function annotation = wormFrameAnnotation()
%FRAMEANNOTATIONCODES Get the video frame annotation information for worm
%segmentation.
%
%   ANNOTATION = WORMFRAMEANNOTATION()
%
%   Output:
%       annotation - a struct of the the video frame annotation information
%                    for worm segmentation; the fields are:
%                    
%                    id       = the annotation id
%                    function = a string describing the function which
%                               generated the annotation
%                    message  = a message describing the annotation
%
% See also SEGWORM, FINDSTAGEMOVEMENT, NORMWORMS
%
%
% © Medical Research Council 2012
% You will not remove any copyright or other notices from the Software; 
% you must reproduce all copyright notices and other proprietary 
% notices on any copies of the Software.

% The video frame annotation for worm segmentation.
annotation = struct( ...
    ... % Annotation IDs.
    'id', ...
    { 1, ...
      2, ...
      3, ...
      101, ...
      102, ...
      103, ...
      104, ...
      105, ...
      106, ...
      107, ...
      108, ...
      109, ...
      110, ...
      111, ...
      1001}, ...
    ... % Annotation function signatures. 
    'function', ...
    { 'segWorm:Success', ...
      'findStageMovement:StageMovement', ...
      'segWorm:DroppedFrame', ...
      'segWorm:NoWormFound', ...
      'segWorm:ContourTouchesBoundary', ...
      'segWorm:ContourTooSmall', ...
      'segWorm:TooManyEnds', ...
      'segWorm:TooFewEnds', ...
      'segWorm:DoubleLengthSide', ...
      'segWorm:DoubleHeadWidth', ...
      'segWorm:DoubleTailWidth', ...
      'segWorm:SmallTail', ...
      'segWorm:SmallHead', ...
      'segWorm:SmallHeadTail', ...
      'normWorms:TooShort'}, ...
    ... % Annotation function signatures. 
    'message', ...
    { 'The worm was successfully segmented.', ...
      'The video frame contains stage motion.', ...
      'The video frame was dropped.', ...
      'No worm was found in the video frame.', ...
      'The worm contour touches the image boundary.', ...
      'The worm contour is too small.', ...
      ['The worm has 3 or more low-frequency sampled convexities ' ...
      'sharper than 90 degrees (possible head/tail points).'], ...
      ['The worm contour has less than 2 high-frequency sampled ' ...
      'convexities sharper than 60 degrees (the head and tail). ' ...
      'Therefore, the worm is coiled or obscured and cannot be ' ...
      'segmented.'], ...
      ['The worm length, from head to tail, is more than twice as ' ...
      'large on one side than it is on the other. Therefore, the worm ' ...
      'is coiled or obscured and cannot be segmented.'], ...
      ['The worm more than doubles its width from the end of its head. ' ...
      'Therefore, the worm is coiled, laid an egg, and/or is ' ...
      'significantly obscured and cannot be segmented'], ...
      ['The worm more than doubles its width from the end of its tail. ' ...
      'Therefore, the worm is coiled, laid an egg, and/or is ' ...
      'significantly obscured and cannot be segmented.'], ...
      ['The worm tail is less than half the size of its head. ' ...
      'Therefore, the worm is significantly obscured and cannot be ' ...
      'segmented.'], ...
      ['The worm head is less than half the size of its tail. ' ...
      'Therefore, the worm is significantly obscured and cannot be ' ...
      'segmented.'], ...
      ['The worm head and tail are less than 1/4 the size of its ' ...
      'remaining body. Therefore, the worm is significantly obscured ' ...
      'and cannot be segmented.'], ...
      'The worm is shorter than the sampling points requested.'});
end