Description of worm2GenotypeLabel
worm2GenotypeLabel
PURPOSE
WORM2GENOTYPELABEL Label the worm genotype.
SYNOPSIS
function label = worm2GenotypeLabel(wormInfo)
DESCRIPTION
WORM2GENOTYPELABEL Label the worm genotype.
   LABEL = WORM2GENOTYPELABEL(WORMINFO)
   Input:
       wormInfo - the worm information
   Output:
       label - the worm label
 See also WORMSTATS2MATRIX
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
worm2TOCOntologyTIF WORM2TOCONTOLOGYTIF Save worm details to a TIF.
worm2detailsTIF WORM2DETAILSTIF Save worm details to a TIF.
worm2summaryTIF WORM2SUMMARYTIF Save a worm summary to a TIF.
wormStatsInfo2CSV WORMSTATSINFO2CSV Convert the worm statistics to a set of CSV files.
wormStats2Matrix WORMSTATS2MATRIX Construct and save a worms x features matrix.
wormStats2Ontology WORMSTATS2ONTOLOGY Convert a worm's significant features to ontology.
SOURCE CODE
function label = worm2GenotypeLabel(wormInfo)
%WORM2GENOTYPELABEL Label the worm genotype.
%
%   LABEL = WORM2GENOTYPELABEL(WORMINFO)
%
%   Input:
%       wormInfo - the worm information
%
%   Output:
%       label - the worm label
%
% See also WORMSTATS2MATRIX
% label = [wormInfo(1).experiment.worm.strain ': ' ...
%     wormInfo(1).experiment.worm.genotype];
label = wormInfo(1).experiment.worm.genotype;
end