Description of circNearestPoints
circNearestPoints
PURPOSE
CIRCNEARESTPOINTS For each point, find the nearest corresponding point
SYNOPSIS
function nearI = circNearestPoints(points, minI, maxI, x)
DESCRIPTION
CIRCNEARESTPOINTS For each point, find the nearest corresponding point
   within an interval of circularly-connected search points.
   NEARI = CIRCNEARESTPOINTS(POINTS, MINI, MAXI, X)
   Inputs:
       points - the point coordinates from which the distance is measured
       minI   - the minimum indices of the intervals
       maxI   - the maximum indices of the intervals
       x      - the circularly-connected, point coordinates on which the
                search intervals lie
   Output:
       nearI - the indices of the nearest points
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
circOpposingNearestPoints CIRCOPPOSINGNEARESTPOINTS Find the nearest equivalent point indices on the
linearSkeleton LINEARSKELETON Skeletonize a linear (non-looped) worm. The worm is
worm2poly WORM2POLY Compute the polygon outline for a worm segment.
SOURCE CODE
function nearI = circNearestPoints(points, minI, maxI, x)
%CIRCNEARESTPOINTS For each point, find the nearest corresponding point
%   within an interval of circularly-connected search points.
%
%   NEARI = CIRCNEARESTPOINTS(POINTS, MINI, MAXI, X)
%
%   Inputs:
%       points - the point coordinates from which the distance is measured
%       minI   - the minimum indices of the intervals
%       maxI   - the maximum indices of the intervals
%       x      - the circularly-connected, point coordinates on which the
%                search intervals lie
%
%   Output:
%       nearI - the indices of the nearest points
% Are the points 2 dimensional?
if ndims(points) ~=2 || (size(points, 1) ~= 2 && size(points, 2) ~= 2)
    error('circNearestPoints:PointsNot2D', ...
        'The matrix of points must be 2 dimensional');
end
% Are the search points 2 dimensional?
if length(size(x)) ~=2 || (size(x, 2) ~= 2 && size(x, 2) ~= 2)
    error('circNearestPoints:XNot2D', ...
        'The circularly-connected search points must be 2 dimensional');
end
% Orient the points as a N-by-2 matrix.
isTransposed = false;
if size(points, 2) ~= 2
    points = points';
    isTransposed = true;
end
% Orient the search points as a N-by-2 matrix.
if size(x, 2) ~= 2
    x = x';
end
% Pre-allocate memory.
nearI(1:size(points, 1)) = NaN;
% Search for the nearest points.
for i = 1:size(points, 1)
    % The interval is continuous.
    if minI(i) <= maxI(i)
        [~, nearI(i)] = min((points(i,1) - x(minI(i):maxI(i),1)).^ 2 + ...
            (points(i,2) - x(minI(i):maxI(i),2)) .^ 2);
        nearI(i) = nearI(i) + minI(i) - 1;
    % The interval wraps.
    else
        [mag1, nearI1] = min((points(i,1) - x(minI(i):end,1)) .^ 2 + ...
            (points(i,2) - x(minI(i):end,2)) .^ 2);
        [mag2, nearI2] = min((points(i,1) - x(1:maxI(i),1)) .^ 2 + ...
            (points(i,2) - x(1:maxI(i),2)) .^ 2);
        % Which point is nearest?
        if mag1 <= mag2
            nearI(i) = nearI1 + minI(i) - 1;
        else
            nearI(i) = nearI2;
        end
    end
end
% Transpose the point indices.
if isTransposed
    nearI = nearI';
end
end