Description of assertSimilarImages
assertSimilarImages
PURPOSE
assertSimilarImages(a,b)
SYNOPSIS
function assertSimilarImages(a,b) %#ok
DESCRIPTION
assertSimilarImages(a,b)
  Checks to see if A and B are similar in an IMAGEDIFF sense using a
  hand-tuned threshold.
  This function has been customized for use with the videoIO tests.
CROSS-REFERENCE INFORMATION
This function calls:
imageDiff d=imageDiff(a,b)
vrassert vrassert(testCondition)
This function is called by:
concatReadTests concatReadTests
doMultiFullReadTest DOMULTIFULLREADTEST(...)
doPreciseSeekTests DOPRECISESEEKTESTS(...)
SOURCE CODE
function assertSimilarImages(a,b)  %#ok<INUSD>
%assertSimilarImages(a,b)
%  Checks to see if A and B are similar in an IMAGEDIFF sense using a
%  hand-tuned threshold.
%
%  This function has been customized for use with the videoIO tests.
maxMeaninglessRms = 4; %#ok<NASGU>
vrassert imageDiff(a,b) < maxMeaninglessRms;