Description of iexit
iexit
PURPOSE
IEXIT(...)
SYNOPSIS
function iexit(varargin)
DESCRIPTION
IEXIT(...)
  Decreases the indentation level then calls IPRINTF on the input
  arguments.  If no input args are used, a message is created using the
  caller's function or script name.  Useful for debugging/tracing.
  If an unhandled error occurs between calls to ienter and iexit, the
  indentation level will not be properly reset.  To reset it, type
     clear all
Example:
  function d = foo
  ienter;
  d = 2+2;
  iprintf('2+2=%d', d);
  iexit;
CROSS-REFERENCE INFORMATION
This function calls:
iexit IEXIT(...)
iprintf IPRINTF(...)
This function is called by:
addFrameDemo addFrameDemo
concatReadTests concatReadTests
doFullRead IMAGES=DOFULLREAD(...)
doMultiFullReadTest DOMULTIFULLREADTEST(...)
doMultiFullReadTestOnAllLoadables DOMULTIFULLREADTESTONALLLOADABLES(...)
doPreciseSeekTests DOPRECISESEEKTESTS(...)
extractFrames Script to create the frames/ subdirectory. The data in that directory is
iexit IEXIT(...)
longWriteTest longWriteTests(plugin)
readIndvFrameTests readIndvFrameTests(plugin,ext,...)
readTests readTests(plugin)
resizeTest writeTests(plugin)
standardTestBattery standardTestBattery(plugin)
testAll testAll
testBitRate testBitRate
testDirectShow testDirectShow
testEcho testEcho
testFfmpeg testFfmpeg
testGet testGet
testGopSize testGopSize
testLoadAndImread testLoadAndImread
testMatrix testMatrix
testQuality testQuality
testVfw testVfw
testVideoRead testVideoRead
test_pvtVideoIO_mexName This is a regression test for the pseudo-private pvtVideoIO_mexName
videoWriterDemo videoWriterDemo
writeTests writeTests(plugin)
SOURCE CODE
function iexit(varargin)
%IEXIT(...)
%  Decreases the indentation level then calls IPRINTF on the input
%  arguments.  If no input args are used, a message is created using the
%  caller's function or script name.  Useful for debugging/tracing.
%
%  If an unhandled error occurs between calls to ienter and iexit, the
%  indentation level will not be properly reset.  To reset it, type
%     clear all
%
%Example:
%  function d = foo
%  ienter;
%  d = 2+2;
%  iprintf('2+2=%d', d);
%  iexit;
global videoIO_test_indentLevel;
if (isempty(videoIO_test_indentLevel))
  videoIO_test_indentLevel = 0;
end
if (nargin == 0)
  st = dbstack;
  iexit('...%s', st(2).name);
elseif (nargin == 1 && isnumeric(varargin{1}))
  st = dbstack;
  iexit(varargin{1}, '...%s', st(2).name);
else
  videoIO_test_indentLevel = videoIO_test_indentLevel - 1;
  iprintf(varargin{:});
end