Description of resizeTest
resizeTest
PURPOSE
writeTests(plugin)
SYNOPSIS
function resizeTest(plugin)
DESCRIPTION
writeTests(plugin)
  Checks to see if automatic resizing of images is working properly for a
  given videoReader/videoWriter plugin using some quick heuristics.
Examples:
  resizeTest
  resizeTest ffmpegPopen2  % linux & similar
  resizeTest ffmpegDirect  % ...if system's gcc is compatible w/ Matlab's
  resizeTest DirectShow    % Windows
CROSS-REFERENCE INFORMATION
This function calls:
close VR=CLOSE(VR)
get INFO=GET(VR)
videoReader videoReader class constructor
addframe ADDFRAME Add video frame to VIDEOWRITER stream.
close VW=CLOSE(VW)
get INFO=GET(VW)
videoWriter videoWriter class constructor
defaultVideoIOPlugin pluginName = defaultVideoIOPlugin(ctor)
ienter IENTER(...)
iexit IEXIT(...)
psychedelicFrame rgbFrame = psychedelicFrame(w,h,i)
vrassert vrassert(testCondition)
This function is called by:
SOURCE CODE
function resizeTest(plugin)
%writeTests(plugin)
%  Checks to see if automatic resizing of images is working properly for a
%  given videoReader/videoWriter plugin using some quick heuristics.
%
%Examples:
%  resizeTest
%  resizeTest ffmpegPopen2  % linux & similar
%  resizeTest ffmpegDirect  % ...if system's gcc is compatible w/ Matlab's
%  resizeTest DirectShow    % Windows
ienter
if nargin < 1, plugin = defaultVideoIOPlugin; end
W = 640;
H = 480;
fname = [tempname '.avi'];
try
  vw = videoWriter(fname, plugin, 'width',W, 'height',H);
  widths = 4:40:640;
  for i=1:length(widths)
    w = widths(i);
    frame = psychedelicFrame(w,w,i);
    addframe(vw, frame);
  end
  vw = close(vw);
  vr = videoReader(fname, plugin);
  info = get(vr); %#ok<NASGU>
  vrassert W == info.width;
  vrassert H == info.height;
  vr = close(vr); %#ok<NASGU>
  delete(fname);
catch
  e = lasterror;
  try close(vw); catch end
  delete(fname);
  rethrow(e);
end
iexit