Description of standardTestBattery
standardTestBattery
PURPOSE
standardTestBattery(plugin)
SYNOPSIS
function standardTestBattery(plugin)
DESCRIPTION
standardTestBattery(plugin)
  Performs a standard battery of tests on a given plugin
Examples:
  standardTestBattery
  standardTestBattery ffmpegPopen2  % linux & similar
  standardTestBattery ffmpegDirect  % ...if system's gcc is compatible w/ Matlab's
  standardTestBattery DirectShow    % Windows
CROSS-REFERENCE INFORMATION
This function calls:
defaultVideoIOPlugin pluginName = defaultVideoIOPlugin(ctor)
concatReadTests concatReadTests
ienter IENTER(...)
iexit IEXIT(...)
longWriteTest longWriteTests(plugin)
readTests readTests(plugin)
testBitRate testBitRate
testGet testGet
testGopSize testGopSize
testQuality testQuality
writeTests writeTests(plugin)
This function is called by:
testDirectShow testDirectShow
testFfmpeg testFfmpeg
SOURCE CODE
function standardTestBattery(plugin)
%standardTestBattery(plugin)
%  Performs a standard battery of tests on a given plugin
%
%Examples:
%  standardTestBattery
%  standardTestBattery ffmpegPopen2  % linux & similar
%  standardTestBattery ffmpegDirect  % ...if system's gcc is compatible w/ Matlab's
%  standardTestBattery DirectShow    % Windows
%
ienter
if nargin < 1, plugin = defaultVideoIOPlugin; end
readTests(plugin);
concatReadTests; % without a plugin specified
concatReadTests(plugin); % with an explicit default
writeTests(plugin);
if ispc
  testGet(plugin);
end
if ~strcmpi(plugin, 'DirectShow') % DShow doesn't support these options now
  testBitRate(plugin);
  testGopSize(plugin);
  testQuality(plugin);
end
longWriteTest(plugin);
iexit