Description of testVfw
testVfw
PURPOSE
testVfw
SYNOPSIS
This is a script file.
DESCRIPTION
testVfw
  Script that runs tests on Windows using the Vfw writer 'Vfw'.
Example:
  testVfw
Copyright (c) 2008 Gerald Dalley
See "MIT.txt" in the installation directory for licensing details (especially
when using this library on GNU/Linux).
CROSS-REFERENCE INFORMATION
This function calls:
buildVideoIO buildVideoIO
ienter IENTER(...)
iexit IEXIT(...)
longWriteTest longWriteTests(plugin)
testBitRate testBitRate
testGopSize testGopSize
testQuality testQuality
writeTests writeTests(plugin)
This function is called by:
testAll testAll
SOURCE CODE
%testVfw
%  Script that runs tests on Windows using the Vfw writer 'Vfw'.
%
%Example:
%  testVfw
%
%Copyright (c) 2008 Gerald Dalley
%See "MIT.txt" in the installation directory for licensing details (especially
%when using this library on GNU/Linux).
ienter
% Make sure we have the most up-to-date version
if exist('buildVideoIO', 'file') == 2, buildVideoIO('DirectShow'); end
writeTests('Vfw', 'DirectShow');
testBitRate('Vfw');
testGopSize('Vfw');
testQuality('Vfw');
longWriteTest('Vfw', 'DirectShow');
iexit