Description of events2array
events2array
PURPOSE
EVENTS2ARRAY Convert a set of events into a logical array.
SYNOPSIS
function isEvent = events2array(frames, totalFrames)
DESCRIPTION
EVENTS2ARRAY Convert a set of events into a logical array.
   ISEVENT = EVENTS2ARRAY(EVENTS, TOTALFRAMES)
   Inputs:
       frames      - the frames at which the even took place (see findEvent);
                     a structure array with fields:
                     start = the start frame
                     end   = the end frame
       totalFrames - the total number of frames in the video
   Output:
       isEvent - a logical array of whether the event occured, per frame
 See also FINDEVENT
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bendAndSpeedTest Initialize our variables.
wormEvents % Compute the multi-scale worm.
wormVelocity WORMVELOCITY Compute the worm velocity (speed & direction) at the
SOURCE CODE
function isEvent = events2array(frames, totalFrames)
%EVENTS2ARRAY Convert a set of events into a logical array.
%
%   ISEVENT = EVENTS2ARRAY(EVENTS, TOTALFRAMES)
%
%   Inputs:
%       frames      - the frames at which the even took place (see findEvent);
%                     a structure array with fields:
%
%                     start = the start frame
%                     end   = the end frame
%
%       totalFrames - the total number of frames in the video
%
%   Output:
%       isEvent - a logical array of whether the event occured, per frame
%
% See also FINDEVENT
% Convert the event frames to an array of where the events take place.
isEvent = false(totalFrames,1);
for i = 1:length(frames)
  % The frames are video indexed, convert them to Matlab indexing.
  isEvent((frames(i).start + 1):(frames(i).end + 1)) = true;
end
end