%% The WT2 information.
%
%
% © Medical Research Council 2012
% You will not remove any copyright or other notices from the Software; 
% you must reproduce all copyright notices and other proprietary 
% notices on any copies of the Software.
wt2 = struct( ...
    'tracker', trackerVersion, ...
    'hardware', hardwareVersion, ...
    'analysis', analysisVersion, ...
    'annotations', systemAnnotations);


%% The video information.
% The microns/pixels.
videoLength = struct( ...
    'frames', videoFrames, ...
    'time', videoTime);
micronsPerPixels = struct( ...
    'x', micronsPerPixelsX, ...
    'y', micronsPerPixelsY);
resolution = struct( ...
    'fps', fps, ...
    'height', height, ...
    'width', width, ...
    'micronsPerPixels', micronsPerPixels, ...
    'fourcc', fourcc);
videoAnnotations = struct( ...
    'frames', frameAnnotations, ...
    'reference', annotationReference);
video = struct( ...
    'length', videoLength, ...
    'resolution', resolution, ...
    'annotations', videoAnnotations);



%% The experiment information.
expFiles = struct( ...
    'video', videoFile, ...
    'vignette', vignetteFile, ...
    'info', infoFile, ...
    'stage', stageLogFile, ...
    'directory', expDirectory, ...
    'computer', expComputer);
expWorm = struct( ...
    'timestamp', expTimestamp, ...
    'genotype', expGenotype, ...
    'gene', expGene, ...
    'allele', expAllele, ...
    'strain', expStrain, ...
    'food', expFood, ...
    'ventralSide', expVentralSide, ...
    'agarSide', expAgarSide, ...
    'sex', expSex, ...
    'age', expAge, ...
    'habituation', expHabituation, ...
    'illumination', expIllumination, ...
    'temperature', expTemperature, ...
    'chemicals', expChemicals, ...
    'arena', expArena, ...
    'tracker', expTracker, ...
    'experimenter', expExperimenter, ...
    'lab', expLab, ...
    'address', expAddress, ...
    'annotations', expAnnotations);
experiment = struct( ...
    'worm', expWorm, ...
    'files', expFiles);



%% The overall information
info = struct( ...
    'wt2', wt2, ...
    'video', video, ...
    'experiment', experiment);
