Description of removePartialEvents
removePartialEvents
PURPOSE
REMOVEPARTIALEVENTS Remove partial events at the start and end of the data.
SYNOPSIS
function eventStats = removePartialEvents(eventStats, totalFrames)
DESCRIPTION
REMOVEPARTIALEVENTS Remove partial events at the start and end of the data.
   EVENTSTATS = REMOVEPARTIALEVENTS(EVENTSTATS, TOTALFRAMES)
   Inputs:
       eventStats  - the event statistics (see events2stats)
       totalFrames - the total number of frames in the video
   Output:
       eventStats - the event statistics (see events2stats) with partial
                    events, at the start and end of the data, removed
   See also EVENTS2STATS
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
wormEvents % Compute the multi-scale worm.
worm2NormTimes WORM2NORMTIMES Normalize worm feature time series.
worm2histogram WORM2HISTOGRAM Convert worm features to their histogram.
SOURCE CODE
function eventStats = removePartialEvents(eventStats, totalFrames)
%REMOVEPARTIALEVENTS Remove partial events at the start and end of the data.
%
%   EVENTSTATS = REMOVEPARTIALEVENTS(EVENTSTATS, TOTALFRAMES)
%
%   Inputs:
%       eventStats  - the event statistics (see events2stats)
%       totalFrames - the total number of frames in the video
%
%   Output:
%       eventStats - the event statistics (see events2stats) with partial
%                    events, at the start and end of the data, removed
%
%   See also EVENTS2STATS
% Remove partially recorded events.
if ~isempty(eventStats)
    if eventStats(1).start == 0
        eventStats(1) = [];
    end
end
if ~isempty(eventStats)
    if eventStats(end).end == totalFrames
        eventStats(end) = [];
    end
end
end