function [ info ] = parseWormFilename2( filename )
%parseWormFilename Parses a filename, from a worm experiment, into a struct
%of information.
%
%   The input argument 'filename' is the file's name as a string. The
%   output 'info' is a struct containing the worm type, strain, whether
%   it's crawling on food, what side it's crawling on, and the timestamp of
%   when the file was created.
% © Medical Research Council 2012
% You will not remove any copyright or other notices from the Software; 
% you must reproduce all copyright notices and other proprietary 
% notices on any copies of the Software.

% Parse the file name.
pattern = ['(?<type>\S+)\s*' ...
    '(?<strain>(\(\w+\)\w*)|\S+)?\s+' ...
    '(?<food>(on|off)\s+food)?\s*' ...
    '(?<side>(L|R|x|LR|RL))?_' ...
    '(?<year>\d\d\d\d)_' ...
    '(?<month>\d\d)_' ...
    '(?<day>\d\d)__' ...
    '(?<hour>\d\d)_' ...
    '(?<minute>\d\d)_' ...
    '(?<second>\d\d)?.*'];
[pathDir, experimentName] = fileparts(filename);
matches = regexpi(experimentName, pattern, 'names');

if ~isempty(matches)
    % Parse the strain.
    smatches(1) = struct('strain', '', 'chromosome', '');
    if ~isempty(matches(1).strain)
        spattern = '\((?<strain>\w+)\)(?<chromosome>\w+)?';
        smatches = regexpi(matches(1).strain, spattern, 'names');
    end
    
    %seconds were lost
    if isempty(matches(1).second)
        matches(1).second = '00';
    end
    % Construct the date.
    date = datenum(str2num(matches(1).year), ...
        str2num(matches(1).month), ...
        str2num(matches(1).day), ...
        str2num(matches(1).hour), ...
        str2num(matches(1).minute), ...
        str2num(matches(1).second));
    
    if isempty(matches(1).side)
        matches(1).side = 'unknown';
    end
    
    if isempty(smatches)
        smatches(1).chromosome = [];
    end
    
    % Fill the info.
    info = struct('type', matches(1).type, ...
        'strain', smatches(1).strain, ...
        'chromosome', smatches(1).chromosome, ...
        'food', strcmp(matches(1).food, 'on food'), ...
        'side', matches(1).side, ...
        'timestamp', date);
else
    %gmail('wormtoolbox@gmail.com','The filename does not parse', strcat(filename,{' - '},datestr(datevec(now))));
    %error('parseWormFilename:NoMatches', 'The filename does not parse');
    info = struct('type', experimentName, ...
        'strain', NaN, ...
        'chromosome', NaN, ...
        'food', NaN, ...
        'side', NaN, ...
        'timestamp', NaN);
end