Description of flipWormVulva
flipWormVulva
PURPOSE
FLIPWORMVULVA Flip the vulval orientation of the worm.
SYNOPSIS
function worm = flipWormVulva(worm)
DESCRIPTION
FLIPWORMVULVA Flip the vulval orientation of the worm.
   WORM = FLIPWORMVULVA(WORM)
   Input:
       worm - the worm to flip
   Output:
       worm - the flipped worm
   See also FLIPWORMCELLVULVA, FLIPWORMHEAD, FLIPWORMDATA, WORM2STRUCT,
   SEGWORM
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
orientWorm ORIENTWORM Orient worm2 to match worm1's orientation (by setting
orientWormAtCentroid ORIENTWORMATCENTROID Orient worm2 to match worm1's orientation (by setting
orientWormPostCoil ORIENTWORMPOSTCOIL Orient worm2 to match worm1's orientation (by setting
segWorm SEGWORM Segment the worm in an image and organize the information in a
segWormVideo SEGWORMVIDEO Segment a worm video.
SOURCE CODE
function worm = flipWormVulva(worm)
%FLIPWORMVULVA Flip the vulval orientation of the worm.
%
%   WORM = FLIPWORMVULVA(WORM)
%
%   Input:
%       worm - the worm to flip
%
%   Output:
%       worm - the flipped worm
%
%   See also FLIPWORMCELLVULVA, FLIPWORMHEAD, FLIPWORMDATA, WORM2STRUCT,
%   SEGWORM
% Flip the worm's vulval side.
worm.orientation.vulva.isClockwiseFromHead = ...
    ~worm.orientation.vulva.isClockwiseFromHead;
tmp = worm.orientation.vulva.confidence.vulva;
worm.orientation.vulva.confidence.vulva = ...
    worm.orientation.vulva.confidence.nonVulva;
worm.orientation.vulva.confidence.nonVulva = tmp;
end