Description of p2stars
p2stars
PURPOSE
P2STARS Convert a p-value to a string of stars representing significance.
SYNOPSIS
function stars = p2stars(p)
DESCRIPTION
P2STARS Convert a p-value to a string of stars representing significance.
   STARS = P2STARS(P)
   Input:
       p - the p-value
   Output:
       stars - a string representing the p-value significance
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
worm2TOCOntologyTIF WORM2TOCONTOLOGYTIF Save worm details to a TIF.
worm2detailsPDF2 WORM2DETAILSPDF Save worm details to a PDF.
worm2detailsTIF WORM2DETAILSTIF Save worm details to a TIF.
wormStats2OntologyCSV WORMSTATS2ONTOLOGYCSV Convert a worm's significant features to an ontology
wormStatsInfo2CSV WORMSTATSINFO2CSV Convert the worm statistics to a set of CSV files.
SOURCE CODE
function stars = p2stars(p)
%P2STARS Convert a p-value to a string of stars representing significance.
%
%   STARS = P2STARS(P)
%
%   Input:
%       p - the p-value
%
%   Output:
%       stars - a string representing the p-value significance
% The p-value is not significant.
stars = 'n.s.';
% Determine the significance of the p-value.
if p <= 0.0001
    stars = '****';
elseif p <= 0.001
    stars = '***';
elseif p <= 0.01
    stars = '**';
elseif p <= 0.05
    stars = '*';
end
end