Description of worm2summaryTIF
worm2summaryTIF
PURPOSE
WORM2SUMMARYTIF Save a worm summary to a TIF.
SYNOPSIS
function [filename pages] = worm2summaryTIF(filename, worm, wormName,varargin)
DESCRIPTION
WORM2SUMMARYTIF Save a worm summary to a TIF.
   [FILENAME PAGES] = WORM2SUMMARYTIF(FILENAME, WORM, WORMNAME)
   [FILENAME PAGES] = WORM2SUMMARYTIF(FILENAME, WORM, WORMNAME,
                                      WORMINFOFILTER, WORMFEATFILTER,
                                      CONTROL, CONTROLNAME,
                                      CONTROLINFOFILTER, CONTROLFEATFILTER,
                                      SIGNIFICANCE, ISSHOW, PAGE,
                                      SAVEQUALITY, ISCLOSE, ISVERBOSE)
   Inputs:
       filename          - the TIF filename;
                           if empty, the file is named
                           "<wormName> [vs <controlName>].tif"
       worm              - the worm histograms or filename
       wormName          - the name for the worm;
                           or, a function handle of the form:
                   LABEL = WORM2LABEL(WORMINFO)
                           wormInfo = the worm information
                           label    = the worm label
                           if empty, we use WORM2STRAINLABEL
       wormInfoFilter    - the worm information filtering criteria;
                           a structure with any of the fields:
              minFPS     = the minimum video frame rate (frames/seconds)
              minTime    = the minimum video time (seconds)
              maxTime    = the maximum video time (seconds)
              minSegTime = the minimum time for segmented video (seconds)
              minRatio   = the minimum ratio for segmented video frames
              minDate    = the minimum date to use (DATENUM)
              maxDate    = the maximum date to use (DATENUM)
              years      = the years to use
              months     = the months to use (1-12)
              weeks      = the weeks to use (1-52)
              days       = the days (of the week) to use (1-7)
              hours      = the hours to use (1-24)
              trackers   = the trackers to use (1-8)
       wormFeatFilter    - the worm feature filtering criteria;
                           a structure with the fields:
               featuresI = the feature indices (see WORMDATAINFO)
               minThr    = the minimum feature value (optional)
               maxThr    = the maximum feature value (optional)
               indices   = the sub indices for the features (optional)
               subFields = the subFields for the features (optional)
       control           - the control histograms or filename;
                           if empty; no control is shown
       controlName       - the name for the control;
                           or, a function handle of the form:
                   LABEL = WORM2LABEL(WORMINFO)
                           wormInfo = the worm information
                           label    = the worm label
                           if empty, we use WORM2STRAINLABEL
       controlInfoFilter - the control indices to use;
                           or, the control filtering criteria
       controlFeatFilter - the control feature filtering criteria
       significance      - the feature statistical significance or filename;
                           if empty; no statistical significance is shown
                           if a struct, the fields are:
                           p     = the p-value, per feature
                           q     = the q-value, per feature
       isShow            - are we showing the figures onscreen?
                           Note: hiding the figures is faster.
       page              - the page number;
                           if empty, the page number is not shown
       saveQuality       - the quality (magnification) for saving the figures;
                           if empty, the figures are not saved
                           the default is none (empty)
       isClose           - shoud we close the figures after saving them?
                           when saving the figure, the default is yes (true)
                           otherwise, the default is no (false)
       isVerbose         - verbose mode displays the progress;
                           the default is yes (true)
   Output:
       filename - the TIF file containing the saved figures;
                  if empty, the figures were not saved
       pages    - the number of pages in the figure file
 See also FILTERWORMINFO, FILTERWORMHIST, WORM2HISTOGRAM, WORM2STATSINFO
CROSS-REFERENCE INFORMATION
This function calls:
color2TeX COLOR2TEX Convert a color to a TeX string.
downSampleHistogram DOWNSAMPLEHISTOGRAM Downsample a histogram(s).
filterHistogram FILTERHISTOGRAM Filter a histogram to remove data.
getStructField GETSTRUCTFIELD Get a field in a structure.
nanHistogram HISTOGRAM Get a histogram full of NaNs.
plotHistogram PLOTHISTOGRAM Plot a histogram(s) of data.
saveTIF SAVETIF Save a figure to a TIF file.
str2colors STR2COLORS Convert a string of colors to RGB values.
wormDataInfo WORMDATAINFO Get information for computing the worm data.
wormDisplayInfo WORMDISPLAYINFO Get information for displaying the worm data.
filterWormHist FILTERWORMHIST Filter worm features to meet specific criteria.
filterWormInfo FILTERWORMINFO Filter worm information to meet specific criteria.
worm2GenotypeLabel WORM2GENOTYPELABEL Label the worm genotype.
worm2StrainLabel WORM2STRAINLABEL Label the worm strain.
wormStatsInfo WORMFEATUREINFO Get information for computing the worm statistics.
This function is called by:
worm2TIF WORM2TIF Save worm information to a TIF.
SUBFUNCTIONS
function drawLegend(h)
function drawHistogramExample(h)
function drawHistogram(dispInfo, worm, wormName, isWormUsed,
function [str sigs] = stats2strs(worm, control, sig, sigI)
function [str sigs] = field2str(worm, isWormUsed,
function color = p2BackColor(p)
SOURCE CODE
function [filename pages] = worm2summaryTIF(filename, worm, wormName, ...
    varargin)
%WORM2SUMMARYTIF Save a worm summary to a TIF.
%
%   [FILENAME PAGES] = WORM2SUMMARYTIF(FILENAME, WORM, WORMNAME)
%
%   [FILENAME PAGES] = WORM2SUMMARYTIF(FILENAME, WORM, WORMNAME,
%                                      WORMINFOFILTER, WORMFEATFILTER,
%                                      CONTROL, CONTROLNAME,
%                                      CONTROLINFOFILTER, CONTROLFEATFILTER,
%                                      SIGNIFICANCE, ISSHOW, PAGE,
%                                      SAVEQUALITY, ISCLOSE, ISVERBOSE)
%
%   Inputs:
%       filename          - the TIF filename;
%                           if empty, the file is named
%                           "<wormName> [vs <controlName>].tif"
%       worm              - the worm histograms or filename
%       wormName          - the name for the worm;
%                           or, a function handle of the form:
%
%                   LABEL = WORM2LABEL(WORMINFO)
%
%                           wormInfo = the worm information
%                           label    = the worm label
%
%                           if empty, we use WORM2STRAINLABEL
%
%       wormInfoFilter    - the worm information filtering criteria;
%                           a structure with any of the fields:
%
%              minFPS     = the minimum video frame rate (frames/seconds)
%              minTime    = the minimum video time (seconds)
%              maxTime    = the maximum video time (seconds)
%              minSegTime = the minimum time for segmented video (seconds)
%              minRatio   = the minimum ratio for segmented video frames
%              minDate    = the minimum date to use (DATENUM)
%              maxDate    = the maximum date to use (DATENUM)
%              years      = the years to use
%              months     = the months to use (1-12)
%              weeks      = the weeks to use (1-52)
%              days       = the days (of the week) to use (1-7)
%              hours      = the hours to use (1-24)
%              trackers   = the trackers to use (1-8)
%
%       wormFeatFilter    - the worm feature filtering criteria;
%                           a structure with the fields:
%
%               featuresI = the feature indices (see WORMDATAINFO)
%               minThr    = the minimum feature value (optional)
%               maxThr    = the maximum feature value (optional)
%               indices   = the sub indices for the features (optional)
%               subFields = the subFields for the features (optional)
%
%       control           - the control histograms or filename;
%                           if empty; no control is shown
%       controlName       - the name for the control;
%                           or, a function handle of the form:
%
%                   LABEL = WORM2LABEL(WORMINFO)
%
%                           wormInfo = the worm information
%                           label    = the worm label
%
%                           if empty, we use WORM2STRAINLABEL
%
%       controlInfoFilter - the control indices to use;
%                           or, the control filtering criteria
%       controlFeatFilter - the control feature filtering criteria
%       significance      - the feature statistical significance or filename;
%                           if empty; no statistical significance is shown
%                           if a struct, the fields are:
%
%                           p     = the p-value, per feature
%                           q     = the q-value, per feature
%
%       isShow            - are we showing the figures onscreen?
%                           Note: hiding the figures is faster.
%       page              - the page number;
%                           if empty, the page number is not shown
%       saveQuality       - the quality (magnification) for saving the figures;
%                           if empty, the figures are not saved
%                           the default is none (empty)
%       isClose           - shoud we close the figures after saving them?
%                           when saving the figure, the default is yes (true)
%                           otherwise, the default is no (false)
%       isVerbose         - verbose mode displays the progress;
%                           the default is yes (true)
%   Output:
%       filename - the TIF file containing the saved figures;
%                  if empty, the figures were not saved
%       pages    - the number of pages in the figure file
%
% See also FILTERWORMINFO, FILTERWORMHIST, WORM2HISTOGRAM, WORM2STATSINFO
% Load the worm.
wormInfo = [];
if ischar(worm)
    load(worm, 'worm', 'wormInfo');
end
% Determine the worm name.
if isempty(wormName) && ~isempty(wormInfo)
    wormName = worm2StrainLabel(wormInfo);
elseif isa(wormName, 'function_handle')
    if ~isempty(wormInfo)
        wormName = wormName(wormInfo);
    else
        wormName = '';
    end
end
% Filter the worm information.
isWormUsed = [];
if ~isempty(varargin)
    wormInfoFilter = varargin{1};
    isWormUsed = filterWormInfo(wormInfo, wormInfoFilter);
end
% Filter the worm features.
if length(varargin) > 1
    % Filter the worm features.
    wormFeatFilter = varargin{2};
    isUsed = filterWormHist(worm, wormFeatFilter);
    % Combine the filters.
    if isempty(isWormUsed)
        isWormUsed = isUsed;
    else
        isWormUsed = isWormUsed & isUsed;
    end
end
% Do we have a control?
control = [];
controlName = [];
isControlUsed = [];
if length(varargin) > 2
    % Load the control.
    control = varargin{3};
    controlInfo = [];
    if ~isempty(control) && ischar(control)
        controlData = load(control, 'worm', 'wormInfo');
        control = controlData.worm;
        controlInfo = controlData.wormInfo;
        clear controlData;
    end
    % Do we have a control?
    if ~isempty(control)
        % Determine the control name.
        if length(varargin) > 3
            controlName = varargin{4};
        end
        if isempty(controlName) && ~isempty(controlInfo)
            controlName = worm2StrainLabel(controlInfo);
        elseif isa(controlName, 'function_handle')
            if ~isempty(controlInfo)
                controlName = controlName(controlInfo);
            else
                controlName = '';
            end
        end
        % Filter the control information.
        isControlUsed = [];
        if length(varargin) > 4
            controlInfoFilter = varargin{5};
            isControlUsed = filterWormInfo(controlInfo, controlInfoFilter);
        end
        % Filter the control features.
        if length(varargin) > 5
            % Filter the worm features.
            controlFeatFilter = varargin{6};
            isUsed = filterWormHist(control, controlFeatFilter);
            % Combine the filters.
            if isempty(isControlUsed)
                isControlUsed = isUsed;
            else
                isControlUsed = isControlUsed & isUsed;
            end
        end
    end
end
% Do we have the statistical significance?
sig = [];
if length(varargin) > 6
    significance = varargin{7};
    % Load the significance.
    if ~isempty(significance) && ischar(significance)
        % Load the significance matrix.
        if ~isempty(whos('-FILE', significance, 'worm'))
            sigData = load(significance, 'worm');
            % Find the genotype.
            genotype = worm2GenotypeLabel(wormInfo);
            strainI = find(cellfun(@(x) strcmp(genotype, x), ...
                sigData.worm.info.genotype));
            % Determine the significance.
            if length(strainI) == 1
                sig.p = sigData.worm.sig.pWValue(strainI,:);
                sig.q = sigData.worm.sig.qWValue.all(strainI,:);
%                 sig.power = sigData.worm.sig.power(strainI,:);
            end
        % Load the strain matrix.
        elseif ~isempty(whos('-FILE', significance, 'significance'))
            sigData = load(significance, 'significance');
            % Determine the significance.
            sig.p = [sigData.significance.features.pWValue];
            sig.q = [sigData.significance.features.qWValue];
%             sig.power = [sigData.significance.features.power];
        end
    % Determine the significance.
    else
        sig = significance;
    end
end
% Are we showing the figures onscreen?
% Note: hiding the figures is faster.
isShow = true;
if length(varargin) > 7
    isShow = varargin{8};
end
% Determine the page number.
pages = 0;
page = 0;
if length(varargin) > 8
    page = varargin{9};
    pages = page;
end
% Determine the quality (magnification) for saving the figures.
saveQuality = []; % don't save the figures
if length(varargin) > 9
    saveQuality = varargin{10};
end
% Are we closing the figures after saving them?
if saveQuality > 0
    isClose = true;
else
    isClose = false;
end
if length(varargin) > 10
    isClose = varargin{11};
end
if ~isShow
    isClose = true;
end
% Are we displaying the progress?
isVerbose = true;
if length(varargin) > 11
    isVerbose = varargin{12};
end
% Construct the file name.
if saveQuality > 0
    % Remove the TIF extension.
    tifExt = '.tif';
    tifName = filename;
    if length(tifName) >= length(tifExt) && ...
            strcmp(filename((end - length(tifExt) + 1):end), tifExt)
        tifName = filename(1:(end - length(tifExt)));
    end
    % Create the filename.
    if isempty(tifName)
        if isempty(controlName)
            tifName = [wormName ' summary'];
        else
            tifName = [wormName ' vs ' controlName ' summary'];
        end
    end
    % Add the TIF extension.
    filename = [tifName '.tif'];
% We are not saving a file.
else
    filename = [];
end
% Initialize the feature information.
dispInfo = wormDisplayInfo();
dataInfo = wormDataInfo();
statsInfo = wormStatsInfo();
dataInfoField = {dataInfo.field};
statsInfoTitle1I = [statsInfo.title1I];
statsInfoIndex = [statsInfo.index];
% Initialize the color scheme.
statColorScale = 0.6;
controlColor = str2colors('k');
morphologyColor = str2colors('m');
morphologyColors1 = [controlColor; str2colors('m')];
morphologyColors2 = [controlColor; str2colors('p')];
postureColor = str2colors('b');
postureColors1 = [controlColor; str2colors('b')];
postureColors2 = [controlColor; str2colors('c')];
postureColors3 = [controlColor; str2colors('s')];
locomotionColor = str2colors('g', -0.5);
locomotionColors1 = [controlColor; str2colors('g')];
locomotionColors2 = [controlColor; str2colors('g', -0.75)];
locomotionColors3 = [controlColor; str2colors('l')];
locomotionColors4 = [controlColor; str2colors('t')];
pathColor = str2colors('n');
pathColors1 = [controlColor; str2colors('n', 0.25)];
pathColors2 = [controlColor; str2colors('n', -0.25)];
% Initialize special ascii symbols.
semChar = '±';
sepStr = '   ¤   ';
% Initialize the page offset for details.
detailPageOff = page + 3;
% Initialize the histogram logarithm mode.
logMode = 2;
% Construct the page titles.
pageTitle = [];
if saveQuality > 0
    % Add the names.
    pageTitle = wormName;
    if ~isempty(controlName)
        pageTitle = ['\it' pageTitle ' vs. ' controlName ' \rm'];
    end
    % Construct the page title.
    pageTitle = [pageTitle sepStr '\bf' ...
        ' ' color2TeX(morphologyColor) 'Morphology\color{black},' ...
        ' ' color2TeX(postureColor) 'Posture\color{black},' ...
        ' ' color2TeX(locomotionColor) 'Motion\color{black},' ...
        ' ' color2TeX(pathColor) 'Path' ...
        ' \color{black}Summary '];
end
%% Draw page 1.
% Display the progress.
if isVerbose
    disp('Printing summary 1/3 ...');
end
% Create a figure.
h = figure;
visStr = 'off';
if isShow
    visStr = 'on';
end
set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
    'PaperType', 'A2', 'Visible', visStr);
hold on;
% Draw an example.
subplotHandle = subplot(4,5,1);
drawHistogramExample(subplotHandle);
% Draw the length.
field = 'morphology.length';
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
sigI = find(statsInfoTitle1I == featureI, 1);
histColors = morphologyColors2;
statColors = histColors * statColorScale;
refPage = detailPageOff + 1;
subplot(4,5,6);
drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
    control, controlName, isControlUsed, sig, sigI, field, [], ...
    histColors, statColors, refPage);
% Draw the width.
field = 'morphology.width';
subFields = { ...
    'head', ...
    'midbody', ...
    'tail'};
locations = [7 2 12];
histColors = morphologyColors1;
statColors = histColors * statColorScale;
refPage = detailPageOff + 1;
for i = 1:length(subFields)
    % Find the info.
    dataField = [field '.' subFields{i}];
    featureI = find(cellfun(@(x) strcmp(x, dataField), dataInfoField));
    sigI = find(statsInfoTitle1I == featureI, 1);
    % Draw the data.
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI, ...
        dataField, [], histColors, statColors, refPage + i);
end
% % Draw the area.
% field = 'morphology.area';
% histColors = morphologyColors2;
% statColors = morphologyColors2;
% refPage = detailPageOff + 5;
% subplot(4,5,6);
% drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
%     control, controlName, isControlUsed, ...
%     field, [], histColors, statColors, refPage);
% Draw the track length.
field = 'posture.tracklength';
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
sigI = find(statsInfoTitle1I == featureI, 1);
histColors = postureColors2;
statColors = histColors * statColorScale;
refPage = detailPageOff + 22;
subplot(4,5,11);
drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
    control, controlName, isControlUsed, sig, sigI, ...
    field, [], histColors, statColors, refPage);
% Draw the amplitude.
field = 'posture.amplitude.max';
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
sigI = find(statsInfoTitle1I == featureI, 1);
histColors = postureColors3;
statColors = histColors * statColorScale;
refPage = detailPageOff + 18;
subplot(4,5,16);
drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
    control, controlName, isControlUsed, sig, sigI, ...
    field, [], histColors, statColors, refPage);
% Draw the wavelength.
field = 'posture.wavelength.primary';
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
sigI = find(statsInfoTitle1I == featureI, 1);
histColors = postureColors3;
statColors = histColors * statColorScale;
refPage = detailPageOff + 20;
subplot(4,5,17);
drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
    control, controlName, isControlUsed, sig, sigI, ...
    field, [], histColors, statColors, refPage);
% Draw the head/midbody/tail bend means.
field = 'posture.bends';
subFields = { ...
    'head', ...
    'midbody', ...
    'tail'};
locations = 3:5;
histColors = postureColors1;
statColors = histColors * statColorScale;
refPage = detailPageOff + 6;
for i = 1:length(subFields)
    % Find the info.
    dataField = [field '.' subFields{i} '.mean'];
    featureI = find(cellfun(@(x) strcmp(x, dataField), dataInfoField));
    sigI = find(statsInfoTitle1I == featureI, 1);
    % Draw the data.
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI, ...
        dataField, [], histColors, statColors, ...
        refPage + 2 * i);
end
% Draw the head/midbody/tail bend standard deviations.
field = 'posture.bends';
subFields = { ...
    'head', ...
    'midbody', ...
    'tail'};
locations = 8:10;
histColors = postureColors1;
statColors = histColors * statColorScale;
refPage = detailPageOff + 11;
for i = 1:length(subFields)
    % Find the info.
    dataField = [field '.' subFields{i} '.stdDev'];
    featureI = find(cellfun(@(x) strcmp(x, dataField), dataInfoField));
    sigI = find(statsInfoTitle1I == featureI, 1);
    % Draw the data.
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI, ...
        dataField, [], histColors, statColors, refPage + 2 * i);
end
% Draw the head/midbody/tail bend amplitudes.
field = 'locomotion.bends';
subFields = { ...
    'head', ...
    'midbody', ...
    'tail'};
locations = 13:15;
histColors = locomotionColors1;
statColors = histColors * statColorScale;
refPage = detailPageOff + 48;
for i = 1:length(subFields)
    % Find the info.
    dataField = [field '.' subFields{i} '.amplitude'];
    featureI = find(cellfun(@(x) strcmp(x, dataField), dataInfoField));
    sigI = find(statsInfoTitle1I == featureI, 1);
    % Draw the data.
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI, ...
        dataField, [], histColors, statColors, refPage + i);
end
% Draw the head/midbody/tail bend frequencies.
field = 'locomotion.bends';
subFields = { ...
    'head', ...
    'midbody', ...
    'tail'};
locations = 18:20;
histColors = locomotionColors1;
statColors = histColors * statColorScale;
refPage = detailPageOff + 52;
for i = 1:length(subFields)
    % Find the info.
    dataField = [field '.' subFields{i} '.frequency'];
    featureI = find(cellfun(@(x) strcmp(x, dataField), dataInfoField));
    sigI = find(statsInfoTitle1I == featureI, 1);
    % Draw the data.
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI, ...
        dataField, [], histColors, statColors, refPage + i, logMode);
end
%% Save page 1.
% Draw the legend.
drawLegend(h);
% Save the figure.
page = page + 1;
if saveQuality > 0
    saveTIF(h, filename, saveQuality, true, pageTitle, page, isClose);
% Close the figure.
elseif ~isShow || isClose
    close(h);
end
%% Draw page 2.
% Display the progress.
if isVerbose
    disp('Printing summary 2/3 ...');
end
% Create a figure.
h = figure;
if isShow
    set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
        'PaperType', 'A2');
else
    set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
        'PaperType', 'A2', 'Visible', 'off');
end
hold on;
% Draw the foraging amplitude.
field = 'locomotion.bends.foraging.amplitude';
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
sigI = find(statsInfoTitle1I == featureI, 1);
histColors = locomotionColors4;
statColors = histColors * statColorScale;
refPage = detailPageOff + 48;
subplot(4,5,1);
drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
    control, controlName, isControlUsed, sig, sigI, ...
    field, [], histColors, statColors, refPage);
% Draw the foraging speed.
field = 'locomotion.bends.foraging.angleSpeed';
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
sigI = find(statsInfoTitle1I == featureI, 1);
histColors = locomotionColors4;
statColors = histColors * statColorScale;
refPage = detailPageOff + 52;
subplot(4,5,2);
drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
    control, controlName, isControlUsed, sig, sigI, ...
    field, [], histColors, statColors, refPage, logMode);
% Draw the eigen projections.
field = 'posture.eigenProjection';
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
locations = [6:7, 11:12, 16:17];
histColors = postureColors1;
statColors = histColors * statColorScale;
refPage = detailPageOff + 28;
for i = 1:length(locations)
    % Find the info.
    sigI = find(statsInfoTitle1I == featureI & statsInfoIndex == i, 1);
    % Draw the data.
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI, ...
        field, i, histColors, statColors, refPage + i);
end
% Draw the head/midbody/tail speed.
field = 'locomotion.velocity';
subFields = { ...
    'head', ...
    'midbody', ...
    'tail'};
locations = 3:5;
histColors = locomotionColors1;
statColors = histColors * statColorScale;
refPage = detailPageOff + 38;
for i = 1:length(subFields)
    % Find the info.
    dataField = [field '.' subFields{i} '.speed'];
    featureI = find(cellfun(@(x) strcmp(x, dataField), dataInfoField));
    sigI = find(statsInfoTitle1I == featureI, 1);
    % Draw the data.
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI, ...
        dataField, [], histColors, statColors, refPage + i, logMode);
end
% Draw the head/midbody/tail direction.
field = 'locomotion.velocity';
subFields = { ...
    'head', ...
    'midbody', ...
    'tail'};
locations = 8:10;
histColors = locomotionColors1;
statColors = histColors * statColorScale;
refPage = detailPageOff + 43;
for i = 1:length(subFields)
    % Find the info.
    dataField = [field '.' subFields{i} '.direction'];
    featureI = find(cellfun(@(x) strcmp(x, dataField), dataInfoField));
    sigI = find(statsInfoTitle1I == featureI, 1);
    % Draw the data.
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI, ...
        dataField, [], histColors, statColors, refPage + i, logMode);
end
% Draw the omega turns time/inter-time/inter-distance.
field = 'locomotion.turns.omegas';
subFields = { ...
    'time', ...
    'interTime', ...
    'interDistance'};
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
sigI = find(statsInfoTitle1I == featureI, 1);
extraFields = { ...
    [field '.timeRatio'], ...
    [field '.frequency'], ...
    []};
extraFieldNames = { ...
    'TIME(%)', ...
    'FREQ', ...
    []};
isExtraPercent = { ...
    true, ...
    false, ...
    []};
extraSigI = { ...
    sigI + 1, ...
    sigI, ...
    []};
sigI = sigI + 2; % skip the summary statistics
locations = 13:15;
histColors = locomotionColors2;
statColors = histColors * statColorScale;
refPage = detailPageOff + 56;
for i = 1:length(subFields)
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI + (i - 1) * 4, ...
        [field '.' subFields{i}], [], histColors, statColors, refPage, ...
        logMode, extraFields{i}, extraFieldNames{i}, isExtraPercent{i}, ...
        extraSigI{i});
end
% Draw the upsilon turns time/inter-time/inter-distance.
field = 'locomotion.turns.upsilons';
subFields = { ...
    'time', ...
    'interTime', ...
    'interDistance'};
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
sigI = find(statsInfoTitle1I == featureI, 1);
extraFields = { ...
    [field '.timeRatio'], ...
    [field '.frequency'], ...
    []};
extraFieldNames = { ...
    'TIME(%)', ...
    'FREQ', ...
    []};
isExtraPercent = { ...
    true, ...
    false, ...
    []};
extraSigI = { ...
    sigI + 1, ...
    sigI, ...
    []};
sigI = sigI + 2; % skip the summary statistics
locations = 18:20;
histColors = locomotionColors3;
statColors = histColors * statColorScale;
refPage = detailPageOff + 57;
for i = 1:length(subFields)
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI + (i - 1) * 4, ...
        [field '.' subFields{i}], [], histColors, statColors, refPage, ...
        logMode, extraFields{i}, extraFieldNames{i}, isExtraPercent{i}, ...
        extraSigI{i});
end
%% Save page 2.
% Draw the legend.
drawLegend(h);
% Save the figure.
page = page + 1;
if saveQuality > 0
    saveTIF(h, filename, saveQuality, true, pageTitle, page, isClose);
% Close the figure.
elseif ~isShow || isClose
    close(h);
end
%% Draw page 3.
% Display the progress.
if isVerbose
    disp('Printing summary 3/3 ...');
end
% Create a figure.
h = figure;
if isShow
    set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
        'PaperType', 'A2');
else
    set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
        'PaperType', 'A2', 'Visible', 'off');
end
hold on;
% Draw the range.
field = 'path.range';
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
sigI = find(statsInfoTitle1I == featureI, 1);
histColors = pathColors1;
statColors = histColors * statColorScale;
refPage = detailPageOff + 58;
subplot(4,5,1);
drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
    control, controlName, isControlUsed, sig, sigI, ...
    field, [], histColors, statColors, refPage, logMode);
% Draw the worm/head/midbody/tail durations.
field = 'path.duration';
subFields = { ...
    'head', ...
    'midbody', ...
    'tail'};
locations = [6, 11, 16];
histColors = pathColors2;
statColors = histColors * statColorScale;
refPage = detailPageOff + 59;
for i = 1:length(subFields)
    % Find the info.
    dataField = [field '.' subFields{i}];
    featureI = find(cellfun(@(x) strcmp(x, dataField), dataInfoField));
    sigI = find(statsInfoTitle1I == featureI, 1);
    % Draw the data.
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI, ...
        dataField, [], histColors, statColors, refPage, logMode);
end
% Draw the kinks.
field = 'posture.kinks';
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
sigI = find(statsInfoTitle1I == featureI, 1);
histColors = postureColors2;
statColors = histColors * statColorScale;
refPage = detailPageOff + 24;
subplot(4,5,2);
drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
    control, controlName, isControlUsed, sig, sigI, ...
    field, [], histColors, statColors, refPage);
% Draw the coils time/inter-time/inter-distance.
field = 'posture.coils';
subFields = { ...
    'time', ...
    'interTime', ...
    'interDistance'};
featureI = find(cellfun(@(x) strcmp(x, field), dataInfoField));
sigI = find(statsInfoTitle1I == featureI, 1);
extraFields = { ...
    [field '.timeRatio'], ...
    [field '.frequency'], ...
    []};
extraFieldNames = { ...
    'TIME(%)', ...
    'FREQ', ...
    []};
isExtraPercent = { ...
    true, ...
    false, ...
    []};
extraSigI = { ...
    sigI + 1, ...
    sigI, ...
    []};
sigI = sigI + 2; % skip the summary statistics
locations = 3:5;
histColors = postureColors1;
statColors = histColors * statColorScale;
refPage = detailPageOff + 25;
for i = 1:length(subFields)
    subplot(4,5,locations(i));
    drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
        control, controlName, isControlUsed, sig, sigI + i - 1, ...
        [field '.' subFields{i}], [], histColors, statColors, refPage, ...
        logMode, extraFields{i}, extraFieldNames{i}, isExtraPercent{i}, ...
        extraSigI{i});
end
% Draw the forward/paused/backward time/distance/inter-time/inter-distance.
field = 'locomotion.motion';
subFields1 = { ...
    'forward', ...
    'paused', ...
    'backward'};
subFields2 = { ...
    'time', ...
    'distance', ...
    'interTime', ...
    'interDistance'};
extraFields = { ...
    'ratio.time', ...
    'ratio.distance', ...
    'frequency', ...
    []};
extraFieldNames = { ...
    'TIME(%)', ...
    'DIST(%)', ...
    'FREQ', ...
    []};
isExtraPercent = { ...
    true, ...
    true, ...
    false, ...
    []};
extraSigOff = { ...
    1, ...
    2, ...
    0, ...
    []};
locations = [7:10, 12:15, 17:20];
histColors = { ...
    locomotionColors3, ...
    locomotionColors1, ...
    locomotionColors2};
statColors = { ...
    histColors{1} * statColorScale, ...
    histColors{2} * statColorScale, ...
    histColors{3} * statColorScale};
refPage = detailPageOff + 34;
for i = 1:length(subFields1)
    % Find the info.
    dataField = [field '.' subFields1{i}];
    featureI = find(cellfun(@(x) strcmp(x, dataField), dataInfoField));
    sigI = find(statsInfoTitle1I == featureI, 1);
    % Draw the data.
    for j = 1:length(subFields2)
        % Assemble the extra field.
        extraField = [];
        if ~isempty(extraFields{j})
            extraField = [field '.' subFields1{i} '.' extraFields{j}];
        end
        % Draw the data.
        subplot(4,5,locations((i - 1) * length(subFields2) + j));
        drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
            control, controlName, isControlUsed, sig, sigI + 3 + j - 1, ...
            [dataField  '.' subFields2{j}], [], ...
            histColors{i}, statColors{i}, refPage + i, ...
            logMode, extraField, extraFieldNames{j}, isExtraPercent{j}, ...
            sigI + extraSigOff{j});
    end
end
%% Save page 3.
% Draw the legend.
drawLegend(h);
% Save the figure.
page = page + 1;
if saveQuality > 0
    saveTIF(h, filename, saveQuality, true, pageTitle, page, isClose);
% Close the figure.
elseif ~isShow || isClose
    close(h);
end
% Compute the pages.
pages = page - pages;
end
%% Show the legend.
function drawLegend(h)
% Initialize the drawing information.
fontSize = 18;
black = str2colors('k');
white = str2colors('w');
controlColor = str2colors('k');
morphologyColor = str2colors('m');
postureColor = str2colors('b');
locomotionColor = str2colors('g', -0.5);
pathColor = str2colors('n');
% Setup the label information.
label = {
    ' \bfCONTROL '
    ' \bfMORPHOLOGY '
    ' \bfPOSTURE '
    ' \bfMOTION '
    ' \bfPATH '
    ' \bf****\rm (\itq \leq 0.0001\rm) '
    ' \bf***\rm (\itq \leq 0.001\rm) '
    ' \bf**\rm (\itq \leq 0.01\rm) '
    ' \bf*\rm (\itq \leq 0.05\rm) '
    ' \bfn.s. '};
backColor = {
    controlColor
    morphologyColor
1000     postureColor
1001     locomotionColor
1002     pathColor
1003     p2BackColor(0.00003)
1004     p2BackColor(0.0003)
1005     p2BackColor(0.003)
1006     p2BackColor(0.03)
1007     white};
1008 foreColor = {
1009     white
1010     white
1011     white
1012     white
1013     white
1014     black
1015     black
1016     black
1017     black
1018     black};
1019
1020 % Setup the margin.
1021 xOff = 10^-3;
1022 xPosOff = 1 - xOff;
1023 textPosition = [xPosOff, 0, xOff, 1];
1024 textAxis = axes('units', 'normalized', 'Position', textPosition, ...
1025     'XTick', [], 'YTick', [], 'Parent', h);
1026
1027 % Draw the labels.
1028 yStart = 0.99;
1029 yStart2 = 0.95;
1030 yStart3 = 0.73;
1031 yOff = 0.03;
1032 for i = 1:length(label)
1033
1034     % Draw the label.
1035     text(xOff, yStart - (i - 1) * yOff, label{i}, ...
1036         'FontSize', fontSize, ...
1037         'HorizontalAlignment', 'right', ...
1038         'VerticalAlignment', 'top', ...
1039         'BackgroundColor', backColor{i}, ...
1040         'Color', foreColor{i}, ...
1041         'EdgeColor', 'k', ...
1042         'Parent', textAxis);
1043
1044     % Put in a space.
1045     if i == 1
1046         yStart = yStart2 + i * yOff;
1047     elseif i == 5
1048         yStart = yStart3 + i * yOff;
1049     end
1050 end
1051 end
1052
1053
1054
1055 %% Draw a histogram example.
1056 function drawHistogramExample(h)
1057
1058 % Initialize the plot.
1059 set(h, 'Box', 'on');
1060 set(h, 'LineWidth', 1);
1061 %set(h, 'Color', str2colors('r', 0.75));
1062
1063 % Initialize special ascii symbols.
1064 semChar = '±';
1065 sepStr = ' \bf¤\rm ';
1066
1067 % Initialize special text symbols and directives.
1068 titleFont = '\fontsize{12}';
1069 statFont = '\fontsize{10}';
1070 axisFont = '\fontsize{10}';
1071 legendFont = '\fontsize{9}';
1072
1073 % Construct the title text.
1074 titleStr = '\bfFEATURE NAME (D="DORSAL" V="VENTRAL")\rm';
1075 statStr1 = ['\bfM\rm = Mean(X)' sepStr '\bfA\rm = Mean(Abs(X))' sepStr ...
1076     '\bfP\rm = Mean(X > 0)' sepStr '\bfN\rm = Mean(X < 0)'];
1077 statStr2 = ['\bfExperiment[Control]\rm' sepStr ...
1078     '\itStatistic=Mean ' semChar 'SEM\rm' sepStr ...
1079     '\bfBold\rightarrow q \leq 0.05\rm'];
1080 titleName = {[titleFont titleStr ' '], ...
1081     [statFont statStr1 ' '], [statStr2 ' ']};
1082
1083 % Construct the x-axis label.
1084 xStr = '\bfFeature Units \rm\it(Page # for Details)';
1085 xAxisName = [axisFont xStr];
1086
1087 % Construct the worm histogram.
1088 resolution = 1000;
1089 wormAlpha = 6;
1090 wormBound = 1;
1091 wormMean = 4;
1092 wormStdDev = wormBound / wormAlpha;
1093 wormPDF = gausswin(resolution, wormAlpha)';
1094 wormPDF = wormPDF ./ sum(wormPDF);
1095 wormBins = linspace(wormMean - wormBound, wormMean + wormBound, ...
1096     resolution);
1097 histData = [nanHistogram(), nanHistogram()];
1098 histData(1).bins = wormBins;
1099 histData(1).PDF = wormPDF;
1100 histData(1).sets.mean.all = wormMean;
1101 histData(1).sets.stdDev.all = wormStdDev;
1102 histData(1).sets.samples = 1;
1103 histData(1).resolution = wormBins(2) - wormBins(1);
1104 histData(1).isZeroBin = true;
1105 histData(1).isSigned = false;
1106
1107 % Construct the control histogram.
1108 resolution = 1000;
1109 wormAlpha = 4;
1110 wormBound = 2;
1111 wormMean = 3;
1112 wormStdDev = wormBound / wormAlpha;
1113 wormPDF = gausswin(resolution, wormAlpha)';
1114 wormPDF = wormPDF ./ sum(wormPDF);
1115 wormBins = linspace(wormMean - wormBound, wormMean + wormBound, ...
1116     resolution);
1117 histData(2).bins = wormBins;
1118 histData(2).PDF = wormPDF;
1119 histData(2).sets.mean.all = nan;
1120 histData(2).sets.stdDev.all = nan;
1121 histData(2).sets.samples = nan;
1122 histData(2).resolution = wormBins(2) - wormBins(1);
1123 histData(2).isZeroBin = true;
1124 histData(2).isSigned = false;
1125
1126 % Plot the histogram(s).
1127 histColors = str2colors(['n' 'k']);
1128 statColors = histColors * 0.6;
1129 plotHistogram(histData, titleName, xAxisName, [axisFont '\bf'], [], ...
1130     histColors, statColors, 1, 0, 2, 1);
1131 %ylim([0 1.9]);
1132
1133 % Show the legend.
1134 legendStr = { ...
1135     [legendFont '\bfExperiment Histogram']
1136     [legendFont '\bfControl Histogram']
1137     [legendFont '\bfMean\rm(Absolute(X))']
1138     [legendFont '\bfSEM']};
1139 legendHandle = legend(legendStr, 'Location', 'NorthWest');
1140 set(legendHandle, 'Box', 'off');
1141 set(gca, 'XTick', 1:5);
1142
1143 % Show the significance.
1144 sigFontSize = 9;
1145 xOff = 1.05;
1146 yOff = 0.0005;
1147 stepY = 0.0007;
1148 text(xOff, yOff + stepY * 3, '\bf q \leq 0.0001 ****', ...
1149     'FontSize', sigFontSize, ...
1150     'HorizontalAlignment', 'left', ...
1151     'VerticalAlignment', 'bottom', ...
1152     'BackgroundColor', p2BackColor(0.00005), ...
1153     'EdgeColor', str2colors('k'));
1154 text(xOff, yOff + stepY * 2, '\bf q \leq 0.001 ***', ...
1155     'FontSize', sigFontSize, ...
1156     'HorizontalAlignment', 'left', ...
1157     'VerticalAlignment', 'bottom', ...
1158     'BackgroundColor', p2BackColor(0.0005), ...
1159     'EdgeColor', str2colors('k'));
1160 text(xOff, yOff + stepY * 1, '\bf q \leq 0.01 **', ...
1161     'FontSize', sigFontSize, ...
1162     'HorizontalAlignment', 'left', ...
1163     'VerticalAlignment', 'bottom', ...
1164     'BackgroundColor', p2BackColor(0.005), ...
1165     'EdgeColor', str2colors('k'));
1166 text(xOff, yOff, '\bf q \leq 0.05 *', ...
1167     'FontSize', sigFontSize, ...
1168     'HorizontalAlignment', 'left', ...
1169     'VerticalAlignment', 'bottom', ...
1170     'BackgroundColor', p2BackColor(0.03), ...
1171     'EdgeColor', str2colors('k'));
1172
1173 % Explain the extra statistics.
1174 % extraStr = {
1175 %     'Extra Title Statistics:'
1176 %     'F = "Frequency" (Hz)'
1177 %     'T = "Time Ratio" (0 to 1)'
1178 %     'D = "Distance Ratio" (0 to 1)'
1179 %     };
1180 % text(1.1, 1, extraStr, ...
1181 %     'HorizontalAlignment', 'left', ...
1182 %     'VerticalAlignment', 'top', ...
1183 %     'BackgroundColor', str2colors('y'), ...
1184 %     'EdgeColor', str2colors('k'));
1185 end
1186
1187
1188
1189 %% Draw a histogram.
1190 %
1191 % varargin:
1192 %
1193 % logMode         - are we using a log plot?
1194 % extraField      - the extra field to show in the title
1195 % extraName       - the name for the extra field to show in the title
1196 % isExtraPercent  - should the extra field be converted to a percent?
1197 % extraSigI       - the significance index for the extra field
1198 function drawHistogram(dispInfo, worm, wormName, isWormUsed, ...
1199     control, controlName, isControlUsed, sig, sigI, field, index, ...
1200     histColors, statColors, refPage, varargin)
1201
1202 % Are we using a log plot?
1203 logMode = [];
1204 if ~isempty(varargin)
1205     logMode = varargin{1};
1206 end
1207
1208 % Are we showing any extra fields?
1209 extraField = [];
1210 extraName = [];
1211 extraSigI = [];
1212 if length(varargin) > 4
1213     extraField = varargin{2};
1214     extraName = varargin{3};
1215     isExtraPercent = varargin{4};
1216     extraSigI = varargin{5};
1217 end
1218
1219 % Get the worm histogram data.
1220 data = getStructField(worm, field);
1221 if ~isempty(index)
1222     data = data(index);
1223 end
1224 wormHist = data.histogram;
1225
1226 % Filter the histogram.
1227 if ~isempty(isWormUsed)
1228     wormHist = filterHistogram(wormHist, isWormUsed);
1229 end
1230
1231 % Fix the colors.
1232 controlHist = [];
1233 if isempty(control)
1234     histColors = histColors(end,:);
1235     statColors = statColors(end,:);
1236
1237 % Get the control histogram data.
1238 else
1239     data = getStructField(control, field);
1240     if ~isempty(index)
1241         data = data(index);
1242     end
1243     controlHist = data.histogram;
1244
1245     % Filter the histogram.
1246     if ~isempty(isControlUsed)
1247         controlHist = filterHistogram(controlHist, isControlUsed);
1248     end
1249 end
1250
1251 % Are we showing a page number for the non-summary details?
1252 pageStr = '';
1253 if ~isempty(refPage)
1254     pageStr = [' \it(Page ' num2str(refPage) ')'];
1255 end
1256
1257 % Initialize special text symbols and directives.
1258 titleFont = '\fontsize{10}';
1259 statFont = '\fontsize{8}';
1260 axisFont = '\fontsize{10}';
1261 tickFontSize = 8;
1262
1263 % Determine the data index.
1264 if isempty(index)
1265     index = 1;
1266 end
1267
1268 % Determine the figure information.
1269 info = getStructField(dispInfo, field);
1270 fieldName = info(index).name;
1271 fieldUnit = info(index).unit;
1272
1273 % Construct the worm statistics text.
1274 titleName{1} = [titleFont '\bf' upper(fieldName) '\rm '];
1275 [str sigs] = stats2strs(wormHist, controlHist, sig, sigI);
1276 str{1} = [statFont str{1}];
1277 titleName(2:(length(str) + 1)) = str;
1278
1279 % Convert the extra field to a string.
1280 if ~isempty(extraField)
1281     [titleName{end + 1} sigs(end + 1)] = field2str(worm, isWormUsed, ...
1282         control, isControlUsed, extraField, extraName, isExtraPercent, ...
1283         sig, extraSigI);
1284 end
1285
1286 % Construct the x-axis label.
1287 logStr = '';
1288 unitStr = fieldUnit;
1289 if logMode > 1
1290     logStr = 'Log_{10}';
1291     unitStr = ['' unitStr ''];
1292 end
1293 xAxisName = [axisFont '\bf' logStr unitStr '\rm' pageStr ' '];
1294
1295 % Plot the histogram(s).
1296 histData = downSampleHistogram([controlHist, wormHist]);
1297 plotHistogram(histData, titleName, xAxisName, [axisFont '\bf'], [], ...
1298     histColors, statColors, 1, 0, 2, 1, logMode);
1299
1300 % Fix the x-axis ticks.
1301 if ~isempty(tickFontSize)
1302     set(gca, 'FontSize', tickFontSize);
1303 end
1304
1305 % Color the significance.
1306 minSig = min(sigs);
1307 if ~isnan(minSig)
1308     set(gca, 'Color', p2BackColor(minSig));
1309 end
1310 end
1311
1312
1313
1314 %% Convert the statistics to strings.
1315 function [str sigs] = stats2strs(worm, control, sig, sigI)
1316
1317 % No data.
1318 if (isempty(worm) || isnan(worm.resolution)) && ...
1319         (isempty(control) || isnan(control.resolution))
1320     str = {[statFont 'NO DATA']};
1321     sigs = NaN;
1322     return;
1323 end
1324
1325 % Initialize special ascii symbols.
1326 semChar = '±';
1327 sepStr = ' \bf¤\rm ';
1328
1329 % Initialize the fields.
1330 fields = {
1331     'all'
1332     'abs'
1333     'pos'
1334     'neg'};
1335 names = {
1336     'M'
1337     'A'
1338     'P'
1339     'N'};
1340
1341 % Is the feature signed?
1342 if ~isnan(worm.isSigned) && worm.isSigned
1343     endI = 4;
1344     meanFormat = '%.0G';
1345     semFormat = '%.1G';
1346 else
1347     endI = 1;
1348     meanFormat = '%.3G';
1349     semFormat = '%.3G';
1350 end
1351
1352 % Allocate memory.
1353 %str = cell(ceil(endI / 2) + 1, 1);
1354 str = cell(ceil(endI / 2), 1);
1355 sigs = nan(endI, 1);
1356
1357 % % Show the worm samples.
1358 % if isnan(worm.sets.samples)
1359 %     wormsStr = '0';
1360 % else
1361 %     wormsStr = num2str(worm.sets.samples, '%.3G');
1362 % end
1363 % str{1} = ['W=' wormsStr];
1364 %
1365 % % Show the control samples.
1366 % if ~isempty(control)
1367 %     if isnan(control.sets.samples)
1368 %         controlsStr = '0';
1369 %     else
1370 %         controlsStr = num2str(control.sets.samples, '%.3G');
1371 %     end
1372 %     str{1} = [str{1} '[' controlsStr ']'];
1373 % end
1374 %
1375 % % Show the total worm samples.
1376 % if isnan(worm.allData.samples)
1377 %     wormsTotalStr = '0';
1378 % else
1379 %     wormsTotalStr = num2str(worm.allData.samples, '%.3G');
1380 % end
1381 % str{1} = [str{1} sepStr 'S=' wormsTotalStr];
1382 %
1383 % % Show the total control samples.
1384 % if ~isempty(control)
1385 %     if isnan(control.allData.samples)
1386 %         controlsTotalStr = '0';
1387 %     else
1388 %         controlsTotalStr = num2str(control.allData.samples, '%.3G');
1389 %     end
1390 %     str{1} = [str{1} '[' controlsTotalStr ']'];
1391 % end
1392
1393 % Determine the square root of the sample sets.
1394 wormSqrt = sqrt(worm.sets.samples);
1395 if ~isempty(control)
1396     controlSqrt = sqrt(control.sets.samples);
1397 end
1398
1399 % Convert the statistics to strings.
1400 for i = 1:endI
1401
1402     % Determine the inequality between experiment and control.
1403     wormMean = worm.sets.mean.(fields{i});
1404     eqStr = '';
1405     if ~isempty(control)
1406         controlMean = control.sets.mean.(fields{i});
1407         if wormMean > controlMean
1408             eqStr = '>';
1409         elseif wormMean < controlMean
1410             eqStr = '<';
1411         end
1412     end
1413
1414     % Don't show the inequality between experiment and control.
1415     if isempty(sig)
1416         eqStr = '';
1417
1418     % Determine the significance.
1419     else
1420         k = sigI + i - 1;
1421         sigs(i) = sig.q(k);
1422         if isnan(sigs(i)) || sigs(i) > 0.05
1423             eqStr = '';
1424         end
1425     end
1426
1427     % Determine the separator string.
1428     preStr = [];
1429     if ~mod(i, 2)
1430         preStr = sepStr;
1431     end
1432
1433     % Show the worm statistics.
1434     if isnan(wormMean)
1435         dataStr = 'X';
1436     else
1437         meanStr = num2str(wormMean, meanFormat);
1438         semStr = num2str(worm.sets.stdDev.(fields{i}) / wormSqrt, ...
1439             semFormat);
1440         dataStr = [meanStr semChar semStr];
1441     end
1442     statStr = [names{i} '=' dataStr];
1443
1444     % Show the control statistics.
1445     if ~isempty(control)
1446         if isnan(controlMean)
1447             dataStr = 'X';
1448         else
1449             meanStr = num2str(controlMean, meanFormat);
1450             semStr = num2str(control.sets.stdDev.(fields{i}) / ...
1451                 controlSqrt, semFormat);
1452             dataStr = [meanStr semChar semStr];
1453         end
1454         statStr = [statStr eqStr '[' dataStr ']'];
1455     end
1456
1457     % Show the significance.
1458     if sigs(i) <= 0.05
1459         statStr = ['\bf' statStr '\rm'];
1460     end
1461
1462     %j = floor((i + 3) / 2);
1463     j = ceil(i / 2);
1464     str{j} = [str{j} preStr statStr];
1465 end
1466 end
1467
1468
1469
1470 %% Convert the field statistics to a string.
1471 function [str sigs] = field2str(worm, isWormUsed, ...
1472     control, isControlUsed, field, name, isPercent, sig, sigI)
1473
1474 % Initialize special ascii symbols.
1475 semChar = '±';
1476
1477 % Show the name.
1478 str = [name '='];
1479
1480 % Get the worm data.
1481 wormData = getStructField(worm, [field '.data']);
1482 if ~isempty(isWormUsed)
1483     wormData = wormData(isWormUsed);
1484 end
1485 wormMean = mean(wormData);
1486 wormSEM = std(wormData) / sqrt(length(wormData));
1487
1488 % Get the control data.
1489 if ~isempty(control)
1490     controlData = getStructField(control, [field '.data']);
1491     if ~isempty(isControlUsed)
1492         controlData = controlData(isControlUsed);
1493     end
1494     controlMean = mean(controlData);
1495     controlSEM = std(controlData) / sqrt(length(controlData));
1496 end
1497
1498 % Convert the data to percent.
1499 if isPercent
1500     wormMean = wormMean * 100;
1501     wormSEM = wormSEM * 100;
1502     if ~isempty(control)
1503         controlMean = controlMean * 100;
1504         controlSEM = controlSEM * 100;
1505     end
1506 end
1507
1508 % Get the significance.
1509 sigs = NaN;
1510 if ~isempty(sig)
1511     sigs = sig.q(sigI);
1512 end
1513
1514 % Determine the inequality between experiment and control.
1515 eqStr = '';
1516 if sigs <= 0.05 && ~isempty(control)
1517     if wormMean > controlMean
1518         eqStr = '>';
1519     elseif wormMean < controlMean
1520         eqStr = '<';
1521     end
1522 end
1523
1524 % Show the worm statistics.
1525 if isnan(wormMean)
1526     dataStr = 'X';
1527 else
1528     meanStr = num2str(wormMean, '%.3G');
1529     semStr = num2str(wormSEM, '%.3G');
1530     dataStr = [meanStr semChar semStr];
1531 end
1532 str = [str dataStr];
1533
1534 % Show the control statistics.
1535 if ~isempty(control)
1536     if isnan(controlMean)
1537         dataStr = 'X';
1538     else
1539         meanStr = num2str(controlMean, '%.3G');
1540         semStr = num2str(controlSEM, '%.3G');
1541         dataStr = ['[' meanStr semChar semStr ']'];
1542     end
1543 str = [str eqStr dataStr];
1544 end
1545
1546 % Show the significance.
1547 if sigs <= 0.05
1548     str = ['\bf' str '\rm'];
1549 end
1550 end
1551
1552
1553
1554 %% Convert a p-value to a background color representing significance.
1555 function color = p2BackColor(p)
1556
1557 % The p-value is not significant.
1558 color = str2colors('w');
1559
1560 % Determine the significance of the p-value.
1561 if p <= 0.0001
1562     color = [.9, .8, 1];
1563 elseif p <= 0.001
1564     color = [1, .8, .8];
1565 elseif p <= 0.01
1566     color = [1, .9, .7];
1567 elseif p <= 0.05
1568     color = [1, 1, .7];
1569 end
1570 end