Description of worm2pathTIF
worm2pathTIF
PURPOSE
WORM2PATHTIF Save worm information to a TIF.
SYNOPSIS
function [filename pages] = worm2pathTIF(filename, worm, wormName, varargin)
DESCRIPTION
WORM2PATHTIF Save worm information to a TIF.
   [FILENAME PAGES] = WORM2PATHTIF(FILENAME, WORM, WORMNAME)
   [FILENAME PAGES] = WORM2PATHTIF(FILENAME, WORM, WORMNAME,
                                   WORMINFOFILTER, WORMFEATFILTER,
                                   WORMFEATDIR,
                                   CONTROL, CONTROLNAME,
                                   CONTROLINFOFILTER, CONTROLFEATFILTER,
                                   CONTROLFEATDIR,
                                   ISSHOW, PAGE, SAVEQUALITY, ISCLOSE,
                                   ISVERBOSE)
   Inputs:
       filename          - the TIF filename;
                           if empty, the file is named
                           "<wormName> [vs <controlName>].tif"
       worm              - the worm histograms or filename
       wormName          - the name for the worm;
                           or, a function handle of the form:
                   LABEL = WORM2LABEL(WORMINFO)
                           wormInfo = the worm information
                           label    = the worm label
                           if empty, we use WORM2STRAINLABEL
       wormInfoFilter    - the worm information filtering criteria;
                           a structure with any of the fields:
              minFPS     = the minimum video frame rate (frames/seconds)
              minTime    = the minimum video time (seconds)
              maxTime    = the maximum video time (seconds)
              minSegTime = the minimum time for segmented video (seconds)
              minRatio   = the minimum ratio for segmented video frames
              minDate    = the minimum date to use (DATENUM)
              maxDate    = the maximum date to use (DATENUM)
              years      = the years to use
              months     = the months to use (1-12)
              weeks      = the weeks to use (1-52)
              days       = the days (of the week) to use (1-7)
              hours      = the hours to use (1-24)
              trackers   = the trackers to use (1-8)
       wormFeatFilter    - the worm feature filtering criteria;
                           a structure with the fields:
               featuresI = the feature indices (see WORMDATAINFO)
               minThr    = the minimum feature value (optional)
               maxThr    = the maximum feature value (optional)
               indices   = the sub indices for the features (optional)
               subFields = the subFields for the features (optional)
       wormFeatDir       - the directory to search for worm files;
                           if empty, search in the current directory
                           the default is the current directory (empty)
       control           - the control histograms or filename;
                           if empty; no control is shown
       controlName       - the name for the control;
                           or, a function handle of the form:
                   LABEL = WORM2LABEL(WORMINFO)
                           wormInfo = the worm information
                           label    = the worm label
                           if empty, we use WORM2STRAINLABEL
       controlInfoFilter - the control indices to use;
                           or, the control filtering criteria
       controlFeatFilter - the control feature filtering criteria
       controlFeatDir    - the directory to search for control files;
                           if empty, search in the current directory
                           the default is the current directory (empty)
       isShow            - are we showing the figures onscreen?
                           Note: hiding the figures is faster.
       page              - the page number;
                           if empty, the page number is not shown
       saveQuality       - the quality (magnification) for saving the figures;
                           if empty, the figures are not saved
                           the default is none (empty)
       isClose           - shoud we close the figures after saving them?
                           when saving the figure, the default is yes (true)
                           otherwise, the default is no (false)
       isVerbose         - verbose mode displays the progress;
                           the default is yes (true)
   Output:
       filename - the TIF file containing the saved figures;
                  if empty, the figures were not saved
       pages    - the number of pages in the figure file
 See also FILTERWORMINFO, FILTERWORMHIST, WORM2HISTOGRAM, WORM2STATSINFO
CROSS-REFERENCE INFORMATION
This function calls:
saveTIF SAVETIF Save a figure to a TIF file.
str2colors STR2COLORS Convert a string of colors to RGB values.
plotWormPath PLOTWORMPATH Plot the worm path(s).
plotWormPathData PLOTWORMPATHDATA Plot the worm path data.
filterWormHist FILTERWORMHIST Filter worm features to meet specific criteria.
filterWormInfo FILTERWORMINFO Filter worm information to meet specific criteria.
worm2StrainLabel WORM2STRAINLABEL Label the worm strain.
This function is called by:
worm2TIF WORM2TIF Save worm information to a TIF.
SUBFUNCTIONS
function [xLims, yLims] = centerSkeletons(wormSkeleton, controlSkeleton)
function [wormInfo, skeleton, coils, omegas, speed foraging] =
function page = drawPaths(filename, page,
function page = drawPath(filename, page, wormName, wormInfo, skeleton,
function page = drawPathsData(filename, page, dataName, unitName,
function page = drawPathData(filename, page, dataName, unitName,
function drawPathsLegend(h, isEvents)
function drawPathLegend(h)
function drawPathsDataLegend(h, dataName, unitName, dLim, isEvents)
function drawPathDataLegend(h, dataName, unitName, dLim)
SOURCE CODE
function [filename pages] = worm2pathTIF(filename, worm, wormName, varargin)
%WORM2PATHTIF Save worm information to a TIF.
%
%   [FILENAME PAGES] = WORM2PATHTIF(FILENAME, WORM, WORMNAME)
%
%   [FILENAME PAGES] = WORM2PATHTIF(FILENAME, WORM, WORMNAME,
%                                   WORMINFOFILTER, WORMFEATFILTER,
%                                   WORMFEATDIR,
%                                   CONTROL, CONTROLNAME,
%                                   CONTROLINFOFILTER, CONTROLFEATFILTER,
%                                   CONTROLFEATDIR,
%                                   ISSHOW, PAGE, SAVEQUALITY, ISCLOSE,
%                                   ISVERBOSE)
%
%   Inputs:
%       filename          - the TIF filename;
%                           if empty, the file is named
%                           "<wormName> [vs <controlName>].tif"
%       worm              - the worm histograms or filename
%       wormName          - the name for the worm;
%                           or, a function handle of the form:
%
%                   LABEL = WORM2LABEL(WORMINFO)
%
%                           wormInfo = the worm information
%                           label    = the worm label
%
%                           if empty, we use WORM2STRAINLABEL
%
%       wormInfoFilter    - the worm information filtering criteria;
%                           a structure with any of the fields:
%
%              minFPS     = the minimum video frame rate (frames/seconds)
%              minTime    = the minimum video time (seconds)
%              maxTime    = the maximum video time (seconds)
%              minSegTime = the minimum time for segmented video (seconds)
%              minRatio   = the minimum ratio for segmented video frames
%              minDate    = the minimum date to use (DATENUM)
%              maxDate    = the maximum date to use (DATENUM)
%              years      = the years to use
%              months     = the months to use (1-12)
%              weeks      = the weeks to use (1-52)
%              days       = the days (of the week) to use (1-7)
%              hours      = the hours to use (1-24)
%              trackers   = the trackers to use (1-8)
%
%       wormFeatFilter    - the worm feature filtering criteria;
%                           a structure with the fields:
%
%               featuresI = the feature indices (see WORMDATAINFO)
%               minThr    = the minimum feature value (optional)
%               maxThr    = the maximum feature value (optional)
%               indices   = the sub indices for the features (optional)
%               subFields = the subFields for the features (optional)
%
%       wormFeatDir       - the directory to search for worm files;
%                           if empty, search in the current directory
%                           the default is the current directory (empty)
%       control           - the control histograms or filename;
%                           if empty; no control is shown
%       controlName       - the name for the control;
%                           or, a function handle of the form:
%
%                   LABEL = WORM2LABEL(WORMINFO)
%
%                           wormInfo = the worm information
%                           label    = the worm label
%
%                           if empty, we use WORM2STRAINLABEL
%
%       controlInfoFilter - the control indices to use;
%                           or, the control filtering criteria
%       controlFeatFilter - the control feature filtering criteria
%       controlFeatDir    - the directory to search for control files;
%                           if empty, search in the current directory
%                           the default is the current directory (empty)
%       isShow            - are we showing the figures onscreen?
%                           Note: hiding the figures is faster.
%       page              - the page number;
%                           if empty, the page number is not shown
%       saveQuality       - the quality (magnification) for saving the figures;
%                           if empty, the figures are not saved
%                           the default is none (empty)
%       isClose           - shoud we close the figures after saving them?
%                           when saving the figure, the default is yes (true)
%                           otherwise, the default is no (false)
%       isVerbose         - verbose mode displays the progress;
%                           the default is yes (true)
%   Output:
%       filename - the TIF file containing the saved figures;
%                  if empty, the figures were not saved
%       pages    - the number of pages in the figure file
%
% See also FILTERWORMINFO, FILTERWORMHIST, WORM2HISTOGRAM, WORM2STATSINFO
% Initialize drawing information.
maxPaths = 24;
speedI = 21:29; % the skeleton indices for speed
foragingI = 1:2; % the skeleton indices for foraging
speedLim = [-500, 500]; % the speed scale
foragingLim = [0, 90]; % the foraging amplitude magnitude scale
speedAlpha = 0.9; % the speed transparency
foragingAlpha = 0.9; % the foraging transparency
% Load the worm.
wormInfo = [];
if ischar(worm)
    load(worm, 'worm', 'wormInfo');
end
% Determine the worm name.
if isempty(wormName) && ~isempty(wormInfo)
    wormName = worm2StrainLabel(wormInfo);
elseif isa(wormName, 'function_handle')
    if ~isempty(wormInfo)
        wormName = wormName(wormInfo);
    else
        wormName = '';
    end
end
% Filter the worm information.
isWormUsed = [];
if ~isempty(varargin)
    wormInfoFilter = varargin{1};
    isWormUsed = filterWormInfo(wormInfo, wormInfoFilter);
end
% Filter the worm features.
if length(varargin) > 1
    % Filter the worm features.
    wormFeatFilter = varargin{2};
    isUsed = filterWormHist(worm, wormFeatFilter);
    % Combine the filters.
    if isempty(isWormUsed)
        isWormUsed = isUsed;
    else
        isWormUsed = isWormUsed & isUsed;
    end
end
wormInfo = wormInfo(isWormUsed);
% Sort the worms.
dates = arrayfun(@(x) datenum(x.experiment.environment.timestamp), wormInfo);
[~, dateI] = sort(dates);
wormInfo = wormInfo(dateI);
% Where should we search for the feature files?
wormFeatDir = [];
if length(varargin) > 2
    wormFeatDir = varargin{3};
end
% Do we have a control?
control = [];
controlName = [];
controlInfo = [];
if length(varargin) > 3
    % Load the control.
    control = varargin{4};
    controlInfo = [];
    if ~isempty(control) && ischar(control)
        controlData = load(control, 'worm', 'wormInfo');
        control = controlData.worm;
        controlInfo = controlData.wormInfo;
        clear controlData;
    end
    % Do we have a control?
    if ~isempty(control)
        % Determine the control name.
        if length(varargin) > 4
            controlName = varargin{5};
        end
        if isempty(controlName) && ~isempty(controlInfo)
            controlName = worm2StrainLabel(controlInfo);
        elseif isa(controlName, 'function_handle')
            if ~isempty(controlInfo)
                controlName = controlName(controlInfo);
            else
                controlName = '';
            end
        end
        % Filter the control information.
        isControlUsed = [];
        if length(varargin) > 5
            controlInfoFilter = varargin{6};
            isControlUsed = filterWormInfo(controlInfo, controlInfoFilter);
        end
        % Filter the control features.
        if length(varargin) > 6
            % Filter the worm features.
            controlFeatFilter = varargin{7};
            isUsed = filterWormHist(control, controlFeatFilter);
            % Combine the filters.
            if isempty(isControlUsed)
                isControlUsed = isUsed;
            else
                isControlUsed = isControlUsed & isUsed;
            end
        end
        controlInfo = controlInfo(isControlUsed);
        % Sort the controls.
        dates = arrayfun(@(x) datenum(x.experiment.environment.timestamp), ...
            controlInfo);
        [~, dateI] = sort(dates);
        controlInfo = controlInfo(dateI);
    end
    % Where should we search for the feature files?
    controlFeatDir = [];
    if length(varargin) > 7
        controlFeatDir = varargin{8};
    end
end
% Are we showing the figures onscreen?
% Note: hiding the figures is faster.
isShow = true;
if length(varargin) > 8
    isShow = varargin{9};
end
% Determine the page number.
pages = 0;
page = 0;
if length(varargin) > 9
    page = varargin{10};
    pages = page;
end
% Determine the quality (magnification) for saving the figures.
saveQuality = []; % don't save the figures
if length(varargin) > 10
    saveQuality = varargin{11};
end
% Are we closing the figures after saving them?
if saveQuality > 0
    isClose = true;
else
    isClose = false;
end
if length(varargin) > 11
    isClose = varargin{12};
end
if ~isShow
    isClose = true;
end
% Are we displaying the progress?
isVerbose = true;
if length(varargin) > 12
    isVerbose = varargin{13};
end
% Construct the file name.
if saveQuality > 0
    % Remove the TIF extension.
    tifExt = '.tif';
    tifName = filename;
    if length(tifName) >= length(tifExt) && ...
            strcmp(filename((end - length(tifExt) + 1):end), tifExt)
        tifName = filename(1:(end - length(tifExt)));
    end
    % Create the filename.
    if isempty(tifName)
        if isempty(controlName)
            tifName = [wormName ' path'];
        else
            tifName = [wormName ' vs ' controlName ' path'];
        end
    end
    % Add the TIF extension.
    filename = [tifName '.tif'];
% We are not saving a file.
else
    filename = [];
end
% Initialize the files and drawing information.
if length(wormInfo) > maxPaths
    wormInfo = wormInfo(round(linspace(1, length(wormInfo), maxPaths)));
end
if length(controlInfo) > maxPaths
    controlInfo = ...
        controlInfo(round(linspace(1, length(controlInfo), maxPaths)));
end
% Load the worm path information.
if isVerbose
    disp('Loading experiments ...');
end
[wormInfo, wormSkeleton, wormCoils, wormOmegas, ...
    wormSpeed, wormForaging] = loadWorms(wormFeatDir, wormInfo, isVerbose);
if isVerbose
    disp('Loading controls ...');
end
[controlInfo, controlSkeleton, controlCoils, controlOmegas, ...
    controlSpeed, controlForaging] = ...
    loadWorms(controlFeatDir, controlInfo, isVerbose);
% Translate the skeletons to a common origin.
% [xLims, yLims] = centerSkeletons(wormSkeleton, controlSkeleton);
% xLims = xLims ./ 1000;
% yLims = yLims ./ 1000;
xLims = [];
yLims = [];
% Draw the paths.
pageRows = 2;
pageCols = 3;
page = drawPaths(filename, page, ...
    wormName, wormInfo, ...
    wormSkeleton, wormCoils, wormOmegas, ...
    controlName, controlInfo, ...
    controlSkeleton, controlCoils, controlOmegas, ...
    xLims, yLims, isShow, saveQuality, isClose, isVerbose);
page = drawPath(filename, page, wormName, wormInfo, ...
    wormSkeleton, wormCoils, wormOmegas, xLims, yLims, ...
    pageRows, pageCols, isShow, saveQuality, isClose, isVerbose);
page = drawPath(filename, page, controlName, controlInfo, ...
    controlSkeleton, controlCoils, controlOmegas, xLims, yLims, ...
    pageRows, pageCols, isShow, saveQuality, isClose, isVerbose);
% Draw the speed.
dataName = 'Midbody Speed';
unitName = 'Microns/Seconds';
page = drawPathsData(filename, page, dataName, unitName, ...
    wormName, wormInfo, ...
    wormSkeleton, wormCoils, wormOmegas, ...
    controlName, controlInfo, ...
    controlSkeleton, controlCoils, controlOmegas, ...
    wormSpeed, controlSpeed, speedI, speedLim, speedAlpha, ...
    xLims, yLims, isShow, saveQuality, isClose, isVerbose);
page = drawPathData(filename, page, dataName, unitName, wormName, ...
    wormInfo, wormSkeleton, wormCoils, wormOmegas, ...
    speedI, wormSpeed, speedLim, speedAlpha, xLims, yLims, ...
    pageRows, pageCols, isShow, saveQuality, isClose, isVerbose);
page = drawPathData(filename, page, dataName, unitName, controlName, ...
    controlInfo, controlSkeleton, controlCoils, controlOmegas, ...
    speedI, controlSpeed, speedLim, speedAlpha, xLims, yLims, ...
    pageRows, pageCols, isShow, saveQuality, isClose, isVerbose);
% Draw the foraging.
dataName = 'Foraging Amplitude';
unitName = 'Degrees';
page = drawPathsData(filename, page, dataName, unitName, ...
    wormName, wormInfo, ...
    wormSkeleton, wormCoils, wormOmegas, ...
    controlName, controlInfo, ...
    controlSkeleton, controlCoils, controlOmegas, ...
    wormForaging, controlForaging, foragingI, foragingLim, foragingAlpha, ...
    xLims, yLims, isShow, saveQuality, isClose, isVerbose);
page = drawPathData(filename, page, dataName, unitName, wormName, ...
    wormInfo, wormSkeleton, wormCoils, wormOmegas, ...
    foragingI, wormForaging, foragingLim, foragingAlpha, xLims, yLims, ...
    pageRows, pageCols, isShow, saveQuality, isClose, isVerbose);
page = drawPathData(filename, page, dataName, unitName, controlName, ...
    controlInfo, controlSkeleton, controlCoils, controlOmegas, ...
    foragingI, controlForaging, foragingLim, foragingAlpha, xLims, yLims, ...
    pageRows, pageCols, isShow, saveQuality, isClose, isVerbose);
% Compute the pages.
pages = page - pages;
end
%% Translate the skeletons to a common origin.
function [xLims, yLims] = centerSkeletons(wormSkeleton, controlSkeleton)
% Translate the worm skeletons.
xMax = nan;
yMax = nan;
for i = 1:length(wormSkeleton)
    wormSkeleton{i}.x = wormSkeleton{i}.x - min(wormSkeleton{i}.x(:));
    wormSkeleton{i}.y = wormSkeleton{i}.y - min(wormSkeleton{i}.y(:));
    xMax = max(xMax, max(wormSkeleton{i}.x(:)));
    yMax = max(yMax, max(wormSkeleton{i}.y(:)));
end
% Translate the control skeletons.
for i = 1:length(controlSkeleton)
    controlSkeleton{i}.x = ...
        controlSkeleton{i}.x - min(controlSkeleton{i}.x(:));
    controlSkeleton{i}.y = ...
        controlSkeleton{i}.y - min(controlSkeleton{i}.y(:));
    xMax = max(xMax, max(controlSkeleton{i}.x(:)));
    yMax = max(yMax, max(controlSkeleton{i}.y(:)));
end
% Determine the axial limits.
xLims = [0, xMax];
yLims = [0, yMax];
end
%% Load the worm path information.
function [wormInfo, skeleton, coils, omegas, speed foraging] = ...
    loadWorms(featDir, wormInfo, isVerbose)
% Initialize the video extension.
videoExt = '.avi';
% Load the worm path information.
skeleton = cell(length(wormInfo), 1);
coils = cell(length(wormInfo), 1);
omegas = cell(length(wormInfo), 1);
speed = cell(length(wormInfo), 1);
foraging = cell(length(wormInfo), 1);
keepI = true(length(wormInfo), 1);
for i = 1:length(wormInfo)
    % Get the file name.
    file = wormInfo(i).files.video;
    sepI = strfind(file, '\');
    % Remove the directory
    if ~isempty(sepI)
        file = file((sepI(end) + 1):end);
    end
    % Fix the extension.
    if strcmp(file((end - length(videoExt) + 1):end), videoExt)
        file = file(1:(end - length(videoExt)));
    end
    file = [file '_features.mat'];
    % Display the progress.
    if isVerbose
        disp(['Loading ' num2str(i) '/' ...
            num2str(length(wormInfo)) ' "' file '" ...']);
    end
    % Find the file.
    if ~exist([featDir filesep file], 'file')
        files = rdir([featDir filesep '**' filesep file]);
        if length(files) ~= 1
            file = strrep(file, '\', '\\');
            warning('worm2pathTIF:NoFile', ['"' featDir ...
                '" does not contain a subdirectory with the file "' ...
                file '". The worm will not be used.']);
            keepI(i) = false;
            continue;
        end
        file = files.name;
    end
    % Load the file.
    worm = [];
    load(file, 'worm');
    % Get the worm features.
    if isempty(worm)
        warning('worm2pathTIF:NoWorm', ...
            ['"' file '" does not contain a "worm" and will not be used.']);
        keepI(i) = false;
        continue;
    end
    % Add the worm information.
    skeleton{i} = worm.posture.skeleton;
    coils{i} = worm.posture.coils;
    omegas{i} = worm.locomotion.turns.omegas;
    speed{i} = worm.locomotion.velocity.midbody.speed;
    foraging{i} = abs(worm.locomotion.bends.foraging.amplitude);
end
% Remove the missing worms.
wormInfo = wormInfo(keepI);
skeleton = skeleton(keepI);
coils = coils(keepI);
omegas = omegas(keepI);
speed = speed(keepI);
foraging = foraging(keepI);
end
%% Draw the worm multi-paths.
function page = drawPaths(filename, page, ...
    wormName, wormInfo, wormSkeleton, wormCoils, wormOmegas, ...
    controlName, controlInfo, controlSkeleton, controlCoils, controlOmegas, ...
    xLims, yLims, isShow, saveQuality, isClose, isVerbose)
% Do we have multiple worms?
if isempty(wormInfo) || (length(wormInfo) < 2 && length(controlInfo) < 2)
    return;
end
% Initialize special ascii symbols.
sepStr = '   ¤   ';
sepStr2 = '   \rightarrow   ';
% Initialize the path information.
centerMode = 1;
rotateMode = 2;
sortMode = -1;
% Determine the shape.
numWorms = max(length(wormInfo), length(controlInfo));
rows = ceil(sqrt(numWorms));
cols = ceil(numWorms / rows);
shapeMode = [rows, cols];
% Construct the titles.
wormTitleStr = ['\it' wormName ' \rm' sepStr2 ...
    '\bf' num2str(length(wormInfo)) ' Worms'];
wormPageStr = ['\it' wormName];
if ~isempty(controlInfo)
    controlTitleStr = ['\it' controlName ' \rm' sepStr2 ...
        '\bf' num2str(length(controlInfo)) ' Worms'];
    wormPageStr = [wormPageStr ' vs. ' controlName];
end
wormPageStr = [wormPageStr ' \rm'];
%% Draw the worm path overlay.
% Display the progress.
if isVerbose
    if isempty(controlName)
        disp(['Printing path overlay for "' wormName '" page 1/2 ...']);
    else
        disp(['Printing path overlay for "' wormName '" vs. "' ...
            controlName '" page 1/2 ...']);
    end
end
% Open a new figure.
page = page + 1;
h = figure;
visStr = 'off';
if isShow
    visStr = 'on';
end
set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
    'PaperType', 'A2', 'Visible', visStr);
% Show the legend.
drawPathsLegend(h, true);
% Draw the worm path overlay.
if isempty(controlInfo)
    plotWormPath(wormTitleStr, wormSkeleton, ...
        wormCoils, wormOmegas, xLims, yLims, ...
        centerMode, rotateMode, 0, 0, true, subplot(1, 1, 1, 'Parent', h));
% Draw the worm vs. control path overlay.
else
    % Draw the worm and control.
    wormAxes = plotWormPath(wormTitleStr, wormSkeleton, ...
        wormCoils, wormOmegas, xLims, yLims, ...
        centerMode, rotateMode, 0, 0, true, subplot(1, 2, 1, 'Parent', h));
    controlAxes = plotWormPath(controlTitleStr, controlSkeleton, ...
        controlCoils, controlOmegas, xLims, yLims, ...
        centerMode, rotateMode, 0, 0, true, subplot(1, 2, 2, 'Parent', h));
    % Use a common scale.
    wormXLim = get(wormAxes, 'XLim');
    wormYLim = get(wormAxes, 'YLim');
    controlXLim = get(controlAxes, 'XLim');
    controlYLim = get(controlAxes, 'YLim');
    limX = [min(wormXLim(1), controlXLim(1)), ...
        max(wormXLim(2), controlXLim(2))];
    limY = [min(wormYLim(1), controlYLim(1)), ...
        max(wormYLim(2), controlYLim(2))];
    set(wormAxes, 'XLim', limX);
    set(wormAxes, 'YLim', limY);
    set(controlAxes, 'XLim', limX);
    set(controlAxes, 'YLim', limY);
end
% Save the figure.
if saveQuality > 0
    pageTitle = [wormPageStr sepStr '\bfPath Overlay'];
    saveTIF(h, filename, saveQuality, true, pageTitle, ...
        page, isClose);
% Close the figure.
elseif ~isShow || isClose
    close(h);
end
%% Draw multiple paths spaced out on a single figure.
% Display the progress.
if isVerbose
    if isempty(controlName)
        disp(['Printing path overview for "' wormName '" page 2/2 ...']);
    else
        disp(['Printing path overview for "' wormName '" vs. "' ...
            controlName '" page 2/2 ...']);
    end
end
% Open a new figure.
page = page + 1;
h = figure;
visStr = 'off';
if isShow
    visStr = 'on';
end
set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
    'PaperType', 'A2', 'Visible', visStr);
% Show the legend.
drawPathsLegend(h, false);
% Draw the worm path overlay.
if isempty(controlInfo)
    plotWormPath(wormTitleStr, wormSkeleton, ...
        wormCoils, wormOmegas, xLims, yLims, ...
        centerMode, rotateMode, shapeMode, sortMode, true, ...
        subplot(1, 1, 1, 'Parent', h));
% Draw the worm vs. control path overlay.
else
    % Draw the worm and control.
    wormAxes = plotWormPath(wormTitleStr, wormSkeleton, ...
        wormCoils, wormOmegas, xLims, yLims, ...
        centerMode, rotateMode, shapeMode, sortMode, true, ...
        subplot(1, 2, 1, 'Parent', h));
    controlAxes = plotWormPath(controlTitleStr, controlSkeleton, ...
        controlCoils, controlOmegas, xLims, yLims, ...
        centerMode, rotateMode, shapeMode, sortMode, true, ...
        subplot(1, 2, 2, 'Parent', h));
    % Use a common scale.
%     wormXLim = get(wormAxes, 'XLim');
%     wormYLim = get(wormAxes, 'YLim');
%     controlXLim = get(controlAxes, 'XLim');
%     controlYLim = get(controlAxes, 'YLim');
%     limX = [min(wormXLim(1), controlXLim(1)), ...
%         max(wormXLim(2), controlXLim(2))];
%     limY = [min(wormYLim(1), controlYLim(1)), ...
%         max(wormYLim(2), controlYLim(2))];
%     set(wormAxes, 'XLim', limX);
%     set(wormAxes, 'YLim', limY);
%     set(controlAxes, 'XLim', limX);
%     set(controlAxes, 'YLim', limY);
end
% Save the figure.
if saveQuality > 0
    pageTitle = [wormPageStr sepStr '\bfPath Overview'];
    saveTIF(h, filename, saveQuality, true, pageTitle, ...
        page, isClose);
% Close the figure.
elseif ~isShow || isClose
    close(h);
end
end
%% Draw the worms path.
function page = drawPath(filename, page, wormName, wormInfo, skeleton, ...
    coils, omegas, xLims, yLims, rows, cols, ...
    isShow, saveQuality, isClose, isVerbose)
% Do we have any worms?
if isempty(wormInfo)
    return;
end
% Initialize special ascii symbols.
sepStr = '   ¤   ';
sepStr2 = '   \rightarrow   ';
% Initialize the path information.
centerMode = 1;
rotateMode = 0;
% Draw the paths.
pathsPerPage = rows * cols;
h = [];
for i = 1:length(wormInfo)
    % Find the path page index.
    pathI = mod(i - 1, pathsPerPage) + 1;
    % Are we creating a new figure?
    if pathI == 1
        % Save and/or close the previous figure.
        if i > 1
            % Save the figure.
            if saveQuality > 0
                pageTitle = ['\it' wormName ' \rm' sepStr '\bfPath'];
                saveTIF(h, filename, saveQuality, true, pageTitle, ...
                    page, isClose);
            % Close the figure.
            elseif ~isShow || isClose
                close(h);
            end
        end
        % Open a new figure.
        page = page + 1;
        h = figure;
        visStr = 'off';
        if isShow
            visStr = 'on';
        end
        set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
            'PaperType', 'A2', 'Visible', visStr);
        hold on;
        % Show the legend.
        drawPathLegend(h);
        % Display the progress.
        if isVerbose
            disp(['Printing path for "' wormName '" page ' ...
                num2str(ceil(i / pathsPerPage)) '/' ...
                num2str(ceil(length(wormInfo) / pathsPerPage)) ' ...']);
        end
    end
    % Draw the path.
    timestamp = wormInfo(i).experiment.environment.timestamp;
    dateStr = datestr(datenum(timestamp), 31);
    titleName = ['\it' wormName ' \rm' sepStr2 '\bf' dateStr];
    plotWormPath(titleName, skeleton{i}, coils{i}, omegas{i}, ...
        xLims, yLims, centerMode, rotateMode, 0, 0, false, ...
        subplot(rows, cols, pathI, 'Parent', h));
end
% Save the last figure.
if saveQuality > 0
    pageTitle = ['\it' wormName ' \rm' sepStr '\bfPath'];
    saveTIF(h, filename, saveQuality, true, pageTitle, ...
        page, isClose);
% Close the figure.
elseif ~isShow || isClose
    close(h);
end
end
%% Draw the worm multi-paths data.
function page = drawPathsData(filename, page, dataName, unitName, ...
    wormName, wormInfo, wormSkeleton, wormCoils, wormOmegas, ...
    controlName, controlInfo, controlSkeleton, controlCoils, controlOmegas, ...
    wormData, controlData, bodyI, dLim, alpha, xLims, yLims, ...
    isShow, saveQuality, isClose, isVerbose)
% Do we have multiple worms?
if isempty(wormInfo) || (length(wormInfo) < 2 && length(controlInfo) < 2)
    return;
end
% Initialize special ascii symbols.
sepStr = '   ¤   ';
sepStr2 = '   \rightarrow   ';
% Initialize the path information.
centerMode = 1;
rotateMode = 2;
sortMode = -1;
% Determine the shape.
numWorms = max(length(wormInfo), length(controlInfo));
rows = ceil(sqrt(numWorms));
cols = ceil(numWorms / rows);
shapeMode = [rows, cols];
% Construct the titles.
wormTitleStr = ['\it' wormName ' \rm' sepStr2 ...
    '\bf' num2str(length(wormInfo)) ' Worms'];
wormPageStr = ['\it' wormName];
if ~isempty(controlInfo)
    controlTitleStr = ['\it' controlName ' \rm' sepStr2 ...
        '\bf' num2str(length(controlInfo)) ' Worms'];
    wormPageStr = [wormPageStr ' vs. ' controlName];
end
wormPageStr = [wormPageStr ' \rm'];
%% Draw the worm path data overlay.
% Display the progress.
if isVerbose
    if isempty(controlName)
        disp(['Printing ' dataName ' overlay for "' wormName ...
            '" page 1/2 ...']);
    else
        disp(['Printing ' dataName ' overlay for "' wormName '" vs. "' ...
            controlName '" page 1/2 ...']);
    end
end
% Open a new figure.
page = page + 1;
h = figure;
visStr = 'off';
if isShow
    visStr = 'on';
end
set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
    'PaperType', 'A2', 'Visible', visStr);
% Show the legend.
drawPathsDataLegend(h, dataName, unitName, dLim, true);
% Draw the worm path overlay.
if isempty(controlInfo)
    plotWormPathData(wormTitleStr, wormSkeleton, ...
        wormCoils, wormOmegas, bodyI, wormData, dLim, alpha, ...
        xLims, yLims, centerMode, rotateMode, 0, 0, true, ...
        subplot(1, 1, 1, 'Parent', h));
% Draw the worm vs. control path overlay.
else
    % Draw the worm and control.
    wormAxes = plotWormPathData(wormTitleStr, wormSkeleton, ...
        wormCoils, wormOmegas, bodyI, wormData, dLim, alpha, ...
        xLims, yLims, centerMode, rotateMode, 0, 0, true, ...
        subplot(1, 2, 1, 'Parent', h));
    controlAxes = plotWormPathData(controlTitleStr, controlSkeleton, ...
        controlCoils, controlOmegas, bodyI, controlData, dLim, alpha, ...
        xLims, yLims, centerMode, rotateMode, 0, 0, true, ...
        subplot(1, 2, 2, 'Parent', h));
    % Use a common scale.
    wormXLim = get(wormAxes, 'XLim');
    wormYLim = get(wormAxes, 'YLim');
    controlXLim = get(controlAxes, 'XLim');
    controlYLim = get(controlAxes, 'YLim');
    limX = [min(wormXLim(1), controlXLim(1)), ...
        max(wormXLim(2), controlXLim(2))];
    limY = [min(wormYLim(1), controlYLim(1)), ...
        max(wormYLim(2), controlYLim(2))];
    set(wormAxes, 'XLim', limX);
    set(wormAxes, 'YLim', limY);
    set(controlAxes, 'XLim', limX);
    set(controlAxes, 'YLim', limY);
end
% Save the figure.
if saveQuality > 0
    pageTitle = [wormPageStr sepStr '\bf' dataName ' Overlay'];
    saveTIF(h, filename, saveQuality, true, pageTitle, ...
        page, isClose);
% Close the figure.
elseif ~isShow || isClose
    close(h);
end
%% Draw multiple path data spaced out on a single figure.
% Display the progress.
if isVerbose
    if isempty(controlName)
        disp(['Printing ' dataName ' overview for "' wormName ...
            '" page 2/2 ...']);
    else
        disp(['Printing ' dataName ' overview for "' wormName '" vs. "' ...
            controlName '" page 2/2 ...']);
    end
end
% Open a new figure.
page = page + 1;
h = figure;
visStr = 'off';
if isShow
    visStr = 'on';
end
set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
    'PaperType', 'A2', 'Visible', visStr);
% Show the legend.
drawPathsDataLegend(h, dataName, unitName, dLim, false);
% Draw the worm path overlay.
if isempty(controlInfo)
    plotWormPathData(wormTitleStr, wormSkeleton, ...
        wormCoils, wormOmegas, bodyI, wormData, dLim, alpha, ...
        xLims, yLims, centerMode, rotateMode, shapeMode, sortMode, ...
        true, subplot(1, 1, 1, 'Parent', h));
% Draw the worm vs. control path overlay.
else
    % Draw the worm and control.
    wormAxes = plotWormPathData(wormTitleStr, wormSkeleton, ...
        wormCoils, wormOmegas, bodyI, wormData, dLim, alpha, ...
        xLims, yLims, centerMode, rotateMode, shapeMode, sortMode, ...
        true, subplot(1, 2, 1, 'Parent', h));
    controlAxes = plotWormPathData(controlTitleStr, controlSkeleton, ...
        controlCoils, controlOmegas, bodyI, controlData, dLim, alpha, ...
        xLims, yLims, centerMode, rotateMode, shapeMode, sortMode, ...
        true, subplot(1, 2, 2, 'Parent', h));
    % Use a common scale.
%     wormXLim = get(wormAxes, 'XLim');
%     wormYLim = get(wormAxes, 'YLim');
%     controlXLim = get(controlAxes, 'XLim');
%     controlYLim = get(controlAxes, 'YLim');
%     limX = [min(wormXLim(1), controlXLim(1)), ...
%         max(wormXLim(2), controlXLim(2))];
%     limY = [min(wormYLim(1), controlYLim(1)), ...
%         max(wormYLim(2), controlYLim(2))];
%     set(wormAxes, 'XLim', limX);
%     set(wormAxes, 'YLim', limY);
%     set(controlAxes, 'XLim', limX);
%     set(controlAxes, 'YLim', limY);
end
% Save the figure.
if saveQuality > 0
    pageTitle = [wormPageStr sepStr '\bf' dataName ' Overview'];
    saveTIF(h, filename, saveQuality, true, pageTitle, ...
        page, isClose);
% Close the figure.
elseif ~isShow || isClose
    close(h);
end
end
%% Draw the worms path data.
function page = drawPathData(filename, page, dataName, unitName, ...
    wormName, wormInfo, skeleton, coils, omegas, ...
    bodyI, data, dLim, alpha, xLims, yLims, rows, cols, ...
    isShow, saveQuality, isClose, isVerbose)
% Do we have any worms?
if isempty(wormInfo)
    return;
end
% Initialize special ascii symbols.
sepStr = '  ¤   ';
sepStr2 = '   \rightarrow   ';
% Initialize the path information.
centerMode = 1;
rotateMode = 0;
% Draw the paths.
pathsPerPage = rows * cols;
h = [];
for i = 1:length(wormInfo)
    % Find the path page index.
    pathI = mod(i - 1, pathsPerPage) + 1;
    % Are we creating a new figure?
    if pathI == 1
        % Save and/or close the previous figure.
        if i > 1
            % Save the figure.
            if saveQuality > 0
                pageTitle = ['\it' wormName ' \rm' sepStr '\bf' dataName];
                saveTIF(h, filename, saveQuality, true, pageTitle, ...
                    page, isClose);
            % Close the figure.
            elseif ~isShow || isClose
                close(h);
            end
        end
1000         % Open a new figure.
1001         page = page + 1;
1002         h = figure;
1003         visStr = 'off';
1004         if isShow
1005             visStr = 'on';
1006         end
1007         set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
1008             'PaperType', 'A2', 'Visible', visStr);
1009         hold on;
1010
1011         % Show the legend.
1012         drawPathDataLegend(h, dataName, unitName, dLim);
1013
1014         % Display the progress.
1015         if isVerbose
1016             disp(['Printing "' dataName '" for "' wormName '" page ' ...
1017                 num2str(ceil(i / pathsPerPage)) '/' ...
1018                 num2str(ceil(length(wormInfo) / pathsPerPage)) ' ...']);
1019         end
1020     end
1021
1022     % Draw the path.
1023     timestamp = wormInfo(i).experiment.environment.timestamp;
1024     dateStr = datestr(datenum(timestamp), 31);
1025     titleName = ['\it' wormName ' \rm' sepStr2 '\bf' dateStr];
1026     plotWormPathData(titleName, skeleton{i}, coils{i}, omegas{i}, ...
1027         bodyI, data{i}, dLim, alpha, xLims, yLims, ...
1028         centerMode, rotateMode, 0, 0, false, ...
1029         subplot(rows, cols, pathI, 'Parent', h));
1030 end
1031
1032 % Save the last figure.
1033 if saveQuality > 0
1034     pageTitle = ['\it' wormName ' \rm' sepStr '\bf' dataName];
1035     saveTIF(h, filename, saveQuality, true, pageTitle, ...
1036         page, isClose);
1037
1038 % Close the figure.
1039 elseif ~isShow || isClose
1040     close(h);
1041 end
1042 end
1043
1044
1045
1046 %% Show the multi-path legend.
1047 function drawPathsLegend(h, isEvents)
1048
1049 % Initialize the drawing information.
1050 fontSize = 24;
1051 black = str2colors('k');
1052 white = str2colors('w');
1053 headColor = str2colors('m');
1054 midbodyColor = str2colors('g');
1055 tailColor = str2colors('b', 1/3);
1056 firstColor = str2colors('k', 0.5);
1057 lastColor = str2colors('k')';
1058 coilColor = str2colors('n');
1059 omegaColor = str2colors('n');
1060
1061 % Setup the label information.
1062 label = {
1063     ' \bfMIDBODY '
1064     ' \bfHEAD '
1065     ' \bfTAIL '
1066     ' \bfSTART '
1067     ' \bfEND '
1068     ' \bfOMEGA = x '
1069     ' \bfCOIL = + '};
1070 backColor = {
1071     midbodyColor
1072     headColor
1073     tailColor
1074     firstColor
1075     lastColor
1076     omegaColor
1077     coilColor};
1078 foreColor = {
1079     black
1080     black
1081     black
1082     white
1083     white
1084     white
1085     white};
1086
1087 % Setup the margin.
1088 xOff = 10^-3;
1089 xPosOff = 1 - xOff;
1090 textPosition = [xPosOff, 0, xOff, 1];
1091 textAxis = axes('units', 'normalized', 'Position', textPosition, ...
1092     'XTick', [], 'YTick', [], 'Parent', h);
1093
1094 % Are we showing events?
1095 yStart = 0.99;
1096 yStart2 = 0.155;
1097 yStart3 = 0.072;
1098 yOff = 0.033;
1099 if ~isEvents
1100     label = label(1:(end - 2));
1101     backColor = backColor(1:(end - 2));
1102     foreColor = foreColor(1:(end - 2));
1103     yStart2 = yStart3;
1104 end
1105
1106 % Draw the labels.
1107 for i = 1:length(label)
1108
1109     % Draw the label.
1110     text(xOff, yStart - (i - 1) * yOff, label{i}, ...
1111         'FontSize', fontSize, ...
1112         'HorizontalAlignment', 'right', ...
1113         'VerticalAlignment', 'top', ...
1114         'BackgroundColor', backColor{i}, ...
1115         'Color', foreColor{i}, ...
1116         'EdgeColor', 'k', ...
1117         'Parent', textAxis);
1118
1119     % Put in a space.
1120     if i == 3
1121         yStart = yStart2 + i * yOff;
1122     elseif i == 5
1123         yStart = yStart3 + i * yOff;
1124     end
1125 end
1126 end
1127
1128
1129
1130 %% Show the path legend.
1131 function drawPathLegend(h)
1132
1133 % Initialize the drawing information.
1134 fontSize = 32;
1135 black = str2colors('k');
1136 white = str2colors('w');
1137 headColor = str2colors('m');
1138 midbodyColor = str2colors('g');
1139 tailColor = str2colors('b', 1/3);
1140 firstColor = str2colors('k', 0.5);
1141 lastColor = str2colors('k')';
1142 coilColor = str2colors('n');
1143 omegaColor = str2colors('n');
1144
1145 % Setup the label information.
1146 label = {
1147     ' \bfMIDBODY '
1148     ' \bfHEAD '
1149     ' \bfTAIL '
1150     ' \bfOMEGA = x '
1151     ' \bfCOIL = + '
1152     ' \bfSTART '
1153     ' \bfEND '};
1154 backColor = {
1155     midbodyColor
1156     headColor
1157     tailColor
1158     omegaColor
1159     coilColor
1160     firstColor
1161     lastColor};
1162 foreColor = {
1163     black
1164     black
1165     black
1166     white
1167     white
1168     white
1169     white};
1170
1171 % Setup the margin.
1172 xOff = 10^-3;
1173 xPosOff = 1 - xOff;
1174 textPosition = [xPosOff, 0, xOff, 1];
1175 textAxis = axes('units', 'normalized', 'Position', textPosition, ...
1176     'XTick', [], 'YTick', [], 'Parent', h);
1177
1178 % Draw the labels.
1179 yStart = 0.99;
1180 yStart2 = 0.5;
1181 yStart3 = 0.36;
1182 yOff = 0.05;
1183 for i = 1:length(label)
1184
1185     % Draw the label.
1186     text(xOff, yStart - (i - 1) * yOff, label{i}, ...
1187         'FontSize', fontSize, ...
1188         'HorizontalAlignment', 'right', ...
1189         'VerticalAlignment', 'top', ...
1190         'BackgroundColor', backColor{i}, ...
1191         'Color', foreColor{i}, ...
1192         'EdgeColor', 'k', ...
1193         'Parent', textAxis);
1194
1195     % Put in a space.
1196     if i == 3
1197         yStart = yStart2 + i * yOff;
1198     elseif i == 5
1199         yStart = yStart3 + i * yOff;
1200     end
1201 end
1202 end
1203
1204
1205
1206 %% Show the multi-path data legend.
1207 function drawPathsDataLegend(h, dataName, unitName, dLim, isEvents)
1208
1209 % Initialize the drawing information.
1210 nameFontSize = 20;
1211 dataFontSize = 14;
1212 legendFontSize = 24;
1213 black = str2colors('k');
1214 white = str2colors('w');
1215 firstColor = str2colors('k', 0.5);
1216 lastColor = str2colors('k')';
1217 coilColor = str2colors('n');
1218 omegaColor = str2colors('n');
1219
1220 % Setup the label information.
1221 label = {
1222     ' \bfSTART '
1223     ' \bfEND '
1224     ' \bfOMEGA = x '
1225     ' \bfCOIL = + '};
1226 backColor = {
1227     firstColor
1228     lastColor
1229     omegaColor
1230     coilColor};
1231 foreColor = {
1232     white
1233     white
1234     white
1235     white};
1236
1237 % Setup the margin.
1238 xOff = 10^-3;
1239 xPosOff = 1 - xOff;
1240 textPosition = [xPosOff, 0, xOff, 1];
1241 textAxis = axes('units', 'normalized', 'Position', textPosition, ...
1242     'XTick', [], 'YTick', [], 'Parent', h);
1243
1244 % Draw the colorbar label.
1245 yStart = .995;
1246 nameStr = [' \bf' dataName '\rm  (\it' unitName '\rm) '];
1247 text(xPosOff, yStart, nameStr, ...
1248     'FontSize', nameFontSize, ...
1249     'HorizontalAlignment', 'right', ...
1250     'VerticalAlignment', 'top', ...
1251     'BackgroundColor', white, ...
1252     'Color', black, ...
1253     'EdgeColor', 'k', ...
1254     'Parent', textAxis);
1255
1256 % Draw the colorbar.
1257 yStart = 0.55;
1258 barWidth = .02;
1259 barHeight = 0.4;
1260 barPosition = [xPosOff - barWidth, yStart, barWidth, barHeight];
1261 colormap(textAxis, jet);
1262 set(textAxis, 'CLim', dLim);
1263 colorbar('peer', textAxis, 'Position', barPosition, ...
1264     'YAxisLocation', 'left', 'FontSize', dataFontSize);
1265
1266 % Are we showing events?
1267 yStart = 0.155;
1268 yStart2 = 0.072;
1269 yOff = 0.033;
1270 if ~isEvents
1271     label = label(1:(end - 2));
1272     backColor = backColor(1:(end - 2));
1273     foreColor = foreColor(1:(end - 2));
1274     yStart = yStart2;
1275 end
1276
1277 % Draw the labels.
1278 for i = 1:length(label)
1279
1280     % Draw the label.
1281     text(xOff, yStart - (i - 1) * yOff, label{i}, ...
1282         'FontSize', legendFontSize, ...
1283         'HorizontalAlignment', 'right', ...
1284         'VerticalAlignment', 'top', ...
1285         'BackgroundColor', backColor{i}, ...
1286         'Color', foreColor{i}, ...
1287         'EdgeColor', 'k', ...
1288         'Parent', textAxis);
1289
1290     % Put in a space.
1291     if i == 2
1292         yStart = yStart2 + i * yOff;
1293     end
1294 end
1295 end
1296
1297
1298
1299 %% Show the path data legend.
1300 function drawPathDataLegend(h, dataName, unitName, dLim)
1301
1302 % Initialize the drawing information.
1303 nameFontSize = 20;
1304 dataFontSize = 16;
1305 legendFontSize = 32;
1306 black = str2colors('k');
1307 white = str2colors('w');
1308 firstColor = str2colors('k', 0.5);
1309 lastColor = str2colors('k')';
1310 coilColor = str2colors('n');
1311 omegaColor = str2colors('n');
1312
1313 % Setup the label information.
1314 label = {
1315     ' \bfOMEGA = x '
1316     ' \bfCOIL = + '
1317     ' \bfSTART '
1318     ' \bfEND '};
1319 backColor = {
1320     omegaColor
1321     coilColor
1322     firstColor
1323     lastColor};
1324 foreColor = {
1325     white
1326     white
1327     white
1328     white};
1329
1330 % Setup the margin.
1331 xOff = 10^-3;
1332 xPosOff = 1 - xOff;
1333 textPosition = [xPosOff, 0, xOff, 1];
1334 textAxis = axes('units', 'normalized', 'Position', textPosition, ...
1335     'XTick', [], 'YTick', [], 'Parent', h);
1336
1337 % Draw the colorbar label.
1338 yStart = .995;
1339 nameStr = [' \bf' dataName '\rm  (\it' unitName '\rm) '];
1340 text(xPosOff, yStart, nameStr, ...
1341     'FontSize', nameFontSize, ...
1342     'HorizontalAlignment', 'right', ...
1343     'VerticalAlignment', 'top', ...
1344     'BackgroundColor', white, ...
1345     'Color', black, ...
1346     'EdgeColor', 'k', ...
1347     'Parent', textAxis);
1348
1349 % Draw the colorbar.
1350 yStart = 0.55;
1351 barWidth = .05;
1352 barHeight = 0.4;
1353 barPosition = [xPosOff - barWidth, yStart, barWidth, barHeight];
1354 colormap(textAxis, jet);
1355 set(textAxis, 'CLim', dLim);
1356 colorbar('peer', textAxis, 'Position', barPosition, ...
1357     'YAxisLocation', 'left', 'FontSize', dataFontSize);
1358
1359 % Draw the labels.
1360 yStart = 0.5;
1361 yBreakOff = 0.04;
1362 yOff = 0.05;
1363 for i = 1:length(label)
1364
1365     % Draw the label.
1366     text(xOff, yStart - (i - 1) * yOff, label{i}, ...
1367         'FontSize', legendFontSize, ...
1368         'HorizontalAlignment', 'right', ...
1369         'VerticalAlignment', 'top', ...
1370         'BackgroundColor', backColor{i}, ...
1371         'Color', foreColor{i}, ...
1372         'EdgeColor', 'k', ...
1373         'Parent', textAxis);
1374
1375     % Put in a space.
1376     if i == 2
1377         yStart = yStart - yBreakOff;
1378     end
1379 end
1380 end