Description of worm2detailsTIF
worm2detailsTIF
PURPOSE
WORM2DETAILSTIF Save worm details to a TIF.
SYNOPSIS
function [filename pages] = worm2detailsTIF(filename, worm, wormName,varargin)
DESCRIPTION
WORM2DETAILSTIF Save worm details to a TIF.
   [FILENAME PAGES] = WORM2DETAILSTIF(FILENAME, WORM, WORMNAME)
   [FILENAME PAGES] = WORM2DETAILSTIF(FILENAME, WORM, WORMNAME,
                                      WORMINFOFILTER, WORMFEATFILTER,
                                      CONTROL, CONTROLNAME,
                                      CONTROLINFOFILTER, CONTROLFEATFILTER,
                                      SIGNIFICANCE, ISSHOW, PAGE,
                                      SAVEQUALITY, ISCLOSE, ISVERBOSE)
   Inputs:
       filename          - the TIF filename;
                           if empty, the file is named
                           "<wormName> [vs <controlName>].tif"
       worm              - the worm histograms or filename
       wormName          - the name for the worm;
                           or, a function handle of the form:
                   LABEL = WORM2LABEL(WORMINFO)
                           wormInfo = the worm information
                           label    = the worm label
                           if empty, we use WORM2STRAINLABEL
       wormInfoFilter    - the worm information filtering criteria;
                           a structure with any of the fields:
              minFPS     = the minimum video frame rate (frames/seconds)
              minTime    = the minimum video time (seconds)
              maxTime    = the maximum video time (seconds)
              minSegTime = the minimum time for segmented video (seconds)
              minRatio   = the minimum ratio for segmented video frames
              minDate    = the minimum date to use (DATENUM)
              maxDate    = the maximum date to use (DATENUM)
              years      = the years to use
              months     = the months to use (1-12)
              weeks      = the weeks to use (1-52)
              days       = the days (of the week) to use (1-7)
              hours      = the hours to use (1-24)
              trackers   = the trackers to use (1-8)
       wormFeatFilter    - the worm feature filtering criteria;
                           a structure with the fields:
               featuresI = the feature indices (see WORMDATAINFO)
               minThr    = the minimum feature value (optional)
               maxThr    = the maximum feature value (optional)
               indices   = the sub indices for the features (optional)
               subFields = the subFields for the features (optional)
       control           - the control histograms or filename;
                           if empty; no control is shown
       controlName       - the name for the control;
                           or, a function handle of the form:
                   LABEL = WORM2LABEL(WORMINFO)
                           wormInfo = the worm information
                           label    = the worm label
                           if empty, we use WORM2STRAINLABEL
       controlInfoFilter - the control indices to use;
                           or, the control filtering criteria
       controlFeatFilter - the control feature filtering criteria
       significance      - the feature statistical significance or filename;
                           if empty; no statistical significance is shown
                           if a struct, the fields are:
                           p = the p-value, per feature
                           q = the q-value, per feature
       isShow            - are we showing the figures onscreen?
                           Note: hiding the figures is faster.
       page              - the page number;
                           if empty, the page number is not shown
       saveQuality       - the quality (magnification) for saving the figures;
                           if empty, the figures are not saved
                           the default is none (empty)
       isClose           - shoud we close the figures after saving them?
                           when saving the figure, the default is yes (true)
                           otherwise, the default is no (false)
       isVerbose         - verbose mode displays the progress;
                           the default is yes (true)
   Output:
       filename - the TIF file containing the saved figures;
                  if empty, the figures were not saved
       pages    - the number of pages in the figure file
 See also FILTERWORMINFO, FILTERWORMHIST, WORM2HISTOGRAM, WORM2STATSINFO
CROSS-REFERENCE INFORMATION
This function calls:
downSampleHistogram DOWNSAMPLEHISTOGRAM Downsample a histogram(s).
filterHistogram FILTERHISTOGRAM Filter a histogram to remove data.
getStructField GETSTRUCTFIELD Get a field in a structure.
plotHistogram PLOTHISTOGRAM Plot a histogram(s) of data.
saveTIF SAVETIF Save a figure to a TIF file.
str2colors STR2COLORS Convert a string of colors to RGB values.
wormDataInfo WORMDATAINFO Get information for computing the worm data.
wormDisplayInfo WORMDISPLAYINFO Get information for displaying the worm data.
p2stars P2STARS Convert a p-value to a string of stars representing significance.
filterWormHist FILTERWORMHIST Filter worm features to meet specific criteria.
filterWormInfo FILTERWORMINFO Filter worm information to meet specific criteria.
worm2GenotypeLabel WORM2GENOTYPELABEL Label the worm genotype.
worm2StrainLabel WORM2STRAINLABEL Label the worm strain.
wormStatsInfo WORMFEATUREINFO Get information for computing the worm statistics.
This function is called by:
worm2TIF WORM2TIF Save worm information to a TIF.
SUBFUNCTIONS
function drawSimpleData(filename, page, featureI, worm, wormName,
function drawMotionData(filename, page, featureI, index, worm, wormName,
function drawEventData(filename, page, featureI, worm, wormName,
function drawSimpleLegend(h)
function drawMotionLegend(h)
function drawEventLegend(h)
function color = p2ForeColor(p)
function color = p2BackColor(p)
function [str sigs] = stats2strs(worm, control, sig, sigI)
function [str sigs] = eventStats2strs(worms, isWormUsed,
function str = info2pageTitle(wormName, controlName, featureI,
SOURCE CODE
function [filename pages] = worm2detailsTIF(filename, worm, wormName, ...
    varargin)
%WORM2DETAILSTIF Save worm details to a TIF.
%
%   [FILENAME PAGES] = WORM2DETAILSTIF(FILENAME, WORM, WORMNAME)
%
%   [FILENAME PAGES] = WORM2DETAILSTIF(FILENAME, WORM, WORMNAME,
%                                      WORMINFOFILTER, WORMFEATFILTER,
%                                      CONTROL, CONTROLNAME,
%                                      CONTROLINFOFILTER, CONTROLFEATFILTER,
%                                      SIGNIFICANCE, ISSHOW, PAGE,
%                                      SAVEQUALITY, ISCLOSE, ISVERBOSE)
%
%   Inputs:
%       filename          - the TIF filename;
%                           if empty, the file is named
%                           "<wormName> [vs <controlName>].tif"
%       worm              - the worm histograms or filename
%       wormName          - the name for the worm;
%                           or, a function handle of the form:
%
%                   LABEL = WORM2LABEL(WORMINFO)
%
%                           wormInfo = the worm information
%                           label    = the worm label
%
%                           if empty, we use WORM2STRAINLABEL
%
%       wormInfoFilter    - the worm information filtering criteria;
%                           a structure with any of the fields:
%
%              minFPS     = the minimum video frame rate (frames/seconds)
%              minTime    = the minimum video time (seconds)
%              maxTime    = the maximum video time (seconds)
%              minSegTime = the minimum time for segmented video (seconds)
%              minRatio   = the minimum ratio for segmented video frames
%              minDate    = the minimum date to use (DATENUM)
%              maxDate    = the maximum date to use (DATENUM)
%              years      = the years to use
%              months     = the months to use (1-12)
%              weeks      = the weeks to use (1-52)
%              days       = the days (of the week) to use (1-7)
%              hours      = the hours to use (1-24)
%              trackers   = the trackers to use (1-8)
%
%       wormFeatFilter    - the worm feature filtering criteria;
%                           a structure with the fields:
%
%               featuresI = the feature indices (see WORMDATAINFO)
%               minThr    = the minimum feature value (optional)
%               maxThr    = the maximum feature value (optional)
%               indices   = the sub indices for the features (optional)
%               subFields = the subFields for the features (optional)
%
%       control           - the control histograms or filename;
%                           if empty; no control is shown
%       controlName       - the name for the control;
%                           or, a function handle of the form:
%
%                   LABEL = WORM2LABEL(WORMINFO)
%
%                           wormInfo = the worm information
%                           label    = the worm label
%
%                           if empty, we use WORM2STRAINLABEL
%
%       controlInfoFilter - the control indices to use;
%                           or, the control filtering criteria
%       controlFeatFilter - the control feature filtering criteria
%       significance      - the feature statistical significance or filename;
%                           if empty; no statistical significance is shown
%                           if a struct, the fields are:
%
%                           p = the p-value, per feature
%                           q = the q-value, per feature
%
%       isShow            - are we showing the figures onscreen?
%                           Note: hiding the figures is faster.
%       page              - the page number;
%                           if empty, the page number is not shown
%       saveQuality       - the quality (magnification) for saving the figures;
%                           if empty, the figures are not saved
%                           the default is none (empty)
%       isClose           - shoud we close the figures after saving them?
%                           when saving the figure, the default is yes (true)
%                           otherwise, the default is no (false)
%       isVerbose         - verbose mode displays the progress;
%                           the default is yes (true)
%   Output:
%       filename - the TIF file containing the saved figures;
%                  if empty, the figures were not saved
%       pages    - the number of pages in the figure file
%
% See also FILTERWORMINFO, FILTERWORMHIST, WORM2HISTOGRAM, WORM2STATSINFO
% Load the worm.
wormInfo = [];
if ischar(worm)
    load(worm, 'worm', 'wormInfo');
end
% Determine the worm name.
if isempty(wormName) && ~isempty(wormInfo)
    wormName = worm2StrainLabel(wormInfo);
elseif isa(wormName, 'function_handle')
    if ~isempty(wormInfo)
        wormName = wormName(wormInfo);
    else
        wormName = '';
    end
end
% Filter the worm information.
isWormUsed = [];
if ~isempty(varargin)
    wormInfoFilter = varargin{1};
    isWormUsed = filterWormInfo(wormInfo, wormInfoFilter);
end
% Filter the worm features.
if length(varargin) > 1
    % Filter the worm features.
    wormFeatFilter = varargin{2};
    isUsed = filterWormHist(worm, wormFeatFilter);
    % Combine the filters.
    if isempty(isWormUsed)
        isWormUsed = isUsed;
    else
        isWormUsed = isWormUsed & isUsed;
    end
end
% Do we have a control?
control = [];
controlName = [];
isControlUsed = [];
if length(varargin) > 2
    % Load the control.
    control = varargin{3};
    controlInfo = [];
    if ~isempty(control) && ischar(control)
        controlData = load(control, 'worm', 'wormInfo');
        control = controlData.worm;
        controlInfo = controlData.wormInfo;
        clear controlData;
    end
    % Do we have a control?
    if ~isempty(control)
        % Determine the control name.
        if length(varargin) > 3
            controlName = varargin{4};
        end
        if isempty(controlName) && ~isempty(controlInfo)
            controlName = worm2StrainLabel(controlInfo);
        elseif isa(controlName, 'function_handle')
            if ~isempty(controlInfo)
                controlName = controlName(controlInfo);
            else
                controlName = '';
            end
        end
        % Filter the control information.
        isControlUsed = [];
        if length(varargin) > 4
            controlInfoFilter = varargin{5};
            isControlUsed = filterWormInfo(controlInfo, controlInfoFilter);
        end
        % Filter the control features.
        if length(varargin) > 5
            % Filter the worm features.
            controlFeatFilter = varargin{6};
            isUsed = filterWormHist(control, controlFeatFilter);
            % Combine the filters.
            if isempty(isControlUsed)
                isControlUsed = isUsed;
            else
                isControlUsed = isControlUsed & isUsed;
            end
        end
    end
end
% Do we have the statistical significance?
sig = [];
if length(varargin) > 6
    significance = varargin{7};
    % Load the significance.
    if ~isempty(significance) && ischar(significance)
        % Load the significance matrix.
        if ~isempty(whos('-FILE', significance, 'worm'))
            sigData = load(significance, 'worm');
            % Find the genotype.
            genotype = worm2GenotypeLabel(wormInfo);
            strainI = find(cellfun(@(x) strcmp(genotype, x), ...
                sigData.worm.info.genotype));
            % Determine the significance.
            if length(strainI) == 1
                sig.p = sigData.worm.sig.pWValue(strainI,:);
                sig.q = sigData.worm.sig.qWValue.all(strainI,:);
%                 sig.power = sigData.worm.sig.power(strainI,:);
            end
        % Load the strain matrix.
        elseif ~isempty(whos('-FILE', significance, 'significance'))
            sigData = load(significance, 'significance');
            % Determine the significance.
            sig.p = [sigData.significance.features.pWValue];
            sig.q = [sigData.significance.features.qWValue];
%             sig.power = [sigData.significance.features.power];
        end
    % Determine the significance.
    else
        sig = significance;
    end
end
% Are we showing the figures onscreen?
% Note: hiding the figures is faster.
isShow = true;
if length(varargin) > 7
    isShow = varargin{8};
end
% Determine the page number.
pages = 0;
page = 0;
if length(varargin) > 8
    page = varargin{9};
    pages = page;
end
% Determine the quality (magnification) for saving the figures.
saveQuality = []; % don't save the figures
if length(varargin) > 9
    saveQuality = varargin{10};
end
% Are we closing the figures after saving them?
if saveQuality > 0
    isClose = true;
else
    isClose = false;
end
if length(varargin) > 10
    isClose = varargin{11};
end
if ~isShow
    isClose = true;
end
% Are we displaying the progress?
isVerbose = true;
if length(varargin) > 11
    isVerbose = varargin{12};
end
% Construct the file name.
if saveQuality > 0
    % Remove the TIF extension.
    tifExt = '.tif';
    tifName = filename;
    if length(tifName) >= length(tifExt) && ...
            strcmp(filename((end - length(tifExt) + 1):end), tifExt)
        tifName = filename(1:(end - length(tifExt)));
    end
    % Create the filename.
    if isempty(tifName)
        if isempty(controlName)
            tifName = [wormName ' details'];
        else
            tifName = [wormName ' vs ' controlName ' details'];
        end
    end
    % Add the TIF extension.
    filename = [tifName '.tif'];
% We are not saving a file.
else
    filename = [];
end
% Initialize the feature information.
dispInfo = wormDisplayInfo();
dataInfo = wormDataInfo();
statsInfo = wormStatsInfo();
% Draw the features.
i = 1;
while i <= length(dataInfo)
    % Draw the features.
    switch dataInfo(i).type
        % Draw a quadrant of simple features.
        case 's'
            % Compute the page.
            page = page + 1;
            % Display the progress.
            if isVerbose
                disp(['Printing details ' num2str(i) '/' ...
                    num2str(length(dataInfo)) ' ...']);
            end
            % Add up to 3 more simple features to the page.
            j = i;
            endJ = min(i + 3, length(dataInfo));
            while j < endJ
                j = j + 1;
            end
            % Draw the feature.
            drawSimpleData(filename, page, i:j, worm, wormName, ...
                isWormUsed, control, controlName, isControlUsed, ...
                sig, dispInfo, dataInfo, statsInfo, ...
                isShow, saveQuality, isClose);
            % Advance.
            i = j;
        % Draw the quadrants of the motion features.
        case 'm'
            % Get the data.
            field = dataInfo(i).field;
            dispData = getStructField(dispInfo, field);
            wormData = getStructField(worm, field);
            controlData = [];
            if ~isempty(control)
                controlData = getStructField(control, field);
            end
            % Draw the data.
            if isempty(controlData)
                for j = 1:length(wormData)
                    % Compute the page.
                    page = page + 1;
                    % Display the progress.
                    if isVerbose
                        disp(['Printing details ' num2str(i) '/' ...
                            num2str(length(dataInfo)) ' ...']);
                    end
                    % Draw the feature.
                    drawMotionData(filename, page, i, j, ...
                        wormData(j), wormName,  isWormUsed, [], [], [], ...
                        sig, dispData(j), dataInfo, statsInfo, ...
                        isShow, saveQuality, isClose);
                end
            % Draw the controlled data.
            else
                for j = 1:length(wormData)
                    % Compute the page.
                    page = page + 1;
                    % Display the progress.
                    if isVerbose
                        disp(['Printing details ' num2str(i) '/' ...
                            num2str(length(dataInfo)) ' ...']);
                    end
                    % Draw the feature.
                    drawMotionData(filename, page, i, j, ...
                        wormData(j), wormName,  isWormUsed, ...
                        controlData(j), controlName, isControlUsed, ...
                        sig, dispData(j), dataInfo, statsInfo, ...
                        isShow, saveQuality, isClose);
                end
            end
        % Draw the quadrants of the event.
        case 'e'
            % Compute the page.
            page = page + 1;
            % Display the progress.
            if isVerbose
                disp(['Printing details ' num2str(i) '/' ...
                    num2str(length(dataInfo)) ' ...']);
            end
            % Draw the feature.
            drawEventData(filename, page, i, worm, wormName, ...
                isWormUsed, control, controlName,  isControlUsed, ...
                sig, dispInfo, dataInfo, statsInfo, ...
                isShow, saveQuality, isClose);
    end
    % Advance.
    i = i + 1;
end
% Compute the pages.
pages = page - pages;
end
%% Draw a quadrant of simple features.
function drawSimpleData(filename, page, featureI, worm, wormName, ...
    isWormUsed, control, controlName, isControlUsed, sig, ...
    dispInfo, dataInfo, statsInfo, isShow, saveQuality, isClose)
% Initialize the fonts.
smallFontStr = '\rm\fontsize{10}';
bigFontStr = '\bf\fontsize{14}';
axisFontSize = 12;
% Initialize the color scheme.
statColorScale = 0.6;
wormColor = str2colors('n');
controlColor = str2colors('k');
if isempty(control)
    histColors = wormColor;
else
    histColors = [controlColor; wormColor];
end
statColors = histColors * statColorScale;
% Create a figure.
h = figure;
visStr = 'off';
if isShow
    visStr = 'on';
end
set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
    'PaperType', 'A2', 'Visible', visStr);
hold on;
% Draw the feature histograms.
statsInfoTitle1I = [statsInfo.title1I];
featureNames = cell(length(featureI), 1);
for i = 1:length(featureI)
    % Get the data.
    field = dataInfo(featureI(i)).field;
    wormHist = getStructField(worm, [field '.histogram']);
    wormHist = filterHistogram(wormHist, isWormUsed);
    controlHist = [];
    if ~isempty(control)
        controlHist = getStructField(control, [field '.histogram']);
        controlHist = filterHistogram(controlHist, isControlUsed);
    end
    % Downsample the data.
    hist = [controlHist, wormHist];
    hist = downSampleHistogram(hist);
    % Get the statistics.
    sigI = find(statsInfoTitle1I == featureI(i), 1);
    disp = getStructField(dispInfo, field);
    featureNames{i} = disp.name;
    [statsStrs sigs] = stats2strs(wormHist, controlHist, sig, sigI);
    % Create the labels.
%     titleLabel{1} = [bigFontStr wormName];
%     if ~isempty(controlName)
%         titleLabel{1} = [titleLabel{1} '   [' controlName ']'];
%     end
    titleLabel{1} = [bigFontStr upper(disp.name) smallFontStr];
    titleLabel(2:(length(statsStrs) + 1)) = statsStrs;
    xLabel = [bigFontStr disp.unit ' '];
    % Draw the data.
    subplot(2,2,i);
    hold on;
    plotHistogram(hist, titleLabel, xLabel, bigFontStr, [], ...
        histColors, statColors, 1, 0, 1, 1);
    % Embiggen the x-axis ticks.
    set(gca, 'FontSize', axisFontSize);
    % Color the significance.
    set(gca, 'Color', p2BackColor(min(sigs)));
end
% Draw the legend.
drawSimpleLegend(h);
% Save the figure.
if saveQuality > 0
    pageTitle = info2pageTitle(wormName, controlName, featureI, ...
        featureNames, dataInfo);
    saveTIF(h, filename, saveQuality, true, pageTitle, page, isClose);
% Close the figure.
elseif ~isShow || isClose
    close(h);
end
end
%% Draw a quadrant of the motion features.
function drawMotionData(filename, page, featureI, index, worm, wormName, ...
    isWormUsed, control, controlName, isControlUsed, sig, ...
    dispInfo, dataInfo, statsInfo, isShow, saveQuality, isClose)
% Initialize the fonts.
smallFontStr = '\rm\fontsize{10}';
bigFontStr = '\bf\fontsize{14}';
axisFontSize = 12;
% Initialize the color scheme.
% Note: the order for 3 color schemes is forward, backward, paused.
statColorScale = 0.6;
wormColor = str2colors('n');
%wormColor3 = str2colors('rgb', [0, -0.5, 0]);
wormColor3 = str2colors('mgb', [0, -1/3, 0]);
controlColor = str2colors('k');
% Initialize the motion fields.
motionField = {
    'forward'
    'paused'
    'backward'};
% Get the worm histograms.
numPlots = 6;
wormHist = filterHistogram(worm.histogram, isWormUsed);
wormHist3 = [];
for i = 1:length(motionField)
    wormHist3 = cat(1, wormHist3, worm.(motionField{i}).histogram);
end
wormHist3 = filterHistogram(wormHist3, isWormUsed);
% Group the control histograms.
if ~isempty(control)
    controlHist = filterHistogram(control.histogram, isControlUsed);
    controlHist3 = [];
    for i = 1:length(motionField)
        controlHist3 = cat(1, controlHist3, ...
            control.(motionField{i}).histogram);
    end
    controlHist3 = filterHistogram(controlHist3, isControlUsed);
end
% Allocate the memory.
titles = cell(numPlots, 1);
hists = cell(numPlots, 1);
histColors = cell(numPlots, 1);
statColors = cell(numPlots, 1);
histModes = cell(numPlots, 1);
logModes = cell(numPlots, 1);
sigColors = cell(numPlots, 1);
% Get the feature information.
numSigns = 1;
if wormHist.isSigned
    numSigns = 4;
end
if index > 1
    sigI = find([statsInfo.title1I] == featureI & ...
        [statsInfo.index] == index, 1);
else
    sigI = find([statsInfo.title1I] == featureI, 1);
end
% Create the x-axis label.
%xLabel = [bigFontStr dispInfo.name ' (' dispInfo.unit ') '];
xLabel = [bigFontStr dispInfo.unit ' '];
% Group the worm drawings.
if isempty(control)
    % Draw the worm.
    [statsStrs sigs] = stats2strs(wormHist, [], sig, sigI);
    titleStrs = [];
%     titleStrs{1} = [bigFontStr wormName ' [' controlName ']: ' ...
%         upper(dispInfo.name) smallFontStr];
    titleStrs{1} = [bigFontStr upper(dispInfo.name) smallFontStr];
    titleStrs(2:(length(statsStrs) + 1)) = statsStrs;
    titles{1} = titleStrs;
    hists{1} = downSampleHistogram(wormHist);
    histColors{1} = wormColor;
    statColors{1} = histColors{1} * statColorScale;
    histModes{1} = 1;
    % Draw the worm motion vs. the worm.
    titles{2} = [bigFontStr wormName ': ' upper(dispInfo.name)];
    hists{2} = downSampleHistogram([wormHist3; wormHist]);
    histColors{2} = [wormColor3; controlColor];
    histModes{2} = 2;
    % Draw the worm motion.
    for i = 1:3
        % Create the title.
        [statsStrs sigs] = stats2strs(wormHist3(i), [], ...
            sig, sigI + i * numSigns);
        titleStrs = [];
%         titleStrs{1} = [bigFontStr wormName ' [' controlName ']: ' ...
%             upper([motionField{i} ' ' dispInfo.name]) smallFontStr ];
        titleStrs{1} = [bigFontStr ...
            upper([motionField{i} ' ' dispInfo.name]) smallFontStr ];
        titleStrs(2:(length(statsStrs) + 1)) = statsStrs;
        titles{i + 3} = titleStrs;
        % Create the histogram.
        hists{i + 3} = downSampleHistogram(wormHist3(i));
        histColors{i + 3} = wormColor3(i,:);
        statColors{i + 3} = histColors{i + 3} * statColorScale;
        histModes{i + 3} = 1;
    end
% Group the worm and control drawings.
else
    % Draw the worm vs. the control.
    [statsStrs sigs] = stats2strs(wormHist, controlHist, sig, sigI);
    titleStrs = [];
%     titleStrs{1} = [bigFontStr wormName ' [' controlName ']: ' ...
%         upper(dispInfo.name) smallFontStr];
    titleStrs{1} = [bigFontStr upper(dispInfo.name) smallFontStr];
    titleStrs(2:(length(statsStrs) + 1)) = statsStrs;
    titles{1} = titleStrs;
    hists{1} = downSampleHistogram([controlHist; wormHist]);
    histColors{1} = [controlColor; wormColor];
    statColors{1} = histColors{1} * statColorScale;
    histModes{1} = 1;
    sigColors{1} = p2BackColor(min(sigs));
    % Draw the worm motion vs. the worm.
    titles{2} = [bigFontStr wormName ': ' upper(dispInfo.name)];
    hists{2} = downSampleHistogram([wormHist3; wormHist]);
    histColors{2} = [wormColor3; controlColor];
    histModes{2} = 2;
    % Draw the control motion vs. the control.
    titles{3} = [bigFontStr controlName ': ' upper(dispInfo.name)];
    hists{3} = downSampleHistogram([controlHist3; controlHist]);
    histColors{3} = [wormColor3; controlColor];
    histModes{3} = 2;
    % Draw the worm motion vs. control motion.
    for i = 1:3
        % Create the title.
        [statsStrs sigs] = stats2strs(wormHist3(i), controlHist3(i), ...
            sig, sigI + i * numSigns);
        titleStrs = [];
%         titleStrs{1} = [bigFontStr wormName ' [' controlName ']: ' ...
%             upper([motionField{i} ' ' dispInfo.name]) smallFontStr ];
        titleStrs{1} = [bigFontStr ...
            upper([motionField{i} ' ' dispInfo.name]) smallFontStr ];
        titleStrs(2:(length(statsStrs) + 1)) = statsStrs;
        titles{i + 3} = titleStrs;
        % Create the histogram.
        hists{i + 3} = downSampleHistogram([controlHist3(i); wormHist3(i)]);
        histColors{i + 3} = [controlColor; wormColor3(i,:)];
        statColors{i + 3} = histColors{i + 3} * statColorScale;
        histModes{i + 3} = 1;
        sigColors{i + 3} = p2BackColor(min(sigs));
    end
end
% Create a figure.
h = figure;
visStr = 'off';
if isShow
    visStr = 'on';
end
set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
    'PaperType', 'A2', 'Visible', visStr);
hold on;
% Draw the features.
for i = 1:length(hists)
    if ~isempty(titles{i})
        % Draw the data.
        subplot(2,3,i);
        hold on;
        plotHistogram(hists{i}, titles{i}, xLabel, bigFontStr, [], ...
            histColors{i}, statColors{i}, histModes{i}, 0, 1, 1, ...
            logModes{i});
        % Embiggen the x-axis ticks.
        set(gca, 'FontSize', axisFontSize);
        % Color the significance.
        if ~isempty(sigColors{i})
            set(gca, 'Color', sigColors{i});
        end
    end
end
% Draw the legend.
drawMotionLegend(h);
% Save the figure.
if saveQuality > 0
    pageTitle = info2pageTitle(wormName, controlName, featureI, ...
        {dispInfo.name}, dataInfo);
    saveTIF(h, filename, saveQuality, true, pageTitle, page, isClose);
% Close the figure.
elseif ~isShow || isClose
    close(h);
end
end
%% Draw a quadrant of the event.
function drawEventData(filename, page, featureI, worm, wormName, ...
    isWormUsed, control, controlName, isControlUsed, sig, ...
    dispInfo, dataInfo, statsInfo, isShow, saveQuality, isClose)
% Initialize the fonts.
smallFontStr = '\rm\fontsize{10}';
bigFontStr = '\bf\fontsize{14}';
axisFontSize = 12;
% Initialize the color scheme.
% Note: the order for 2 color schemes is feature and inter-feature.
statColorScale = 0.6;
wormColor = str2colors('n');
wormColor2 = str2colors('gm', [-1/3, 0]);
controlColor = str2colors('k');
controlColor2 = str2colors('kk', [0 .6]);
% Initialize the fields.
field = dataInfo(featureI).field;
summaryFields = dataInfo(featureI).subFields.summary;
dataFields = dataInfo(featureI).subFields.data;
% Group the worm summary fields.
worm = getStructField(worm, field);
wormFields = [];
for i = 1:length(summaryFields)
    subField = getStructField(worm, summaryFields{i});
    wormFields = cat(1, wormFields, subField);
end
% Group the worm control fields.
controlFields = [];
if ~isempty(control)
    control = getStructField(control, field);
    for i = 1:length(summaryFields)
        subField = getStructField(control, summaryFields{i});
        controlFields = cat(1, controlFields, subField);
    end
end
% Create the summary statistics strings.
sigI = find([statsInfo.title1I] == featureI, 1);
[summaryStrs summarySigs] = eventStats2strs(wormFields, isWormUsed, ...
    controlFields, isControlUsed, sig, sigI);
% Group the worm histograms.
wormHists = [];
numSigns = ones(length(dataFields), 1);
for i = 1:length(dataFields)
    wormHists = cat(1, wormHists, worm.(dataFields{i}).histogram);
    if ~isnan(wormHists(i).isSigned) && wormHists(i).isSigned
        numSigns(i) = 4;
    end
end
wormHists = filterHistogram(wormHists, isWormUsed);
% Group the control histograms.
if ~isempty(control)
    controlHists = [];
    for i = 1:length(dataFields)
        controlHists = ...
            cat(1, controlHists, control.(dataFields{i}).histogram);
    end
    controlHists = filterHistogram(controlHists, isControlUsed);
end
% Create the data statistics strings.
dataStrs = cell(length(wormHists), 1);
dataSigs = cell(length(wormHists), 1);
sigI = sigI + length(summaryFields);
if isempty(control)
    for i = 1:length(wormHists)
        [dataStrs{i} dataSigs{i}] = stats2strs(wormHists(i), [], ...
            sig, sigI + (i - 1) * numSigns(i));
    end
else
    for i = 1:length(wormHists)
        [dataStrs{i} dataSigs{i}] = stats2strs(wormHists(i), ...
            controlHists(i), sig, sigI + (i - 1) * numSigns(i));
    end
end
% Get the labels.
disp = getStructField(dispInfo, field);
names = cell(length(dataFields), 1);
units = cell(length(dataFields), 1);
for i = 1:length(dataFields)
    names{i} = disp.(dataFields{i}).name;
    units{i} = disp.(dataFields{i}).unit;
end
% Group the histograms.
titles = cell(length(wormHists), 1);
xLabels = cell(length(wormHists), 1);
hists = cell(length(wormHists), 1);
histModes = cell(length(wormHists), 1);
sigColors = cell(length(wormHists), 1);
for i = 1:length(hists)
    % Create the title.
    titleStrs = [];
%     titleStrs{1} = [bigFontStr wormName];
%     if ~isempty(control)
%         titleStrs{1} = [titleStrs{1} '   [' controlName ']'];
%     end
%     titleStrs{1} = [titleStrs{1} ': ' upper(names{i}) smallFontStr];
    titleStrs{1} = [bigFontStr upper(names{i}) smallFontStr];
    titleStrs(2:(length(dataStrs{i}) + 1)) = dataStrs{i};
    titles{i} = titleStrs;
    % Create the x-axis label.
%     xLabels{i} = [bigFontStr names{i} ' (' units{i} ') '];
    xLabels{i} = [bigFontStr units{i} ' '];
    % Create the histogram.
    if isempty(control)
        hists{i} = downSampleHistogram(wormHists(i));
    else
        hists{i} = downSampleHistogram([controlHists(i); wormHists(i)]);
    end
    histModes{i} = 1;
    sigColors{i} = p2BackColor(min(dataSigs{i}));
end
% Group the 4 drawings.
histColors = cell(length(wormHists), 1);
statColors = cell(length(wormHists), 1);
if length(hists) == 3
    % Re-order the existing drawings.
    oldI = 3;
    newI = 4;
    titles(newI) = titles(oldI);
    xLabels(newI) = xLabels(oldI);
    hists(newI) = hists(oldI);
    histModes(newI) = histModes(oldI);
    sigColors(newI) = sigColors(oldI);
    logModes = cell(4, 1);
    % Color the existing drawings.
    if isempty(control)
        histColors{1} = wormColor2(1,:);
        histColors{2} = wormColor2(2,:);
        histColors{4} = wormColor;
    else
        histColors{1} = [controlColor2(1,:); wormColor2(1,:)];
        histColors{2} = [controlColor2(2,:); wormColor2(2,:)];
        histColors{4} = [controlColor; wormColor];
    end
    for i = 1:length(histColors)
        statColors{i} = histColors{i} * statColorScale;
    end
    % Create the comparative titles.
    titleStrs = [];
    titleStrs{1} = [bigFontStr upper(['Inter vs. ' names{1}]) smallFontStr];
    titleStrs(2:(length(summaryStrs) + 1)) = summaryStrs;
    titles{3} = titleStrs;
%     xLabels{3} = [bigFontStr names{1} ' vs. ' names{2} ' (' units{1} ') '];
    xLabels{3} = [bigFontStr units{1} ' '];
    histModes{3} = 2;
    logModes{3} = 1;
    sigColors{3} = p2BackColor(min(summarySigs));
    % Create the comparative drawings.
    if isempty(control)
        hists{3} = downSampleHistogram([wormHists(1); wormHists(2)]);
        histColors{3} = wormColor2;
    else
        hists{3} = ...
            downSampleHistogram([controlHists(1); controlHists(2); ...
            wormHists(1); wormHists(2)]);
        histColors{3} = [controlColor2; wormColor2];
    end
% Group the 6 drawings.
else % length(dataFields) == 4
    % Re-order the existing drawings.
    oldI = [2 3 4];
    newI = [4 2 5];
    titles(newI) = titles(oldI);
    xLabels(newI) = xLabels(oldI);
    hists(newI) = hists(oldI);
    histModes(newI) = histModes(oldI);
    sigColors(newI) = sigColors(oldI);
    logModes = cell(6, 1);
    % Color the existing drawings.
    if isempty(control)
        histColors{1} = wormColor2(1,:);
        histColors{2} = wormColor2(2,:);
        histColors{4} = wormColor2(1,:);
        histColors{5} = wormColor2(2,:);
    else
        histColors{1} = [controlColor2(1,:); wormColor2(1,:)];
        histColors{2} = [controlColor2(2,:); wormColor2(2,:)];
        histColors{4} = [controlColor2(1,:); wormColor2(1,:)];
        histColors{5} = [controlColor2(2,:); wormColor2(2,:)];
    end
    for i = 1:length(histColors)
        statColors{i} = histColors{i} * statColorScale;
    end
    statColors{6} = [];
    % Create the comparative titles for the time.
    titleStrs = [];
    titleStrs{1} = [bigFontStr upper(['Inter vs. ' names{1}]) smallFontStr];
    titleStrs(2:4) = summaryStrs(1:3);
    titles{3} = titleStrs;
%     xLabels{3} = [bigFontStr names{1} ' vs. ' names{3} ' (' units{1} ') '];
    xLabels{3} = [bigFontStr units{1} ' '];
    histModes{3} = 2;
    logModes{3} = 1;
    sigColors{3} = p2BackColor(min(summarySigs(1:2)));
    % Create the comparative titles for the distance.
    titleStrs = [];
    titleStrs{1} = [bigFontStr upper(['Inter vs. ' names{2}]) smallFontStr];
    titleStrs(2:3) = summaryStrs([1,4]);
    titles{6} = titleStrs;
%     xLabels{6} = [bigFontStr names{2} ' vs. ' names{4} ' (' units{2} ') '];
    xLabels{6} = [bigFontStr units{2} ' '];
    histModes{6} = 2;
    logModes{6} = 1;
    sigColors{6} = p2BackColor(summarySigs(3));
    % Create the comparative drawings.
    if isempty(control)
        hists{3} = downSampleHistogram([wormHists(1); wormHists(3)]);
        hists{6} = downSampleHistogram([wormHists(2); wormHists(4)]);
        histColors{3} = wormColor2;
        histColors{6} = wormColor2;
    else
        hists{3} = ...
            downSampleHistogram([controlHists(1); controlHists(3); ...
            wormHists(1); wormHists(3)]);
        hists{6} = ...
            downSampleHistogram([controlHists(2); controlHists(4); ...
            wormHists(2); wormHists(4)]);
        histColors{3} = [controlColor2; wormColor2];
        histColors{6} = [controlColor2; wormColor2];
    end
end
% Create a figure.
h = figure;
visStr = 'off';
if isShow
    visStr = 'on';
end
set(h, 'units', 'normalized', 'position', [0 0 1 1], ...
    'PaperType', 'A2', 'Visible', visStr);
hold on;
% Draw the feature histograms.
for i = 1:length(hists)
    % Draw the data.
    subplot(2,3,i);
    hold on;
    plotHistogram(hists{i}, titles{i}, xLabels{i}, bigFontStr, [], ...
        histColors{i}, statColors{i}, histModes{i}, 0, 1, 1, logModes{i});
    % Embiggen the x-axis ticks.
    set(gca, 'FontSize', axisFontSize);
    % Color the significance.
1000     if ~isempty(sigColors{i})
1001         set(gca, 'Color', sigColors{i});
1002     end
1003 end
1004
1005 % Draw the legend.
1006 drawEventLegend(h);
1007
1008 % Save the figure.
1009 if saveQuality > 0
1010     pageTitle = info2pageTitle(wormName, controlName, featureI, ...
1011         {disp.name}, dataInfo);
1012     saveTIF(h, filename, saveQuality, true, pageTitle, page, isClose);
1013
1014 % Close the figure.
1015 elseif ~isShow || isClose
1016     close(h);
1017 end
1018 end
1019
1020
1021
1022 %% Show the simple legend.
1023 function drawSimpleLegend(h)
1024
1025 % Initialize the drawing information.
1026 fontSize = 20;
1027 black = str2colors('k');
1028 white = str2colors('w');
1029 experimentColor = str2colors('n');
1030 controlColor = str2colors('k');
1031
1032 % Setup the label information.
1033 label = {
1034     ' \bfEXPERIMENT '
1035     ' \bfCONTROL '
1036     ' \bfn.s. '
1037     ' \bf*\rm (\itq \leq 0.05\rm) '
1038     ' \bf**\rm (\itq \leq 0.01\rm) '
1039     ' \bf***\rm (\itq \leq 0.001\rm) '
1040     ' \bf****\rm (\itq \leq 0.0001\rm) '};
1041 backColor = {
1042     experimentColor
1043     controlColor
1044     white
1045     p2BackColor(0.03)
1046     p2BackColor(0.003)
1047     p2BackColor(0.0003)
1048     p2BackColor(0.00003)};
1049 foreColor = {
1050     white
1051     white
1052     black
1053     black
1054     black
1055     black
1056     black};
1057
1058 % Setup the margin.
1059 xOff = 10^-3;
1060 xPosOff = 1 - xOff;
1061 textPosition = [xPosOff, 0, xOff, 1];
1062 textAxis = axes('units', 'normalized', 'Position', textPosition, ...
1063     'XTick', [], 'YTick', [], 'Parent', h);
1064
1065 % Draw the labels.
1066 yStart = 0.99;
1067 yStart2 = 0.16;
1068 yOff = 0.03;
1069 for i = 1:length(label)
1070
1071     % Draw the label.
1072     text(xOff, yStart - (i - 1) * yOff, label{i}, ...
1073         'FontSize', fontSize, ...
1074         'HorizontalAlignment', 'right', ...
1075         'VerticalAlignment', 'top', ...
1076         'BackgroundColor', backColor{i}, ...
1077         'Color', foreColor{i}, ...
1078         'EdgeColor', 'k', ...
1079         'Parent', textAxis);
1080
1081     % Put in a space.
1082     if i == 2
1083         yStart = yStart2 + i * yOff;
1084     end
1085 end
1086 end
1087
1088
1089
1090 %% Show the motion legend.
1091 function drawMotionLegend(h)
1092
1093 % Initialize the drawing information.
1094 fontSize = 20;
1095 black = str2colors('k');
1096 white = str2colors('w');
1097 experimentColor = str2colors('n');
1098 controlColor = str2colors('k');
1099 forwardColor = str2colors('m');
1100 pausedColor = str2colors('g', -1/3);
1101 backwardColor = str2colors('b');
1102
1103 % Setup the label information.
1104 label = {
1105     ' \bfEXPERIMENT '
1106     ' \bfCONTROL '
1107     ' \bfBACKWARD '
1108     ' \bfFORWARD '
1109     ' \bfPAUSED '
1110     ' \bfn.s. '
1111     ' \bf*\rm (\itq \leq 0.05\rm) '
1112     ' \bf**\rm (\itq \leq 0.01\rm) '
1113     ' \bf***\rm (\itq \leq 0.001\rm) '
1114     ' \bf****\rm (\itq \leq 0.0001\rm) '};
1115 backColor = {
1116     experimentColor
1117     controlColor
1118     backwardColor
1119     forwardColor
1120     pausedColor
1121     white
1122     p2BackColor(0.03)
1123     p2BackColor(0.003)
1124     p2BackColor(0.0003)
1125     p2BackColor(0.00003)};
1126 foreColor = {
1127     white
1128     white
1129     white
1130     white
1131     white
1132     black
1133     black
1134     black
1135     black
1136     black};
1137
1138 % Setup the margin.
1139 xOff = 10^-3;
1140 xPosOff = 1 - xOff;
1141 textPosition = [xPosOff, 0, xOff, 1];
1142 textAxis = axes('units', 'normalized', 'Position', textPosition, ...
1143     'XTick', [], 'YTick', [], 'Parent', h);
1144
1145 % Draw the labels.
1146 yStart = 0.99;
1147 yStart2 = 0.55;
1148 yStart3 = 0.16;
1149 yOff = 0.03;
1150 for i = 1:length(label)
1151
1152     % Draw the label.
1153     text(xOff, yStart - (i - 1) * yOff, label{i}, ...
1154         'FontSize', fontSize, ...
1155         'HorizontalAlignment', 'right', ...
1156         'VerticalAlignment', 'top', ...
1157         'BackgroundColor', backColor{i}, ...
1158         'Color', foreColor{i}, ...
1159         'EdgeColor', 'k', ...
1160         'Parent', textAxis);
1161
1162     % Put in a space.
1163     if i == 2
1164         yStart = yStart2 + i * yOff;
1165     elseif i == 5
1166         yStart = yStart3 + i * yOff;
1167     end
1168 end
1169 end
1170
1171
1172
1173 %% Show the event legend.
1174 function drawEventLegend(h)
1175
1176 % Initialize the drawing information.
1177 fontSize = 20;
1178 black = str2colors('k');
1179 white = str2colors('w');
1180 experimentColor = str2colors('n');
1181 controlColor = str2colors('k');
1182 eventColor = str2colors('g', -1/3);
1183 interEventColor = str2colors('m', 0);
1184 interControlColor = str2colors('k', 0.5);
1185
1186 % Setup the label information.
1187 label = {
1188     ' \bfEXPERIMENT '
1189     ' \bfCONTROL '
1190     ' \bfINTER CONTROL'
1191     ' \bfINTER EVENT '
1192     ' \bfEVENT '
1193     ' \bfn.s. '
1194     ' \bf*\rm (\itq \leq 0.05\rm) '
1195     ' \bf**\rm (\itq \leq 0.01\rm) '
1196     ' \bf***\rm (\itq \leq 0.001\rm) '
1197     ' \bf****\rm (\itq \leq 0.0001\rm) '};
1198 backColor = {
1199     experimentColor
1200     controlColor
1201     interControlColor
1202     interEventColor
1203     eventColor
1204     white
1205     p2BackColor(0.03)
1206     p2BackColor(0.003)
1207     p2BackColor(0.0003)
1208     p2BackColor(0.00003)};
1209 foreColor = {
1210     white
1211     white
1212     white
1213     white
1214     white
1215     black
1216     black
1217     black
1218     black
1219     black};
1220
1221 % Setup the margin.
1222 xOff = 10^-3;
1223 xPosOff = 1 - xOff;
1224 textPosition = [xPosOff, 0, xOff, 1];
1225 textAxis = axes('units', 'normalized', 'Position', textPosition, ...
1226     'XTick', [], 'YTick', [], 'Parent', h);
1227
1228 % Draw the labels.
1229 yStart = 0.99;
1230 yStart2 = 0.55;
1231 yStart3 = 0.16;
1232 yOff = 0.03;
1233 for i = 1:length(label)
1234
1235     % Draw the label.
1236     text(xOff, yStart - (i - 1) * yOff, label{i}, ...
1237         'FontSize', fontSize, ...
1238         'HorizontalAlignment', 'right', ...
1239         'VerticalAlignment', 'top', ...
1240         'BackgroundColor', backColor{i}, ...
1241         'Color', foreColor{i}, ...
1242         'EdgeColor', 'k', ...
1243         'Parent', textAxis);
1244
1245     % Put in a space.
1246     if i == 2
1247         yStart = yStart2 + i * yOff;
1248     elseif i == 5
1249         yStart = yStart3 + i * yOff;
1250     end
1251 end
1252 end
1253
1254
1255
1256 %% Convert a p-value to a foreground color representing significance.
1257 function color = p2ForeColor(p)
1258
1259 % The p-value is not significant.
1260 color = str2colors('c');
1261
1262 % Determine the significance of the p-value.
1263 if p <= 0.0001
1264     color = str2colors('m');
1265 elseif p <= 0.001
1266     color = str2colors('r');
1267 elseif p <= 0.01
1268     color = str2colors('o');
1269 elseif p <= 0.05
1270     color = str2colors('y');
1271 end
1272 end
1273
1274
1275
1276 %% Convert a p-value to a background color representing significance.
1277 function color = p2BackColor(p)
1278
1279 % The p-value is not significant.
1280 color = str2colors('w');
1281
1282 % Determine the significance of the p-value.
1283 if p <= 0.0001
1284     color = [.9, .8, 1];
1285 elseif p <= 0.001
1286     color = [1, .8, .8];
1287 elseif p <= 0.01
1288     color = [1, .9, .7];
1289 elseif p <= 0.05
1290     color = [1, 1, .7];
1291 end
1292 end
1293
1294
1295
1296 %% Convert the statistics to strings.
1297 function [str sigs] = stats2strs(worm, control, sig, sigI)
1298
1299 % No data.
1300 if (isempty(worm) || isnan(worm.resolution)) && ...
1301         (isempty(control) || isnan(control.resolution))
1302     str = {'NO DATA'};
1303     sigs = NaN;
1304     return;
1305 end
1306
1307 % Initialize special ascii symbols.
1308 semChar = '';
1309 sepStr = '      ';
1310
1311 % Initialize the fields.
1312 fields = {
1313     'all'
1314     'abs'
1315     'pos'
1316     'neg'};
1317
1318 % Is the feature signed?
1319 if ~isnan(worm.isSigned) && worm.isSigned
1320     endI = 4;
1321 else
1322     endI = 1;
1323 end
1324
1325 % Allocate memory.
1326 str = cell(endI + 1, 1);
1327 sigs = nan(endI, 1);
1328
1329 % % Show the names.
1330 % str{1} = wormName;
1331 % if ~isempty(controlName)
1332 %     str{1} = [str{1} ' [' controlName ']'];
1333 % end
1334
1335 % Show the worm samples.
1336 %str{1} = [str{1} sepStr 'WORMS=' num2str(worm.sets.samples, '%.0G')];
1337 if isnan(worm.sets.samples)
1338     wormsStr = '0';
1339 else
1340     wormsStr = num2str(worm.sets.samples, '%.3G');
1341 end
1342 str{1} = ['WORMS = ' wormsStr];
1343
1344 % Show the control samples.
1345 if ~isempty(control)
1346     if isnan(control.sets.samples)
1347         controlsStr = '0';
1348     else
1349         controlsStr = num2str(control.sets.samples, '%.3G');
1350     end
1351     str{1} = [str{1} '   [' controlsStr ']'];
1352 end
1353
1354 % Show the total worm samples.
1355 if isnan(worm.allData.samples)
1356     wormsTotalStr = '0';
1357 else
1358     wormsTotalStr = num2str(worm.allData.samples, '%.3G');
1359 end
1360 str{1} = [str{1} sepStr 'SAMPLES = ' wormsTotalStr];
1361
1362 % Show the total control samples.
1363 if ~isempty(control)
1364     if isnan(control.allData.samples)
1365         controlsTotalStr = '0';
1366     else
1367         controlsTotalStr = num2str(control.allData.samples, '%.3G');
1368     end
1369     str{1} = [str{1} '   [' controlsTotalStr ']'];
1370 end
1371
1372 % Determine the square root of the sample sets.
1373 wormSqrt = sqrt(worm.sets.samples);
1374 if ~isempty(control)
1375     controlSqrt = sqrt(control.sets.samples);
1376 end
1377
1378 % Convert the statistics to strings.
1379 for i = 1:endI
1380
1381     % Determine the inequality between experiment and control.
1382     wormMean = worm.sets.mean.(fields{i});
1383     eqStr = '   ';
1384     if ~isempty(control)
1385         controlMean = control.sets.mean.(fields{i});
1386         if wormMean > controlMean
1387             %eqStr = ' > ';
1388             eqStr = ' >>> ';
1389         elseif wormMean < controlMean
1390             %eqStr = ' < ';
1391             eqStr = ' <<< ';
1392         end
1393     end
1394
1395     % Don't show the inequality between experiment and control.
1396     sigStr = [];
1397     if isempty(sig)
1398         eqStr = '   ';
1399
1400     % Determine the significance.
1401     else
1402         k = sigI + i - 1;
1403         sigs(i) = sig.q(k);
1404
1405         % The significance was not measured.
1406         if isnan(sigs(i))
1407             eqStr = '   ';
1408
1409         % Show the significance.
1410         else
1411
1412 %             % Determine the power.
1413 %             if isnan(sig.power(k))
1414 %                 betaStr = '1';
1415 %             else
1416 %                 betaStr = num2str(1 - sig.power(k), '%.2G');
1417 %             end
1418
1419             % Show the significance.
1420             sigStr = [sepStr '(p=' num2str(sig.p(k), '%.2G') ...
1421                 ', q=' num2str(sig.q(k), '%.2G')];
1422 %                 ', \beta=' betaStr];
1423             sigStr = [sigStr ')   ' p2stars(sigs(i))];
1424
1425             % Don't show the inequality between experiment and control.
1426             if sigs(i) > 0.05
1427                 eqStr = '   ';
1428             end
1429         end
1430     end
1431
1432     % Determine the separator string.
1433     preStr = [];
1434 %     if ~mod(i, 2)
1435 %         preStr = sepStr;
1436 %     end
1437
1438     % Show the worm statistics.
1439     if isnan(wormMean)
1440         dataStr = 'NO DATA';
1441     else
1442         meanStr = num2str(wormMean, '%.3G');
1443         semStr = num2str(worm.sets.stdDev.(fields{i}) / wormSqrt, '%.3G');
1444         dataStr = [meanStr semChar semStr];
1445     end
1446 %     j = floor((i + 3) / 2);
1447     j = i + 1;
1448     str{j} = [str{j} preStr upper(fields{i}) ' = ' dataStr];
1449
1450     % Show the control statistics.
1451     if ~isempty(control)
1452         if isnan(controlMean)
1453             dataStr = 'NO DATA';
1454         else
1455             meanStr = num2str(controlMean, '%.3G');
1456             semStr = num2str(control.sets.stdDev.(fields{i}) / ...
1457                 controlSqrt, '%.3G');
1458             dataStr = [meanStr semChar semStr];
1459         end
1460         str{j} = [str{j} eqStr '[' dataStr ']'];
1461
1462     end
1463
1464     % Show the significance.
1465     if sigs(i) > 0.05
1466         str{j} = [str{j} sigStr];
1467     else
1468         str{j} = ['\bf' str{j} sigStr '\rm'];
1469     end
1470 end
1471 end
1472
1473
1474
1475 %% Convert the event statistics to strings.
1476 function [str sigs] = eventStats2strs(worms, isWormUsed, ...
1477     controls, isControlUsed, sig, sigI)
1478
1479 % Initialize special ascii symbols.
1480 semChar = '';
1481 sepStr = '      ';
1482
1483 % Initialize the names.
1484 names = {
1485     'FREQ'
1486     'TIME'
1487     'DIST'};
1488
1489 % Allocate memory.
1490 str = cell(length(worms) + 1, 1);
1491 sigs = nan(length(worms), 1);
1492
1493 % % Show the names.
1494 % str{1} = wormName;
1495 % if ~isempty(controlName)
1496 %     str{1} = [str{1} ' [' controlName ']'];
1497 % end
1498
1499 % Show the worm samples.
1500 %str{1} = [str{1} sepStr 'WORMS=' num2str(wormHist.sets.samples, '%.0G')];
1501 wormSamples = worms(1).samples;
1502 if ~isempty(isWormUsed)
1503     wormSamples = sum(isWormUsed);
1504 end
1505 str{1} = ['WORMS = ' num2str(wormSamples, '%.3G')];
1506
1507 % Show the control samples.
1508 if ~isempty(controls)
1509     controlSamples = controls(1).samples;
1510     if ~isempty(isControlUsed)
1511         controlSamples = sum(isControlUsed);
1512     end
1513     str{1} = [str{1} '   [' num2str(controlSamples, '%.3G') ']'];
1514 end
1515
1516 % Determine the square root of the sample sets.
1517 wormSqrt = sqrt(wormSamples);
1518 if ~isempty(controls)
1519     controlSqrt = sqrt(controlSamples);
1520 end
1521
1522 % Convert the statistics to strings.
1523 for i = 1:length(worms)
1524
1525     % Filter the worm data.
1526     wormData = worms(i).data;
1527     if ~isempty(isWormUsed)
1528         wormData = wormData(isWormUsed);
1529     end
1530
1531     % Filter the control data.
1532     if ~isempty(controls)
1533         controlData = controls(i).data;
1534         if ~isempty(isControlUsed)
1535             controlData = controlData(isControlUsed);
1536         end
1537     end
1538
1539     % Determine the inequality between experiment and control.
1540     wormMean = mean(wormData);
1541     eqStr = '   ';
1542     if ~isempty(controls)
1543         controlMean = mean(controlData);
1544         if wormMean > controlMean
1545             %eqStr = ' > ';
1546             eqStr = ' >>> ';
1547         elseif wormMean < controlMean
1548             %eqStr = ' < ';
1549             eqStr = ' <<< ';
1550         end
1551     end
1552
1553     % Determine the separator string.
1554     preStr = [];
1555 %     if ~mod(i, 2)
1556 %         preStr = sepStr;
1557 %     end
1558
1559     % Show the data name.
1560     j = i + 1;
1561     str{j} = [str{j} preStr upper(names{i}) ' = ' ];
1562
1563     % No data.
1564     if isnan(wormMean) && (isempty(controls) || isnan(controlMean))
1565         str{j} = [str{j} 'NO DATA'];
1566         sigs(i) = NaN;
1567         continue;
1568     end
1569
1570     % Don't show the inequality between experiment and control.
1571     sigStr = [];
1572     if isempty(sig)
1573         eqStr = '   ';
1574
1575     % Determine the significance.
1576     else
1577         k = sigI + i - 1;
1578         sigs(i) = sig.q(k);
1579
1580         % The significance was not measured.
1581         if isnan(sigs(i))
1582             eqStr = '   ';
1583
1584         % Show the significance.
1585         else
1586 %             % Determine the power.
1587 %             if isnan(sig.power(k))
1588 %                 betaStr = '1';
1589 %             else
1590 %                 betaStr = num2str(1 - sig.power(k), '%.2G');
1591 %             end
1592
1593             % Show the significance.
1594             sigStr = [sepStr '(p=' num2str(sig.p(k), '%.2G') ...
1595                 ', q=' num2str(sig.q(k), '%.2G')];
1596 %                 ', \beta=' betaStr];
1597             sigStr = [sigStr ')   ' p2stars(sigs(i))];
1598
1599             % Don't show the inequality between experiment and control.
1600             if sigs(i) > 0.05
1601                 eqStr = '   ';
1602             end
1603         end
1604     end
1605
1606     % Compute the worm statistics.
1607     sufStr = [];
1608     wormSEM = std(wormData) / wormSqrt;
1609     if i > 1
1610         wormMean  = wormMean * 100;
1611         wormSEM = wormSEM * 100;
1612         sufStr = '%';
1613     end
1614
1615     % Show the worm statistics.
1616     if isnan(wormMean)
1617         dataStr = 'NO DATA';
1618     else
1619         meanStr = num2str(wormMean, '%.3G');
1620         semStr = num2str(wormSEM, '%.3G');
1621         dataStr = [meanStr semChar semStr sufStr];
1622     end
1623     str{j} = [str{j} dataStr];
1624
1625     % Show the control statistics.
1626     if ~isempty(controls)
1627
1628         % Compute the control statistics.
1629         controlSEM =  std(controlData) / controlSqrt;
1630         if i > 1
1631             controlMean  = controlMean * 100;
1632             controlSEM = controlSEM * 100;
1633         end
1634
1635         % Show the control statistics.
1636         if isnan(controlMean)
1637             dataStr = 'NO DATA';
1638         else
1639             meanStr = num2str(controlMean, '%.3G');
1640             semStr = num2str(controlSEM, '%.3G');
1641             dataStr = [meanStr semChar semStr sufStr];
1642         end
1643         str{j} = [str{j} eqStr '[' dataStr ']'];
1644     end
1645
1646     % Show the significance.
1647     if sigs(i) > 0.05
1648         str{j} = [str{j} sigStr];
1649     else
1650         str{j} = ['\bf' str{j} sigStr '\rm'];
1651     end
1652 end
1653 end
1654
1655
1656
1657 %% Convert information to a page title.
1658 function str = info2pageTitle(wormName, controlName, featureI, ...
1659     featureNames, dataInfo)
1660
1661 % Add the names.
1662 str = wormName;
1663 if ~isempty(controlName)
1664     str = ['\it' str ' vs. ' controlName ' \rm'];
1665 end
1666 %str = [str ' &bull; '];
1667 str = [str '      \bf'];
1668
1669 % Add the feature categories.
1670 categories = unique([dataInfo(featureI).category]);
1671 for i = 1:length(categories)
1672
1673     % Add a separator.
1674     if i > 1
1675         str = [str ', '];
1676     end
1677
1678     % Add the category.
1679     switch categories(i)
1680         case 'm'
1681             str  = [str 'MORPHOLOGY'];
1682         case 's'
1683             str  = [str 'POSTURE'];
1684         case 'l'
1685             str  = [str 'MOTION'];
1686         case 'p'
1687             str  = [str 'PATH'];
1688     end
1689 end
1690 str = [str ': '];
1691
1692 % Add the features.
1693 for i = 1:length(featureI)
1694
1695     % Add a separator.
1696     if i > 1
1697         str = [str ', '];
1698     end
1699
1700     % Add the feature.
1701     str = [str featureNames{i}];
1702 end
1703
1704 % Pad the title.
1705 str = [str ' '];
1706 end