Description of display
display
PURPOSE
DISPLAY(VR) display for a videoReader object
SYNOPSIS
function display(vr)
DESCRIPTION
DISPLAY(VR) display for a videoReader object
CROSS-REFERENCE INFORMATION
This function calls:
disp DISP(vr) displays a videoReader object without printing its name.
get INFO=GET(VR)
disp DISP(vw) displays a videoWriter object without printing its name.
get INFO=GET(VW)
This function is called by:
SOURCE CODE
function display(vr)
%DISPLAY(VR) display for a videoReader object
if isequal(get(0,'FormatSpacing'),'compact')
   disp([inputname(1) ' =']);
   disp(vr)
else
   disp(' ')
   disp([inputname(1) ' =']);
   disp(' ');
   disp(vr)
end