Description of disp
disp
PURPOSE
DISP(vr) displays a videoReader object without printing its name.
SYNOPSIS
function disp(vr)
DESCRIPTION
DISP(vr) displays a videoReader object without printing its name.
CROSS-REFERENCE INFORMATION
This function calls:
disp DISP(vr) displays a videoReader object without printing its name.
get INFO=GET(VR)
disp DISP(vw) displays a videoWriter object without printing its name.
get INFO=GET(VW)
This function is called by:
disp DISP(vr) displays a videoReader object without printing its name.
display DISPLAY(VR) display for a videoReader object
disp DISP(vw) displays a videoWriter object without printing its name.
display DISPLAY(VR) display for a videoReader object
SOURCE CODE
function disp(vr)
%DISP(vr) displays a videoReader object without printing its name.
ctor = class(vr);
info = get(vr);
% actual display
disp(['  ' ctor ' object']);
if ~isequal(get(0,'FormatSpacing'),'compact')
  disp(' ');
end
disp(info);