Description of getframe
getframe
PURPOSE
FRAME=GETFRAME(VR)
SYNOPSIS
function frame = getframe(vr)
DESCRIPTION
FRAME=GETFRAME(VR)
  Returns the current frame that has been read in from video VR.  Calling
  GETFRAME does not automatically advance the current frame so the user
  must first call NEXT, STEP, or SEEK before calling GETFRAME the
  first time.  This makes it easy to write loops such as the example...
  Example:
    vr = videoReader(...);
    while (next(vr))
      img = getframe(vr);
      % ...do something...
    end
    vr = close(vr);
SEE ALSO
  videoReader
  videoReader/get
  videoReader/getnext
  videoReader/next
  videoReader/seek
  videoReader/step
Copyright (c) 2006 Gerald Dalley
See "MIT.txt" in the installation directory for licensing details (especially
when using this library on GNU/Linux).
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
getnext FRAME=GETNEXT(VR)
videoPlayer function vp = videoPlayer(varargin)
addFrameDemo addFrameDemo
analyzeNumFinalHiddenFrames analyzeNumFinalHiddenFrames
concatReadTests concatReadTests
divxSeekExpmt divxSeekExpmt
doFullRead IMAGES=DOFULLREAD(...)
doMultiFullReadTest DOMULTIFULLREADTEST(...)
doPreciseSeekTests DOPRECISESEEKTESTS(...)
getLoadableFiles loadables = getLoadableFiles(...)
longWriteTest longWriteTests(plugin)
testMatrix testMatrix
writeTests writeTests(plugin)
videoReader_concat videoReader_concat
videoread VIDEOREAD Read an video file in a mannter compatible with Matlab's
SOURCE CODE
function frame = getframe(vr)
%FRAME=GETFRAME(VR)
%  Returns the current frame that has been read in from video VR.  Calling
%  GETFRAME does not automatically advance the current frame so the user
%  must first call NEXT, STEP, or SEEK before calling GETFRAME the
%  first time.  This makes it easy to write loops such as the example...
%
%  Example:
%    vr = videoReader(...);
%    while (next(vr))
%      img = getframe(vr);
%      % ...do something...
%    end
%    vr = close(vr);
%
%SEE ALSO
%  videoReader
%  videoReader/get
%  videoReader/getnext
%  videoReader/next
%  videoReader/seek
%  videoReader/step
%
%Copyright (c) 2006 Gerald Dalley
%See "MIT.txt" in the installation directory for licensing details (especially
%when using this library on GNU/Linux).
frame = feval(vr.plugin, 'getframe', vr.handle);