Description of color2TeX
color2TeX
PURPOSE
COLOR2TEX Convert a color to a TeX string.
SYNOPSIS
function str = color2TeX(color)
DESCRIPTION
COLOR2TEX Convert a color to a TeX string.
   STR = COLOR2TEX(COLOR)
   Input:
       color - the RGB color vector
   Output:
       str - a TeX string for the color
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
methodsTIF METHODSTIF Save worm details to a TIF.
plotWormPath PLOTWORMPATH Plot the worm path(s).
plotWormPathData PLOTWORMPATHDATA Plot the worm path data.
plotWormPathData2 PLOTWORMPATHDATA Plot the worm path data.
worm2TOCOntologyTIF WORM2TOCONTOLOGYTIF Save worm details to a TIF.
worm2summaryTIF WORM2SUMMARYTIF Save a worm summary to a TIF.
SOURCE CODE
function str = color2TeX(color)
%COLOR2TEX Convert a color to a TeX string.
%
%   STR = COLOR2TEX(COLOR)
%
%   Input:
%       color - the RGB color vector
%
%   Output:
%       str - a TeX string for the color
str = sprintf('\\color[rgb]{%f %f %f}', color(1), color(2), color(3));
end