Description of getStructField
getStructField
PURPOSE
GETSTRUCTFIELD Get a field in a structure.
SYNOPSIS
function data = getStructField(data, field, varargin)
DESCRIPTION
GETSTRUCTFIELD Get a field in a structure.
   DATA = GETSTRUCTFIELD(DATA, FIELD)
   DATA = GETSTRUCTFIELD(DATA, FIELD, ISSAFE)
   Inputs:
       data   - the structure
       field  - the field to get (a period delimited string)
       isSafe - are we using safe mode? when using safe mode, each field
                is tested to ensure it exists; the default is no (false)
   Output:
       data - the field data;
              empty if the field cannot be found
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
loadStructField LOADSTRUCTFIELD Load a struct field from a file.
plotWormStats PLOTWORMSTATS Plot the worm statistics.
worm2CSV WORM2CSV Convert worm features to a CSV file.
worm2TOCOntologyTIF WORM2TOCONTOLOGYTIF Save worm details to a TIF.
worm2detailsPDF2 WORM2DETAILSPDF Save worm details to a PDF.
worm2detailsTIF WORM2DETAILSTIF Save worm details to a TIF.
worm2summaryPDF2 WORM2SUMMARYPDF Save a worm summary to a PDF.
worm2summaryTIF WORM2SUMMARYTIF Save a worm summary to a TIF.
wormStatsInfo2CSV WORMSTATSINFO2CSV Convert the worm statistics to a set of CSV files.
filterWormHist FILTERWORMHIST Filter worm features to meet specific criteria.
worm2NormTimes WORM2NORMTIMES Normalize worm feature time series.
worm2StatsInfo WORM2STATSINFO Compute worm statistics information and save it to a file.
worm2histogram WORM2HISTOGRAM Convert worm features to their histogram.
worm2histogram2 WORM2HISTOGRAM Convert worm features to their histogram.
wormStats2Matrix2 WORMSTATS2MATRIX Construct and save a features x worms matrix.
wormStatsInfo WORMFEATUREINFO Get information for computing the worm statistics.
SOURCE CODE
function data = getStructField(data, field, varargin)
%GETSTRUCTFIELD Get a field in a structure.
%
%   DATA = GETSTRUCTFIELD(DATA, FIELD)
%
%   DATA = GETSTRUCTFIELD(DATA, FIELD, ISSAFE)
%
%   Inputs:
%       data   - the structure
%       field  - the field to get (a period delimited string)
%       isSafe - are we using safe mode? when using safe mode, each field
%                is tested to ensure it exists; the default is no (false)
%
%   Output:
%       data - the field data;
%              empty if the field cannot be found
% Are we using safe mode?
isSafe = false;
if ~isempty(varargin)
    isSafe = varargin{1};
end
% No data.
if isempty(field)
    return;
% Get the field.
else
    fields = textscan(field, '%s', 'Delimiter', '.');
    fields = fields{1};
    % Check each field to ensure it exists before traversing.
    if isSafe
        for i = 1:length(fields)
            % Have we reached the end?
            if isempty(data) || ~isstruct(data) || ~isfield(data, fields{i})
                data = [];
                return;
            end
            % Go deeper.
            data = [data.(fields{i})];
        end
    % Traverse each field without checking to ensure it exists.
    else
        for i = 1:length(fields)
            % Have we reached the end?
            if isempty(data) || ~isstruct(data)
                data = [];
                return;
            end
            % Go deeper.
            data = [data.(fields{i})];
        end
    end
end
end