Description of loadStructField
loadStructField
PURPOSE
LOADSTRUCTFIELD Load a struct field from a file.
SYNOPSIS
function data = loadStructField(fileName, structName, field)
DESCRIPTION
LOADSTRUCTFIELD Load a struct field from a file.
   DATA = LOADSTRUCTFIELD(FILENAME, DATA, FIELD)
   Inputs:
       fileName   - the name of the file with the struct
       structName - the name of the struct to load
       field      - the field to get (a period delimited string)
   Output:
       data - the field data
CROSS-REFERENCE INFORMATION
This function calls:
getStructField GETSTRUCTFIELD Get a field in a structure.
This function is called by:
addWormHistograms ADDWORMHISTOGRAMS Combine worm histograms.
addWormStats WORM2STATS Combine worm statistics.
worm2NormTimes WORM2NORMTIMES Normalize worm feature time series.
worm2histogram WORM2HISTOGRAM Convert worm features to their histogram.
worm2histogram2 WORM2HISTOGRAM Convert worm features to their histogram.
worm2stats WORM2STATS Convert worms to a set of statistics.
SOURCE CODE
function data = loadStructField(fileName, structName, field)
%LOADSTRUCTFIELD Load a struct field from a file.
%
%   DATA = LOADSTRUCTFIELD(FILENAME, DATA, FIELD)
%
%   Inputs:
%       fileName   - the name of the file with the struct
%       structName - the name of the struct to load
%       field      - the field to get (a period delimited string)
%
%   Output:
%       data - the field data
% Load the struct.
structData = load(fileName, structName);
% Is the struct empty?
if ~isfield(structData, structName)
    data = [];
    return;
end
% Get the field.
data = getStructField(structData, [structName '.' field]);
% Free the memory.
clear structData;
end