Description of setStructField
setStructField
PURPOSE
SETSTRUCTFIELD Set a field in a structure.
SYNOPSIS
function data = setStructField(data, field, value)
DESCRIPTION
SETSTRUCTFIELD Set a field in a structure.
   DATA = SETSTRUCTFIELD(DATA, FIELD, VALUE)
   Inputs:
       data  - the structure
       field - the field to set (a period delimited string)
       value - the value for the field
   Output:
       data - a structure with the field set to the value
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
wormDisplayInfo WORMDISPLAYINFO Get information for displaying the worm data.
worm2CSV WORM2CSV Convert worm features to a CSV file.
worm2histogram WORM2HISTOGRAM Convert worm features to their histogram.
worm2histogram2 WORM2HISTOGRAM Convert worm features to their histogram.
SOURCE CODE
function data = setStructField(data, field, value)
%SETSTRUCTFIELD Set a field in a structure.
%
%   DATA = SETSTRUCTFIELD(DATA, FIELD, VALUE)
%
%   Inputs:
%       data  - the structure
%       field - the field to set (a period delimited string)
%       value - the value for the field
%
%   Output:
%       data - a structure with the field set to the value
eval(['data.' field '=value;']);
end