Description of xmlReadTag
xmlReadTag
PURPOSE
XMLREADTAG Read a tag from an XML document.
SYNOPSIS
function values = xmlReadTag(xml, tag)
DESCRIPTION
XMLREADTAG Read a tag from an XML document.
   VALUES = XMLREADTAG(XML, TAG)
   Inputs:
       xml - the xml document
       tag - the period-delimited path for the tag
   Output:
       values - the values for the given tag
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
findStageMovement FINDSTAGEMOVEMENT Find stage movements in a worm experiment.
readPixels2Microns READPIXELS2MICRONS Read the experiment information file and compute the
video2Vignette VIDEO2VIGNETTE Compute the vignette from a video. Exclude the largest
SUBFUNCTIONS
function values = getElement(element, path, i)
SOURCE CODE
function values = xmlReadTag(xml, tag)
%XMLREADTAG Read a tag from an XML document.
%
%   VALUES = XMLREADTAG(XML, TAG)
%
%   Inputs:
%       xml - the xml document
%       tag - the period-delimited path for the tag
%
%   Output:
%       values - the values for the given tag
% Translate the tag to a path.
path = [];
i = 1;
while ~isempty(tag)
    [name tag] = strtok(tag, '.');
    if ~isempty(name)
        path{i} = name;
        i = i + 1;
    end
end
% Get the values associated with the tag.
values = char(getElement(xml, path, 1));
end
% Get the values associated with a path.
function values = getElement(element, path, i)
% We've reached the requested node.
values = [];
if i == length(path) + 1
    % Search for text (value) nodes.
    k = 1;
    nodes = element.getChildNodes;
    for j = 0:(nodes.getLength - 1)
        if nodes.item(j).getNodeType == element.TEXT_NODE
            value = strtrim(char(nodes.item(j).getNodeValue));
            % Add the value to the list.
            if ~isempty(value)
                values{k} = value;
                k = k + 1;
            end
        end
    end
% Search for the next node in the path.
else
    nodes = element.getElementsByTagName(path{i});
    for j = 0:(nodes.getLength - 1)
        % Follow the node.
        if nodes.item(j).hasChildNodes
            values = cat(2, values, getElement(nodes.item(j), path, i + 1));
        end
    end
end
end