Description of split
split
PURPOSE
L=SPLIT(S,D) splits a string S delimited by characters in D. Meant to
SYNOPSIS
function l = split(d,s)
DESCRIPTION
L=SPLIT(S,D) splits a string S delimited by characters in D.  Meant to
             work roughly like the PERL split function (but without any
             regular expression support).  Internally uses STRTOK to do
             the splitting.  Returns a cell array of strings.
Example:
    >> split('_/', 'this_is___a_/_string/_//')
    ans =
        'this'    'is'    'a'    'string'   []
Written by Gerald Dalley (dalleyg@mit.edu), 2004
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
buildVideoIoPackages buildVideoIoPackages
getFileList [dirname,filenames] = getFileList(filepattern)
videoIoSysInfo videoIoSysInfo
SOURCE CODE
function l = split(d,s)
%L=SPLIT(S,D) splits a string S delimited by characters in D.  Meant to
%             work roughly like the PERL split function (but without any
%             regular expression support).  Internally uses STRTOK to do
%             the splitting.  Returns a cell array of strings.
%
%Example:
%    >> split('_/', 'this_is___a_/_string/_//')
%    ans =
%        'this'    'is'    'a'    'string'   []
%
%Written by Gerald Dalley (dalleyg@mit.edu), 2004
l = {};
while ~isempty(s)
    [t,s] = strtok(s,d); %#ok<STTOK> -- textscan isn't powerful enough
    l = {l{:}, t};
end